
AzerothDataCollector_SpellsDB = {
["module_key"] = "spells",
["by_character"] = {
["Player-3674-09D241D0"] = {
["spells"] = {
["updated_at"] = 1778494570,
["records"] = {
{
["tab"] = "General",
["name"] = "Anomaly Detection Mark I",
["item_type"] = "1",
["id"] = 382499,
["spell_book_index"] = 1,
},
{
["tab"] = "General",
["name"] = "Arcane Torrent",
["item_type"] = "1",
["id"] = 28730,
["spell_book_index"] = 2,
},
{
["tab"] = "General",
["name"] = "Auto Attack",
["item_type"] = "1",
["id"] = 6603,
["spell_book_index"] = 3,
},
{
["tab"] = "General",
["name"] = "Mechanism Bypass",
["item_type"] = "1",
["id"] = 382501,
["spell_book_index"] = 6,
},
{
["tab"] = "General",
["name"] = "Mobile Banking",
["item_type"] = "1",
["id"] = 83958,
["spell_book_index"] = 7,
},
{
["tab"] = "General",
["name"] = "Recuperate",
["item_type"] = "1",
["id"] = 1231411,
["spell_book_index"] = 8,
},
{
["tab"] = "General",
["name"] = "Revive Battle Pets",
["item_type"] = "1",
["id"] = 125439,
["spell_book_index"] = 9,
},
{
["tab"] = "General",
["name"] = "Shoot",
["item_type"] = "1",
["id"] = 5019,
["spell_book_index"] = 10,
},
{
["tab"] = "General",
["name"] = "Arcane Acuity",
["item_type"] = "1",
["id"] = 154742,
["spell_book_index"] = 14,
},
{
["tab"] = "General",
["name"] = "Arcane Affinity",
["item_type"] = "1",
["id"] = 28877,
["spell_book_index"] = 15,
},
{
["tab"] = "General",
["name"] = "Arcane Resistance",
["item_type"] = "1",
["id"] = 822,
["spell_book_index"] = 16,
},
{
["tab"] = "General",
["name"] = "Armor Skills",
["item_type"] = "1",
["id"] = 76277,
["spell_book_index"] = 17,
},
{
["tab"] = "General",
["name"] = "Battle for Azeroth Pathfinder",
["item_type"] = "1",
["id"] = 278833,
["spell_book_index"] = 18,
},
{
["tab"] = "General",
["name"] = "Grove Invigoration",
["item_type"] = "1",
["id"] = 322721,
["spell_book_index"] = 19,
},
{
["tab"] = "General",
["name"] = "Guild Mail",
["item_type"] = "1",
["id"] = 83951,
["spell_book_index"] = 20,
},
{
["tab"] = "General",
["name"] = "Hasty Hearth",
["item_type"] = "1",
["id"] = 83944,
["spell_book_index"] = 21,
},
{
["tab"] = "General",
["name"] = "Languages",
["item_type"] = "1",
["id"] = 79748,
["spell_book_index"] = 22,
},
{
["tab"] = "General",
["name"] = "Master Riding",
["item_type"] = "1",
["id"] = 90265,
["spell_book_index"] = 23,
},
{
["tab"] = "General",
["name"] = "Mount Up",
["item_type"] = "1",
["id"] = 78633,
["spell_book_index"] = 24,
},
{
["tab"] = "General",
["name"] = "The Quick and the Dead",
["item_type"] = "1",
["id"] = 83950,
["spell_book_index"] = 25,
},
{
["tab"] = "General",
["name"] = "Weapon Skills",
["item_type"] = "1",
["id"] = 76299,
["spell_book_index"] = 26,
},
{
["tab"] = "Warlock",
["name"] = "Blight of Weakness",
["item_type"] = "1",
["id"] = 1271748,
["spell_book_index"] = 76,
},
{
["tab"] = "Warlock",
["name"] = "Command Demon",
["item_type"] = "1",
["id"] = 119898,
["spell_book_index"] = 77,
},
{
["tab"] = "Warlock",
["name"] = "Create Healthstone",
["item_type"] = "1",
["id"] = 6201,
["spell_book_index"] = 78,
},
{
["tab"] = "Warlock",
["name"] = "Create Soulwell",
["item_type"] = "1",
["id"] = 29893,
["spell_book_index"] = 79,
},
{
["tab"] = "Warlock",
["name"] = "Curse of Exhaustion",
["item_type"] = "1",
["id"] = 334275,
["spell_book_index"] = 80,
},
{
["tab"] = "Warlock",
["name"] = "Curse of Weakness",
["item_type"] = "1",
["id"] = 702,
["spell_book_index"] = 81,
},
{
["tab"] = "Warlock",
["name"] = "Dark Pact",
["item_type"] = "1",
["id"] = 108416,
["spell_book_index"] = 82,
},
{
["tab"] = "Warlock",
["name"] = "Drain Life",
["item_type"] = "1",
["id"] = 234153,
["spell_book_index"] = 83,
},
{
["tab"] = "Warlock",
["name"] = "Eye of Kilrogg",
["item_type"] = "1",
["id"] = 126,
["spell_book_index"] = 84,
},
{
["tab"] = "Warlock",
["name"] = "Fear",
["item_type"] = "1",
["id"] = 5782,
["spell_book_index"] = 85,
},
{
["tab"] = "Warlock",
["name"] = "Fel Domination",
["item_type"] = "1",
["id"] = 333889,
["spell_book_index"] = 86,
},
{
["tab"] = "Warlock",
["name"] = "Mortal Coil",
["item_type"] = "1",
["id"] = 6789,
["spell_book_index"] = 87,
},
{
["tab"] = "Warlock",
["name"] = "Ritual of Doom",
["item_type"] = "1",
["id"] = 342601,
["spell_book_index"] = 88,
},
{
["tab"] = "Warlock",
["name"] = "Ritual of Summoning",
["item_type"] = "1",
["id"] = 698,
["spell_book_index"] = 89,
},
{
["tab"] = "Warlock",
["name"] = "Shadow Bolt",
["item_type"] = "1",
["id"] = 686,
["spell_book_index"] = 90,
},
{
["tab"] = "Warlock",
["name"] = "Shadowfury",
["item_type"] = "1",
["id"] = 30283,
["spell_book_index"] = 91,
},
{
["tab"] = "Warlock",
["name"] = "Soulstone",
["item_type"] = "1",
["id"] = 20707,
["spell_book_index"] = 92,
},
{
["tab"] = "Warlock",
["name"] = "Subjugate Demon",
["item_type"] = "1",
["id"] = 1098,
["spell_book_index"] = 93,
},
{
["tab"] = "Warlock",
["name"] = "Unending Breath",
["item_type"] = "1",
["id"] = 5697,
["spell_book_index"] = 95,
},
{
["tab"] = "Warlock",
["name"] = "Unending Resolve",
["item_type"] = "1",
["id"] = 104773,
["spell_book_index"] = 96,
},
{
["tab"] = "Warlock",
["name"] = "Soul Shards",
["item_type"] = "1",
["id"] = 246985,
["spell_book_index"] = 97,
},
{
["tab"] = "Demonology",
["name"] = "Call Dreadstalkers",
["item_type"] = "1",
["id"] = 104316,
["spell_book_index"] = 104,
},
{
["tab"] = "Demonology",
["name"] = "Demonbolt",
["item_type"] = "1",
["id"] = 264178,
["spell_book_index"] = 105,
},
{
["tab"] = "Demonology",
["name"] = "Hand of Gul'dan",
["item_type"] = "1",
["id"] = 105174,
["spell_book_index"] = 106,
},
{
["tab"] = "Demonology",
["name"] = "Summon Demonic Tyrant",
["item_type"] = "1",
["id"] = 265187,
["spell_book_index"] = 107,
},
{
["tab"] = "Demonology",
["name"] = "Demonic Core",
["item_type"] = "1",
["id"] = 267102,
["spell_book_index"] = 108,
},
{
["tab"] = "Demonology",
["name"] = "Mastery: Master Demonologist",
["item_type"] = "1",
["id"] = 77219,
["spell_book_index"] = 109,
},
{
["tab"] = "Affliction",
["name"] = "Agony",
["item_type"] = "1",
["id"] = 980,
["spell_book_index"] = 112,
},
{
["tab"] = "Affliction",
["name"] = "Corruption",
["item_type"] = "1",
["id"] = 172,
["spell_book_index"] = 113,
},
{
["tab"] = "Affliction",
["name"] = "Dark Harvest",
["item_type"] = "1",
["id"] = 1257052,
["spell_book_index"] = 114,
},
{
["tab"] = "Affliction",
["name"] = "Haunt",
["item_type"] = "1",
["id"] = 48181,
["spell_book_index"] = 115,
},
{
["tab"] = "Affliction",
["name"] = "Malevolence",
["item_type"] = "1",
["id"] = 442726,
["spell_book_index"] = 116,
},
{
["tab"] = "Affliction",
["name"] = "Seed of Corruption",
["item_type"] = "1",
["id"] = 27243,
["spell_book_index"] = 117,
},
{
["tab"] = "Affliction",
["name"] = "Soulstone",
["item_type"] = "1",
["id"] = 231811,
["spell_book_index"] = 118,
},
{
["tab"] = "Affliction",
["name"] = "Summon Darkglare",
["item_type"] = "1",
["id"] = 205180,
["spell_book_index"] = 119,
},
{
["tab"] = "Affliction",
["name"] = "Unstable Affliction",
["item_type"] = "1",
["id"] = 1259790,
["spell_book_index"] = 120,
},
{
["tab"] = "Affliction",
["name"] = "Aura of Enfeeblement",
["item_type"] = "1",
["id"] = 440059,
["spell_book_index"] = 121,
},
{
["tab"] = "Affliction",
["name"] = "Mastery: Potent Afflictions",
["item_type"] = "1",
["id"] = 77215,
["spell_book_index"] = 122,
},
{
["tab"] = "Affliction",
["name"] = "Nightfall",
["item_type"] = "1",
["id"] = 108558,
["spell_book_index"] = 123,
},
{
["tab"] = "Destruction",
["name"] = "Cataclysm",
["item_type"] = "1",
["id"] = 152108,
["spell_book_index"] = 124,
},
{
["tab"] = "Destruction",
["name"] = "Channel Demonfire",
["item_type"] = "1",
["id"] = 196447,
["spell_book_index"] = 125,
},
{
["tab"] = "Destruction",
["name"] = "Chaos Bolt",
["item_type"] = "1",
["id"] = 116858,
["spell_book_index"] = 126,
},
{
["tab"] = "Destruction",
["name"] = "Conflagrate",
["item_type"] = "1",
["id"] = 17962,
["spell_book_index"] = 127,
},
{
["tab"] = "Destruction",
["name"] = "Grimoire of Sacrifice",
["item_type"] = "1",
["id"] = 108503,
["spell_book_index"] = 128,
},
{
["tab"] = "Destruction",
["name"] = "Havoc",
["item_type"] = "1",
["id"] = 80240,
["spell_book_index"] = 129,
},
{
["tab"] = "Destruction",
["name"] = "Immolate",
["item_type"] = "1",
["id"] = 348,
["spell_book_index"] = 130,
},
{
["tab"] = "Destruction",
["name"] = "Incinerate",
["item_type"] = "1",
["id"] = 29722,
["spell_book_index"] = 131,
},
{
["tab"] = "Destruction",
["name"] = "Rain of Fire",
["item_type"] = "1",
["id"] = 5740,
["spell_book_index"] = 132,
},
{
["tab"] = "Destruction",
["name"] = "Rain of Fire",
["item_type"] = "1",
["id"] = 1214467,
["spell_book_index"] = 133,
},
{
["tab"] = "Destruction",
["name"] = "Shadowburn",
["item_type"] = "1",
["id"] = 17877,
["spell_book_index"] = 134,
},
{
["tab"] = "Destruction",
["name"] = "Soul Fire",
["item_type"] = "1",
["id"] = 6353,
["spell_book_index"] = 135,
},
{
["tab"] = "Destruction",
["name"] = "Soulstone",
["item_type"] = "1",
["id"] = 231811,
["spell_book_index"] = 136,
},
{
["tab"] = "Destruction",
["name"] = "Summon Infernal",
["item_type"] = "1",
["id"] = 1122,
["spell_book_index"] = 137,
},
{
["tab"] = "Destruction",
["name"] = "Mastery: Chaotic Energies",
["item_type"] = "1",
["id"] = 77220,
["spell_book_index"] = 138,
},
},
["partial"] = false,
},
},
["Player-3674-09C5872B"] = {
["spells"] = {
["updated_at"] = 1778494534,
["partial"] = false,
["records"] = {
{
["tab"] = "General",
["name"] = "Anomaly Detection Mark I",
["item_type"] = "1",
["id"] = 382499,
["spell_book_index"] = 1,
},
{
["tab"] = "General",
["name"] = "Arcane Torrent",
["item_type"] = "1",
["id"] = 202719,
["spell_book_index"] = 2,
},
{
["tab"] = "General",
["name"] = "Auto Attack",
["item_type"] = "1",
["id"] = 6603,
["spell_book_index"] = 3,
},
{
["tab"] = "General",
["name"] = "Mechanism Bypass",
["item_type"] = "1",
["id"] = 382501,
["spell_book_index"] = 6,
},
{
["tab"] = "General",
["name"] = "Recuperate",
["item_type"] = "1",
["id"] = 1231411,
["spell_book_index"] = 8,
},
{
["tab"] = "General",
["name"] = "Revive Battle Pets",
["item_type"] = "1",
["id"] = 125439,
["spell_book_index"] = 9,
},
{
["tab"] = "General",
["name"] = "Vindicaar Matrix Crystal",
["item_type"] = "1",
["id"] = 251463,
["spell_book_index"] = 12,
},
{
["tab"] = "General",
["name"] = "Arcane Acuity",
["item_type"] = "1",
["id"] = 154742,
["spell_book_index"] = 14,
},
{
["tab"] = "General",
["name"] = "Arcane Affinity",
["item_type"] = "1",
["id"] = 28877,
["spell_book_index"] = 15,
},
{
["tab"] = "General",
["name"] = "Arcane Resistance",
["item_type"] = "1",
["id"] = 822,
["spell_book_index"] = 16,
},
{
["tab"] = "General",
["name"] = "Armor Skills",
["item_type"] = "1",
["id"] = 202782,
["spell_book_index"] = 17,
},
{
["tab"] = "General",
["name"] = "Battle for Azeroth Pathfinder",
["item_type"] = "1",
["id"] = 278833,
["spell_book_index"] = 18,
},
{
["tab"] = "General",
["name"] = "Grove Invigoration",
["item_type"] = "1",
["id"] = 322721,
["spell_book_index"] = 19,
},
{
["tab"] = "General",
["name"] = "Languages",
["item_type"] = "1",
["id"] = 79748,
["spell_book_index"] = 20,
},
{
["tab"] = "General",
["name"] = "Master Riding",
["item_type"] = "1",
["id"] = 90265,
["spell_book_index"] = 21,
},
{
["tab"] = "General",
["name"] = "Weapon Skills",
["item_type"] = "1",
["id"] = 202783,
["spell_book_index"] = 22,
},
{
["tab"] = "Demon Hunter",
["name"] = "Consume Magic",
["item_type"] = "1",
["id"] = 278326,
["spell_book_index"] = 75,
},
{
["tab"] = "Demon Hunter",
["name"] = "Darkness",
["item_type"] = "1",
["id"] = 196718,
["spell_book_index"] = 76,
},
{
["tab"] = "Demon Hunter",
["name"] = "Disrupt",
["item_type"] = "1",
["id"] = 183752,
["spell_book_index"] = 77,
},
{
["tab"] = "Demon Hunter",
["name"] = "Glide",
["item_type"] = "1",
["id"] = 131347,
["spell_book_index"] = 78,
},
{
["tab"] = "Demon Hunter",
["name"] = "Immolation Aura",
["item_type"] = "1",
["id"] = 258920,
["spell_book_index"] = 79,
},
{
["tab"] = "Demon Hunter",
["name"] = "Imprison",
["item_type"] = "1",
["id"] = 217832,
["spell_book_index"] = 80,
},
{
["tab"] = "Demon Hunter",
["name"] = "Metamorphosis",
["item_type"] = "1",
["id"] = 191427,
["spell_book_index"] = 81,
},
{
["tab"] = "Demon Hunter",
["name"] = "Sigil of Misery",
["item_type"] = "1",
["id"] = 207684,
["spell_book_index"] = 82,
},
{
["tab"] = "Demon Hunter",
["name"] = "Spectral Sight",
["item_type"] = "1",
["id"] = 188501,
["spell_book_index"] = 83,
},
{
["tab"] = "Demon Hunter",
["name"] = "Throw Glaive",
["item_type"] = "1",
["id"] = 185123,
["spell_book_index"] = 84,
},
{
["tab"] = "Demon Hunter",
["name"] = "Torment",
["item_type"] = "1",
["id"] = 185245,
["spell_book_index"] = 85,
},
{
["tab"] = "Demon Hunter",
["name"] = "Vengeful Retreat",
["item_type"] = "1",
["id"] = 198793,
["spell_book_index"] = 86,
},
{
["tab"] = "Demon Hunter",
["name"] = "Chaos Brand",
["item_type"] = "1",
["id"] = 255260,
["spell_book_index"] = 87,
},
{
["tab"] = "Demon Hunter",
["name"] = "Double Jump",
["item_type"] = "1",
["id"] = 196055,
["spell_book_index"] = 88,
},
{
["tab"] = "Havoc",
["name"] = "Blade Dance",
["item_type"] = "1",
["id"] = 188499,
["spell_book_index"] = 91,
},
{
["tab"] = "Havoc",
["name"] = "Blur",
["item_type"] = "1",
["id"] = 198589,
["spell_book_index"] = 92,
},
{
["tab"] = "Havoc",
["name"] = "Chaos Nova",
["item_type"] = "1",
["id"] = 179057,
["spell_book_index"] = 93,
},
{
["tab"] = "Havoc",
["name"] = "Chaos Strike",
["item_type"] = "1",
["id"] = 162794,
["spell_book_index"] = 94,
},
{
["tab"] = "Havoc",
["name"] = "Eye Beam",
["item_type"] = "1",
["id"] = 198013,
["spell_book_index"] = 95,
},
{
["tab"] = "Havoc",
["name"] = "Fel Rush",
["item_type"] = "1",
["id"] = 195072,
["spell_book_index"] = 96,
},
{
["tab"] = "Havoc",
["name"] = "Felblade",
["item_type"] = "1",
["id"] = 232893,
["spell_book_index"] = 97,
},
{
["tab"] = "Havoc",
["name"] = "The Hunt",
["item_type"] = "1",
["id"] = 370965,
["spell_book_index"] = 98,
},
{
["tab"] = "Havoc",
["name"] = "Demon Blades",
["item_type"] = "1",
["id"] = 203555,
["spell_book_index"] = 99,
},
{
["tab"] = "Havoc",
["name"] = "Demonic Appetite",
["item_type"] = "1",
["id"] = 206478,
["spell_book_index"] = 100,
},
{
["tab"] = "Havoc",
["name"] = "Demonic Wards",
["item_type"] = "1",
["id"] = 278386,
["spell_book_index"] = 101,
},
{
["tab"] = "Havoc",
["name"] = "Mastery: Demonic Presence",
["item_type"] = "1",
["id"] = 185164,
["spell_book_index"] = 102,
},
{
["tab"] = "Havoc",
["name"] = "Shattered Souls",
["item_type"] = "1",
["id"] = 178940,
["spell_book_index"] = 103,
},
{
["tab"] = "Vengeance",
["name"] = "Demon Spikes",
["item_type"] = "1",
["id"] = 203720,
["spell_book_index"] = 105,
},
{
["tab"] = "Vengeance",
["name"] = "Demon Spikes",
["item_type"] = "1",
["id"] = 321028,
["spell_book_index"] = 106,
},
{
["tab"] = "Vengeance",
["name"] = "Fel Devastation",
["item_type"] = "1",
["id"] = 212084,
["spell_book_index"] = 107,
},
{
["tab"] = "Vengeance",
["name"] = "Fracture",
["item_type"] = "1",
["id"] = 263642,
["spell_book_index"] = 108,
},
{
["tab"] = "Vengeance",
["name"] = "Immolation Aura",
["item_type"] = "1",
["id"] = 320378,
["spell_book_index"] = 109,
},
{
["tab"] = "Vengeance",
["name"] = "Infernal Strike",
["item_type"] = "1",
["id"] = 189110,
["spell_book_index"] = 110,
},
{
["tab"] = "Vengeance",
["name"] = "Metamorphosis",
["item_type"] = "1",
["id"] = 187827,
["spell_book_index"] = 111,
},
{
["tab"] = "Vengeance",
["name"] = "Sigil of Flame",
["item_type"] = "1",
["id"] = 204596,
["spell_book_index"] = 112,
},
{
["tab"] = "Vengeance",
["name"] = "Soul Cleave",
["item_type"] = "1",
["id"] = 228477,
["spell_book_index"] = 113,
},
{
["tab"] = "Vengeance",
["name"] = "Throw Glaive",
["item_type"] = "1",
["id"] = 204157,
["spell_book_index"] = 114,
},
{
["tab"] = "Vengeance",
["name"] = "Demonic Wards",
["item_type"] = "1",
["id"] = 203513,
["spell_book_index"] = 115,
},
{
["tab"] = "Vengeance",
["name"] = "Fiery Brand",
["item_type"] = "1",
["id"] = 320962,
["spell_book_index"] = 116,
},
{
["tab"] = "Vengeance",
["name"] = "Fiery Brand",
["item_type"] = "1",
["id"] = 204021,
["spell_book_index"] = 117,
},
{
["tab"] = "Vengeance",
["name"] = "Sigil of Chains",
["item_type"] = "1",
["id"] = 202138,
["spell_book_index"] = 118,
},
{
["tab"] = "Vengeance",
["name"] = "Sigil of Silence",
["item_type"] = "1",
["id"] = 202137,
["spell_book_index"] = 119,
},
{
["tab"] = "Vengeance",
["name"] = "Sigil of Spite",
["item_type"] = "1",
["id"] = 390163,
["spell_book_index"] = 120,
},
{
["tab"] = "Vengeance",
["name"] = "Soul Carver",
["item_type"] = "1",
["id"] = 207407,
["spell_book_index"] = 121,
},
{
["tab"] = "Vengeance",
["name"] = "Spirit Bomb",
["item_type"] = "1",
["id"] = 247454,
["spell_book_index"] = 122,
},
{
["tab"] = "Vengeance",
["name"] = "Mastery: Fel Blood",
["item_type"] = "1",
["id"] = 203747,
["spell_book_index"] = 123,
},
{
["tab"] = "Vengeance",
["name"] = "Mastery: Fel Blood",
["item_type"] = "1",
["id"] = 321299,
["spell_book_index"] = 124,
},
{
["tab"] = "Vengeance",
["name"] = "Riposte",
["item_type"] = "1",
["id"] = 207197,
["spell_book_index"] = 125,
},
{
["tab"] = "Vengeance",
["name"] = "Shattered Souls",
["item_type"] = "1",
["id"] = 204254,
["spell_book_index"] = 126,
},
{
["tab"] = "Vengeance",
["name"] = "Thick Skin",
["item_type"] = "1",
["id"] = 320380,
["spell_book_index"] = 127,
},
{
["tab"] = "Devourer",
["name"] = "Blur",
["item_type"] = "1",
["id"] = 198589,
["spell_book_index"] = 128,
},
{
["tab"] = "Devourer",
["name"] = "Consume",
["item_type"] = "1",
["id"] = 473662,
["spell_book_index"] = 129,
},
{
["tab"] = "Devourer",
["name"] = "Reap",
["item_type"] = "1",
["id"] = 1226019,
["spell_book_index"] = 130,
},
{
["tab"] = "Devourer",
["name"] = "Shift",
["item_type"] = "1",
["id"] = 1234796,
["spell_book_index"] = 131,
},
{
["tab"] = "Devourer",
["name"] = "Soul Immolation",
["item_type"] = "1",
["id"] = 1241937,
["spell_book_index"] = 132,
},
{
["tab"] = "Devourer",
["name"] = "Spectral Sight",
["item_type"] = "1",
["id"] = 1251417,
["spell_book_index"] = 133,
},
{
["tab"] = "Devourer",
["name"] = "The Hunt",
["item_type"] = "1",
["id"] = 1246167,
["spell_book_index"] = 134,
},
{
["tab"] = "Devourer",
["name"] = "Void Metamorphosis",
["item_type"] = "1",
["id"] = 1217605,
["spell_book_index"] = 135,
},
{
["tab"] = "Devourer",
["name"] = "Void Nova",
["item_type"] = "1",
["id"] = 1234195,
["spell_book_index"] = 136,
},
{
["tab"] = "Devourer",
["name"] = "Void Ray",
["item_type"] = "1",
["id"] = 473728,
["spell_book_index"] = 137,
},
{
["tab"] = "Devourer",
["name"] = "Voidblade",
["item_type"] = "1",
["id"] = 1245412,
["spell_book_index"] = 138,
},
{
["tab"] = "Devourer",
["name"] = "Demonic Wards",
["item_type"] = "1",
["id"] = 1277736,
["spell_book_index"] = 139,
},
{
["tab"] = "Devourer",
["name"] = "Grim Focus",
["item_type"] = "1",
["id"] = 1260008,
["spell_book_index"] = 140,
},
{
["tab"] = "Devourer",
["name"] = "Mastery: Monster Within",
["item_type"] = "1",
["id"] = 1238855,
["spell_book_index"] = 141,
},
{
["tab"] = "Devourer",
["name"] = "Shattered Souls",
["item_type"] = "1",
["id"] = 1227619,
["spell_book_index"] = 142,
},
},
},
},
},
["schema_version"] = 5,
["addon_folder"] = "AzerothDataCollector_Spells",
["last_saved_at"] = 1778494570,
}
