
AzerothDataCollector_ContainersDB = {
["module_key"] = "containers",
["by_character"] = {
["Player-3674-0BB3F0D1"] = {
["containers"] = {
["updated_at"] = 1778448408,
["partial"] = false,
["records"] = {
{
["id"] = -2,
["name"] = "_container_scan_meta",
["bank_ui_opened_at_least_once"] = false,
},
{
["container_kind"] = "character_bag",
["id"] = 6948,
["bag_id"] = 0,
["name"] = "Hearthstone",
["slot"] = 1,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:6948::::::::15:253::75:::::::|h[Hearthstone]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 6889,
["bag_id"] = 0,
["name"] = "Small Egg",
["slot"] = 2,
["item_level"] = 10,
["item_link"] = "|cnIQ1:|Hitem:6889::::::::15:253:::::::::|h[Small Egg]|h|r",
["count"] = 3,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 805,
["bag_id"] = 0,
["name"] = "Small Red Pouch",
["slot"] = 3,
["item_level"] = 2,
["item_link"] = "|cnIQ1:|Hitem:805::::::::15:253:::::::::|h[Small Red Pouch]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 20837,
["bag_id"] = 0,
["name"] = "Sunstrider Axe",
["slot"] = 4,
["item_level"] = 5,
["item_link"] = "|cnIQ1:|Hitem:20837::::::::15:253::11:1:13617:2:9:5:28:1485:::::|h[Sunstrider Axe]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 187693,
["bag_id"] = 0,
["name"] = "Hunter's Belt",
["slot"] = 5,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:187693::::::::15:253::75:::::::|h[Hunter's Belt]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 128541,
["bag_id"] = 0,
["name"] = "Enchant Ring - Binding of Critical Strike",
["slot"] = 6,
["item_level"] = 16,
["item_link"] = "|cnIQ3:|Hitem:128541::::::::15:253:::::::::|h[Enchant Ring - Binding of Critical Strike]|h|r",
["count"] = 1,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 192626,
["bag_id"] = 0,
["name"] = "Mound of Dust",
["slot"] = 7,
["item_level"] = 21,
["item_link"] = "|cnIQ0:|Hitem:192626::::::::15:253:::::::::|h[Mound of Dust]|h|r",
["count"] = 2,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 83007,
["bag_id"] = 0,
["name"] = "Greater Tiger Claw Inscription",
["slot"] = 8,
["item_level"] = 15,
["item_link"] = "|cnIQ4:|Hitem:83007::::::::15:253:::::::::|h[Greater Tiger Claw Inscription]|h|r",
["count"] = 1,
["quality"] = 4,
},
{
["container_kind"] = "character_bag",
["id"] = 192644,
["bag_id"] = 0,
["name"] = "Aeriform Speck",
["slot"] = 9,
["item_level"] = 21,
["item_link"] = "|cnIQ0:|Hitem:192644::::::::15:253:::::::::|h[Aeriform Speck]|h|r",
["count"] = 1,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 192628,
["bag_id"] = 0,
["name"] = "Phoenix Ash",
["slot"] = 10,
["item_level"] = 21,
["item_link"] = "|cnIQ0:|Hitem:192628::::::::15:253:::::::::|h[Phoenix Ash]|h|r",
["count"] = 2,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 4663,
["bag_id"] = 0,
["name"] = "Journeyman's Belt",
["slot"] = 11,
["item_level"] = 4,
["item_link"] = "|cnIQ1:|Hitem:4663::::::::15:253::::1:28:77:::::|h[Journeyman's Belt]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 23334,
["bag_id"] = 0,
["name"] = "Cracked Power Core",
["slot"] = 12,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:23334::::::::15:253:::::::::|h[Cracked Power Core]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 131237,
["bag_id"] = 0,
["name"] = "Padded Chainmail",
["slot"] = 13,
["item_level"] = 7,
["item_link"] = "|cnIQ1:|Hitem:131237::::::::15:253::11:1:13617:2:9:7:28:77:::::|h[Padded Chainmail]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 23354,
["bag_id"] = 0,
["name"] = "Crystalized Mana Residue",
["slot"] = 14,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:23354::::::::15:253:::::::::|h[Crystalized Mana Residue]|h|r",
["count"] = 3,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 7096,
["bag_id"] = 0,
["name"] = "Plucked Feather",
["slot"] = 15,
["item_level"] = 1,
["item_link"] = "|cnIQ0:|Hitem:7096::::::::15:253:::::::::|h[Plucked Feather]|h|r",
["count"] = 1,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 23353,
["bag_id"] = 0,
["name"] = "Mana Residue",
["slot"] = 16,
["item_level"] = 1,
["item_link"] = "|cnIQ0:|Hitem:23353::::::::15:253:::::::::|h[Mana Residue]|h|r",
["count"] = 8,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 779,
["bag_id"] = 0,
["name"] = "Shiny Seashell",
["slot"] = 17,
["item_level"] = 1,
["item_link"] = "|cnIQ0:|Hitem:779::::::::15:253:::::::::|h[Shiny Seashell]|h|r",
["count"] = 6,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 6510,
["bag_id"] = 0,
["name"] = "Infantry Gauntlets",
["slot"] = 18,
["item_level"] = 5,
["item_link"] = "|cnIQ1:|Hitem:6510::::::::15:253::::1:28:77:::::|h[Infantry Gauntlets]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 2589,
["bag_id"] = 0,
["name"] = "Linen Cloth",
["slot"] = 19,
["item_level"] = 10,
["item_link"] = "|cnIQ1:|Hitem:2589::::::::15:253:::::::::|h[Linen Cloth]|h|r",
["count"] = 9,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 23370,
["bag_id"] = 0,
["name"] = "Ley-Keeper's Blade",
["slot"] = 20,
["item_level"] = 7,
["item_link"] = "|cnIQ1:|Hitem:23370::::::::15:253::11:1:13617:2:9:7:28:77:::::|h[Ley-Keeper's Blade]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 2643,
["bag_id"] = 1,
["name"] = "Loose Chain Bracers",
["slot"] = 1,
["item_level"] = 1,
["item_link"] = "|cnIQ0:|Hitem:2643::::::::15:253:::1:6656:2:9:9:28:77:::::|h[Loose Chain Bracers]|h|r",
["count"] = 1,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 774,
["bag_id"] = 1,
["name"] = "Malachite",
["slot"] = 2,
["item_level"] = 10,
["item_link"] = "|cnIQ2:|Hitem:774::::::::15:253:::::::::|h[Malachite]|h|r",
["count"] = 2,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 23398,
["bag_id"] = 1,
["name"] = "Worn Ranger's Bow",
["slot"] = 3,
["item_level"] = 9,
["item_link"] = "|cnIQ1:|Hitem:23398::::::::15:253::11:1:13617:2:9:9:28:77:::::|h[Worn Ranger's Bow]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 1429,
["bag_id"] = 1,
["name"] = "Patchwork Cloak",
["slot"] = 4,
["item_level"] = 1,
["item_link"] = "|cnIQ0:|Hitem:1429::::::::15:253:::1:6656:2:9:9:28:77:::::|h[Patchwork Cloak]|h|r",
["count"] = 1,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 22957,
["bag_id"] = 1,
["name"] = "Rusty Sin'dorei Sword",
["slot"] = 5,
["item_level"] = 9,
["item_link"] = "|cnIQ1:|Hitem:22957::::::::15:253::11:1:13617:2:9:9:28:77:::::|h[Rusty Sin'dorei Sword]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 1431,
["bag_id"] = 1,
["name"] = "Patchwork Pants",
["slot"] = 6,
["item_level"] = 1,
["item_link"] = "|cnIQ0:|Hitem:1431::::::::15:253:::1:6656:2:9:10:28:77:::::|h[Patchwork Pants]|h|r",
["count"] = 1,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 131240,
["bag_id"] = 1,
["name"] = "Longshoreman's Bracers",
["slot"] = 7,
["item_level"] = 10,
["item_link"] = "|cnIQ1:|Hitem:131240::::::::15:253::11:1:13617:2:9:10:28:77:::::|h[Longshoreman's Bracers]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 23373,
["bag_id"] = 1,
["name"] = "Long Knife",
["slot"] = 8,
["item_level"] = 10,
["item_link"] = "|cnIQ1:|Hitem:23373::::::::15:253::11:1:13617:2:9:10:28:77:::::|h[Long Knife]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 180055,
["bag_id"] = 1,
["name"] = "Relic of the Past I",
["slot"] = 9,
["item_level"] = 17,
["item_link"] = "|cnIQ1:|Hitem:180055::::::::15:253:::::::::|h[Relic of the Past I]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 192631,
["bag_id"] = 1,
["name"] = "Scale-Piercing Fang",
["slot"] = 10,
["item_level"] = 21,
["item_link"] = "|cnIQ0:|Hitem:192631::::::::15:253:::::::::|h[Scale-Piercing Fang]|h|r",
["count"] = 26,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 192624,
["bag_id"] = 1,
["name"] = "Cracked Scales",
["slot"] = 11,
["item_level"] = 21,
["item_link"] = "|cnIQ0:|Hitem:192624::::::::15:253:::::::::|h[Cracked Scales]|h|r",
["count"] = 4,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 200285,
["bag_id"] = 1,
["name"] = "Dragonscale Expedition Insignia",
["slot"] = 12,
["item_level"] = 17,
["item_link"] = "|cnIQ2:|Hitem:200285::::::::15:253:::::::::|h[Dragonscale Expedition Insignia]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 197744,
["bag_id"] = 1,
["name"] = "Hornswog Hunk",
["slot"] = 13,
["item_level"] = 19,
["item_link"] = "|cnIQ1:|Hitem:197744::::::::15:253:::::::::|h[Hornswog Hunk]|h|r",
["count"] = 2,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 200093,
["bag_id"] = 1,
["name"] = "Centaur Hunting Trophy",
["slot"] = 14,
["item_level"] = 1,
["item_link"] = "|cnIQ2:|Hitem:200093::::::::15:253:::::::::|h[Centaur Hunting Trophy]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 200165,
["bag_id"] = 1,
["name"] = "Aegis of Scales",
["slot"] = 15,
["item_level"] = 11,
["item_link"] = "|cnIQ3:|Hitem:200165::::::::15:253::17:2:13642:6652:2:9:11:28:2437:::::|h[Aegis of Scales]|h|r",
["count"] = 1,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 192672,
["bag_id"] = 1,
["name"] = "Tattered Proto-Wing",
["slot"] = 16,
["item_level"] = 21,
["item_link"] = "|cnIQ0:|Hitem:192672::::::::15:253:::::::::|h[Tattered Proto-Wing]|h|r",
["count"] = 1,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 192614,
["bag_id"] = 1,
["name"] = "Elemental Ooze",
["slot"] = 17,
["item_level"] = 21,
["item_link"] = "|cnIQ0:|Hitem:192614::::::::15:253:::::::::|h[Elemental Ooze]|h|r",
["count"] = 11,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 188213,
["bag_id"] = 1,
["name"] = "Large Green Bag",
["slot"] = 18,
["item_level"] = 12,
["item_link"] = "|cnIQ1:|Hitem:188213::::::::15:253:::::::::|h[Large Green Bag]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 192635,
["bag_id"] = 1,
["name"] = "Warped Metal",
["slot"] = 19,
["item_level"] = 21,
["item_link"] = "|cnIQ0:|Hitem:192635::::::::15:253:::::::::|h[Warped Metal]|h|r",
["count"] = 10,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 190320,
["bag_id"] = 1,
["name"] = "Rousing Fire",
["slot"] = 20,
["item_level"] = 19,
["item_link"] = "|cnIQ3:|Hitem:190320::::::::15:253:::::::::|h[Rousing Fire]|h|r",
["count"] = 2,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 201470,
["bag_id"] = 1,
["name"] = "Story of a Memorable Victory",
["slot"] = 21,
["item_level"] = 1,
["item_link"] = "|cnIQ2:|Hitem:201470::::::::15:253:::::::::|h[Story of a Memorable Victory]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 192625,
["bag_id"] = 1,
["name"] = "Motionless Stone",
["slot"] = 22,
["item_level"] = 21,
["item_link"] = "|cnIQ0:|Hitem:192625::::::::15:253:::::::::|h[Motionless Stone]|h|r",
["count"] = 6,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 192662,
["bag_id"] = 1,
["name"] = "Pyretic Speck",
["slot"] = 23,
["item_level"] = 21,
["item_link"] = "|cnIQ0:|Hitem:192662::::::::15:253:::::::::|h[Pyretic Speck]|h|r",
["count"] = 2,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 193050,
["bag_id"] = 1,
["name"] = "Tattered Wildercloth",
["slot"] = 24,
["item_level"] = 19,
["item_link"] = "|cnIQ1:|Hitem:193050::::::::15:253:::::::::|h[Tattered Wildercloth]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 194402,
["bag_id"] = 1,
["name"] = "Expedition Mercenary's Hauberk",
["slot"] = 25,
["item_level"] = 13,
["item_link"] = "|cnIQ2:|Hitem:194402::::::::15:253::26:1:13642:2:9:13:28:2523:::::|h[Expedition Mercenary's Hauberk]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 190315,
["bag_id"] = 1,
["name"] = "Rousing Earth",
["slot"] = 26,
["item_level"] = 19,
["item_link"] = "|cnIQ3:|Hitem:190315::::::::15:253:::::::::|h[Rousing Earth]|h|r",
["count"] = 3,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 197741,
["bag_id"] = 1,
["name"] = "Maybe Meat",
["slot"] = 27,
["item_level"] = 19,
["item_link"] = "|cnIQ1:|Hitem:197741::::::::15:253:::::::::|h[Maybe Meat]|h|r",
["count"] = 3,
["quality"] = 1,
},
},
},
},
["Player-3674-09C5872B"] = {
["containers"] = {
["updated_at"] = 1778449756,
["records"] = {
{
["id"] = -2,
["name"] = "_container_scan_meta",
["bank_ui_opened_at_least_once"] = false,
},
{
["container_kind"] = "character_bag",
["id"] = 6948,
["bag_id"] = 0,
["name"] = "Hearthstone",
["slot"] = 1,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:6948::::::::88:577:::::::::|h[Hearthstone]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 265820,
["bag_id"] = 0,
["name"] = "Ruia's Musings, Part 3",
["slot"] = 2,
["item_level"] = 80,
["item_link"] = "|cnIQ1:|Hitem:265820::::::::88:577:::::::::|h[Ruia's Musings, Part 3]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 265819,
["bag_id"] = 0,
["name"] = "Ruia's Musings, Part 2",
["slot"] = 3,
["item_level"] = 80,
["item_link"] = "|cnIQ1:|Hitem:265819::::::::88:577:::::::::|h[Ruia's Musings, Part 2]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 265818,
["bag_id"] = 0,
["name"] = "Ruia's Musings, Part 1",
["slot"] = 4,
["item_level"] = 80,
["item_link"] = "|cnIQ1:|Hitem:265818::::::::88:577:::::::::|h[Ruia's Musings, Part 1]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 163604,
["bag_id"] = 0,
["name"] = "Net-o-Matic 5000",
["slot"] = 5,
["item_level"] = 15,
["item_link"] = "|cnIQ2:|Hitem:163604::::::::88:577::11:::::::|h[Net-o-Matic 5000]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 267051,
["bag_id"] = 0,
["name"] = "Dark Particle",
["slot"] = 6,
["item_level"] = 1,
["item_link"] = "|cnIQ2:|Hitem:267051::::::::88:577:::::::::|h[Dark Particle]|h|r",
["count"] = 89,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 253580,
["bag_id"] = 0,
["name"] = "Harvesting Hatchet",
["slot"] = 7,
["item_level"] = 1,
["item_link"] = "|cnIQ3:|Hitem:253580::::::::88:577::14::1:28:4285:::::|h[Harvesting Hatchet]|h|r",
["count"] = 1,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 259126,
["bag_id"] = 0,
["name"] = "Void Violet Dye",
["slot"] = 9,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:259126::::::::88:577:::::::::|h[Void Violet Dye]|h|r",
["count"] = 3,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 259115,
["bag_id"] = 0,
["name"] = "Alliance Blue Dye",
["slot"] = 10,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:259115::::::::88:577:::::::::|h[Alliance Blue Dye]|h|r",
["count"] = 3,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 259114,
["bag_id"] = 0,
["name"] = "Lush Green Dye",
["slot"] = 11,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:259114::::::::88:577:::::::::|h[Lush Green Dye]|h|r",
["count"] = 4,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 259113,
["bag_id"] = 0,
["name"] = "Horde Red Dye",
["slot"] = 12,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:259113::::::::88:577:::::::::|h[Horde Red Dye]|h|r",
["count"] = 3,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 238474,
["bag_id"] = 0,
["name"] = "Peculiar Lotus",
["slot"] = 15,
["item_level"] = 1,
["item_link"] = "|cnIQ4:|Hitem:238474::::::::88:577::::1:28:3615:::::|h[Peculiar Lotus]|h|r",
["count"] = 1,
["quality"] = 4,
},
{
["container_kind"] = "character_bag",
["id"] = 238500,
["bag_id"] = 0,
["name"] = "Maella's Report",
["slot"] = 20,
["item_level"] = 21,
["item_link"] = "|cnIQ1:|Hitem:238500::::::::88:577:::::::::|h[Maella's Report]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 257755,
["bag_id"] = 1,
["name"] = "Holy Bounding Hand Grenade",
["slot"] = 1,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:257755::::::::88:577::25:1:13589:1:28:6070:::::|h[Holy Bounding Hand Grenade]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 86143,
["bag_id"] = 1,
["name"] = "Battle Pet Bandage",
["slot"] = 2,
["item_level"] = 10,
["item_link"] = "|cnIQ2:|Hitem:86143::::::::88:577:::::::::|h[Battle Pet Bandage]|h|r",
["count"] = 4,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 200886,
["bag_id"] = 1,
["name"] = "Lemon Silverleaf Tea",
["slot"] = 3,
["item_level"] = 21,
["item_link"] = "|cnIQ1:|Hitem:200886::::::::88:577:::::::::|h[Lemon Silverleaf Tea]|h|r",
["count"] = 6,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 258138,
["bag_id"] = 1,
["name"] = "Potent Healing Potion",
["slot"] = 5,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:258138::::::::88:577:::::::::|h[Potent Healing Potion]|h|r",
["count"] = 34,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 1205,
["bag_id"] = 1,
["name"] = "Melon Juice",
["slot"] = 6,
["item_level"] = 7,
["item_link"] = "|cnIQ1:|Hitem:1205::::::::88:577:::::::::|h[Melon Juice]|h|r",
["count"] = 2,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 1708,
["bag_id"] = 1,
["name"] = "Sweet Nectar",
["slot"] = 7,
["item_level"] = 10,
["item_link"] = "|cnIQ1:|Hitem:1708::::::::88:577:::::::::|h[Sweet Nectar]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 4599,
["bag_id"] = 1,
["name"] = "Cured Ham Steak",
["slot"] = 8,
["item_level"] = 11,
["item_link"] = "|cnIQ1:|Hitem:4599::::::::88:577:::::::::|h[Cured Ham Steak]|h|r",
["count"] = 2,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 1645,
["bag_id"] = 1,
["name"] = "Moonberry Juice",
["slot"] = 9,
["item_level"] = 11,
["item_link"] = "|cnIQ1:|Hitem:1645::::::::88:577:::::::::|h[Moonberry Juice]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 8952,
["bag_id"] = 1,
["name"] = "Roasted Quail",
["slot"] = 10,
["item_level"] = 12,
["item_link"] = "|cnIQ1:|Hitem:8952::::::::88:577:::::::::|h[Roasted Quail]|h|r",
["count"] = 3,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 2455,
["bag_id"] = 1,
["name"] = "Minor Mana Potion",
["slot"] = 11,
["item_level"] = 7,
["item_link"] = "|cnIQ1:|Hitem:2455::::::::88:577:::::::::|h[Minor Mana Potion]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 117,
["bag_id"] = 1,
["name"] = "Tough Jerky",
["slot"] = 12,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:117::::::::88:577:::::::::|h[Tough Jerky]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 13446,
["bag_id"] = 1,
["name"] = "Major Healing Potion",
["slot"] = 13,
["item_level"] = 12,
["item_link"] = "|cnIQ1:|Hitem:13446::::::::88:577:::::::::|h[Major Healing Potion]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 262786,
["bag_id"] = 1,
["name"] = "Suntouched Special Reserve",
["slot"] = 14,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:262786::::::::88:577:::::::::|h[Suntouched Special Reserve]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 112384,
["bag_id"] = 1,
["name"] = "Reflecting Prism",
["slot"] = 15,
["item_level"] = 1,
["item_link"] = "|cnIQ2:|Hitem:112384::::::::88:577::::1:28:5914:::::|h[Reflecting Prism]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 112384,
["bag_id"] = 1,
["name"] = "Reflecting Prism",
["slot"] = 16,
["item_level"] = 1,
["item_link"] = "|cnIQ2:|Hitem:112384::::::::88:577::::1:28:5914:::::|h[Reflecting Prism]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 238987,
["bag_id"] = 1,
["name"] = "Saltheril's Favor",
["slot"] = 21,
["item_level"] = 1,
["item_link"] = "|cnIQ3:|Hitem:238987::::::::88:577:::::::::|h[Saltheril's Favor]|h|r",
["count"] = 1,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 270934,
["bag_id"] = 1,
["name"] = "Recruit's Field Pouch",
["slot"] = 22,
["item_level"] = 1,
["item_link"] = "|cnIQ3:|Hitem:270934::::::::88:577::11::2:9:87:28:3322:::::|h[Recruit's Field Pouch]|h|r",
["count"] = 1,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 272125,
["bag_id"] = 1,
["name"] = "Recruit's Cache",
["slot"] = 23,
["item_level"] = 1,
["item_link"] = "|cnIQ3:|Hitem:272125::::::::88:577::11::2:9:87:28:3321:::::|h[Recruit's Cache]|h|r",
["count"] = 1,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 260664,
["bag_id"] = 2,
["name"] = "Bioluminescent Flower Petals",
["slot"] = 1,
["item_level"] = 24,
["item_link"] = "|cnIQ0:|Hitem:260664::::::::88:577:::::::::|h[Bioluminescent Flower Petals]|h|r",
["count"] = 4,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 260644,
["bag_id"] = 2,
["name"] = "Lightbloom Bark",
["slot"] = 2,
["item_level"] = 24,
["item_link"] = "|cnIQ0:|Hitem:260644::::::::88:577:::::::::|h[Lightbloom Bark]|h|r",
["count"] = 1,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 260656,
["bag_id"] = 2,
["name"] = "Perforated Wing",
["slot"] = 3,
["item_level"] = 24,
["item_link"] = "|cnIQ0:|Hitem:260656::::::::88:577:::::::::|h[Perforated Wing]|h|r",
["count"] = 1,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 260618,
["bag_id"] = 2,
["name"] = "Light-Infused Leaves",
["slot"] = 4,
["item_level"] = 24,
["item_link"] = "|cnIQ0:|Hitem:260618::::::::88:577:::::::::|h[Light-Infused Leaves]|h|r",
["count"] = 1,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 260662,
["bag_id"] = 2,
["name"] = "Polished Purple Pebble",
["slot"] = 5,
["item_level"] = 24,
["item_link"] = "|cnIQ0:|Hitem:260662::::::::88:577:::::::::|h[Polished Purple Pebble]|h|r",
["count"] = 1,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 260604,
["bag_id"] = 2,
["name"] = "Insect Shedding",
["slot"] = 6,
["item_level"] = 24,
["item_link"] = "|cnIQ0:|Hitem:260604::::::::88:577:::::::::|h[Insect Shedding]|h|r",
["count"] = 1,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 260646,
["bag_id"] = 2,
["name"] = "Glowing Gland",
["slot"] = 7,
["item_level"] = 24,
["item_link"] = "|cnIQ0:|Hitem:260646::::::::88:577:::::::::|h[Glowing Gland]|h|r",
["count"] = 2,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 260613,
["bag_id"] = 2,
["name"] = "Lightbloom Flower",
["slot"] = 8,
["item_level"] = 24,
["item_link"] = "|cnIQ0:|Hitem:260613::::::::88:577:::::::::|h[Lightbloom Flower]|h|r",
["count"] = 1,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 260309,
["bag_id"] = 2,
["name"] = "Thrumming Plant Matter",
["slot"] = 9,
["item_level"] = 24,
["item_link"] = "|cnIQ0:|Hitem:260309::::::::88:577:::::::::|h[Thrumming Plant Matter]|h|r",
["count"] = 2,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 260673,
["bag_id"] = 2,
["name"] = "Partially Digested Bracers",
["slot"] = 10,
["item_level"] = 24,
["item_link"] = "|cnIQ0:|Hitem:260673::::::::88:577:::::::::|h[Partially Digested Bracers]|h|r",
["count"] = 1,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 38682,
["bag_id"] = 3,
["name"] = "Enchanting Vellum",
["slot"] = 1,
["item_level"] = 44,
["item_link"] = "|cnIQ1:|Hitem:38682::::::::88:577:::::::::|h[Enchanting Vellum]|h|r",
["count"] = 44,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 227208,
["bag_id"] = 3,
["name"] = "Bismuth Rod",
["slot"] = 2,
["item_level"] = 77,
["item_link"] = "|cnIQ1:|Hitem:227208::::::::88:577::14::1:28:2797:::::|h[Bismuth Rod]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 265803,
["bag_id"] = 5,
["name"] = "Bazaar Bites",
["slot"] = 1,
["item_level"] = 78,
["item_link"] = "|cnIQ3:|Hitem:265803::::::::88:577:::::::::|h[Bazaar Bites]|h|r",
["count"] = 3,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 265800,
["bag_id"] = 5,
["name"] = "Earthy Garnish",
["slot"] = 2,
["item_level"] = 78,
["item_link"] = "|cnIQ2:|Hitem:265800::::::::88:577:::::::::|h[Earthy Garnish]|h|r",
["count"] = 2,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 245850,
["bag_id"] = 5,
["name"] = "Four of Rot",
["slot"] = 3,
["item_level"] = 24,
["item_link"] = "|cnIQ3:|Hitem:245850::::::::88:577:::::::::|h[Four of Rot]|h|r",
["count"] = 1,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 236949,
["bag_id"] = 5,
["name"] = "Mote of Light",
["slot"] = 4,
["item_level"] = 23,
["item_link"] = "|cnIQ3:|Hitem:236949::::::::88:577:::::::::|h[Mote of Light]|h|r",
["count"] = 1,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 256963,
["bag_id"] = 5,
["name"] = "Thalassian Lumber",
["slot"] = 5,
["item_level"] = 10,
["item_link"] = "|cnIQ2:|Hitem:256963::::::::88:577:::::::::|h[Thalassian Lumber]|h|r",
["count"] = 2,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 236776,
["bag_id"] = 5,
["name"] = "Argentleaf",
["slot"] = 6,
["item_level"] = 23,
["item_link"] = "|cnIQ2:|Hitem:236776::::::::88:577::::1:38:13:::::|h[Argentleaf |A:Professions-ChatIcon-Quality-12-Tier1:17:15::1|a]|h|r",
["count"] = 2,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 236770,
["bag_id"] = 5,
["name"] = "Sanguithorn",
["slot"] = 7,
["item_level"] = 23,
["item_link"] = "|cnIQ2:|Hitem:236770::::::::88:577::::1:38:13:::::|h[Sanguithorn |A:Professions-ChatIcon-Quality-12-Tier1:17:15::1|a]|h|r",
["count"] = 5,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 236761,
["bag_id"] = 5,
["name"] = "Tranquility Bloom",
["slot"] = 8,
["item_level"] = 23,
["item_link"] = "|cnIQ1:|Hitem:236761::::::::88:577::::1:38:13:::::|h[Tranquility Bloom |A:Professions-ChatIcon-Quality-12-Tier1:17:15::1|a]|h|r",
["count"] = 2,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 242640,
["bag_id"] = 5,
["name"] = "Plant Protein",
["slot"] = 9,
["item_level"] = 23,
["item_link"] = "|cnIQ1:|Hitem:242640::::::::88:577:::::::::|h[Plant Protein]|h|r",
["count"] = 138,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 242639,
["bag_id"] = 5,
["name"] = "Practically Pork",
["slot"] = 10,
["item_level"] = 23,
["item_link"] = "|cnIQ1:|Hitem:242639::::::::88:577:::::::::|h[Practically Pork]|h|r",
["count"] = 132,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 251923,
["bag_id"] = 5,
["name"] = "Thalassian Essence of the Faire",
["slot"] = 11,
["item_level"] = 24,
["item_link"] = "|cnIQ2:|Hitem:251923::::::::88:577:::::::::|h[Thalassian Essence of the Faire]|h|r",
["count"] = 2,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 2592,
["bag_id"] = 5,
["name"] = "Wool Cloth",
["slot"] = 12,
["item_level"] = 10,
["item_link"] = "|cnIQ1:|Hitem:2592::::::::88:577:::::::::|h[Wool Cloth]|h|r",
["count"] = 5,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 14047,
["bag_id"] = 5,
["name"] = "Runecloth",
["slot"] = 13,
["item_level"] = 10,
["item_link"] = "|cnIQ1:|Hitem:14047::::::::88:577:::::::::|h[Runecloth]|h|r",
["count"] = 3,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 4338,
["bag_id"] = 5,
["name"] = "Mageweave Cloth",
["slot"] = 14,
["item_level"] = 10,
["item_link"] = "|cnIQ1:|Hitem:4338::::::::88:577:::::::::|h[Mageweave Cloth]|h|r",
["count"] = 3,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 1179,
["bag_id"] = 5,
["name"] = "Ice Cold Milk",
["slot"] = 15,
["item_level"] = 3,
["item_link"] = "|cnIQ1:|Hitem:1179::::::::88:577:::::::::|h[Ice Cold Milk]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 40195,
["bag_id"] = 5,
["name"] = "Pygmy Oil",
["slot"] = 16,
["item_level"] = 12,
["item_link"] = "|cnIQ1:|Hitem:40195::::::::88:577:::::::::|h[Pygmy Oil]|h|r",
["count"] = 2,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 265801,
["bag_id"] = 5,
["name"] = "Savory Anomaly",
["slot"] = 17,
["item_level"] = 78,
["item_link"] = "|cnIQ2:|Hitem:265801::::::::88:577:::::::::|h[Savory Anomaly]|h|r",
["count"] = 1,
["quality"] = 2,
},
},
["partial"] = false,
},
},
},
["schema_version"] = 4,
["addon_folder"] = "AzerothDataCollector_Containers",
["last_saved_at"] = 1778449756,
}
