
AzerothDataCollector_CurrenciesDB = {
["module_key"] = "currencies",
["by_character"] = {
["Player-3674-09D241D0"] = {
["currencies"] = {
["updated_at"] = 1778494570,
["records"] = {
{
["max_weekly_quantity"] = 0,
["quantity"] = 4,
["name"] = "Dawnlight Manaflux",
["max_quantity"] = 8,
["id"] = 3378,
["quantity_earned_this_week"] = 0,
["category_header"] = "Season 1",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Restored Coffer Key",
["max_quantity"] = 0,
["id"] = 3028,
["quantity_earned_this_week"] = 0,
["category_header"] = "Season 1",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Undercoin",
["max_quantity"] = 0,
["id"] = 2803,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Season 1",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 2310,
["name"] = "Timewarped Badge",
["max_quantity"] = 0,
["id"] = 1166,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Dungeon and Raid",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Bronze Celebration Token",
["max_quantity"] = 0,
["id"] = 3100,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Miscellaneous",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 4,
["name"] = "Darkmoon Prize Ticket",
["max_quantity"] = 0,
["id"] = 515,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Miscellaneous",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 3015,
["name"] = "Trader's Tender",
["max_quantity"] = 0,
["id"] = 2032,
["quantity_earned_this_week"] = 0,
["category_header"] = "Miscellaneous",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Conquest",
["max_quantity"] = 7200,
["id"] = 1602,
["quantity_earned_this_week"] = 0,
["category_header"] = "Player vs. Player",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Honor",
["max_quantity"] = 15000,
["id"] = 1792,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Player vs. Player",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 11943,
["name"] = "Kej",
["max_quantity"] = 0,
["id"] = 3056,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "War Within",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 12,
["name"] = "Nerub-ar Finery",
["max_quantity"] = 128,
["id"] = 3093,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "War Within",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 5000,
["name"] = "Residual Memories",
["max_quantity"] = 0,
["id"] = 3089,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "War Within",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 2357,
["name"] = "Resonance Crystals",
["max_quantity"] = 0,
["id"] = 2815,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "War Within",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Aspect's Awakened Crest",
["max_quantity"] = 0,
["id"] = 2812,
["quantity_earned_this_week"] = 0,
["category_header"] = "Dragonflight",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 5220,
["name"] = "Dragon Isles Supplies",
["max_quantity"] = 0,
["id"] = 2003,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Dragonflight",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Drake's Awakened Crest",
["max_quantity"] = 0,
["id"] = 2807,
["quantity_earned_this_week"] = 0,
["category_header"] = "Dragonflight",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 6,
["name"] = "Emerald Dewdrop",
["max_quantity"] = 0,
["id"] = 2650,
["quantity_earned_this_week"] = 0,
["category_header"] = "Dragonflight",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Flightstones",
["max_quantity"] = 2000,
["id"] = 2245,
["quantity_earned_this_week"] = 0,
["category_header"] = "Dragonflight",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 3644,
["name"] = "Paracausal Flakes",
["max_quantity"] = 0,
["id"] = 2594,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Dragonflight",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Whelpling's Awakened Crest",
["max_quantity"] = 0,
["id"] = 2806,
["quantity_earned_this_week"] = 0,
["category_header"] = "Dragonflight",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Wyrm's Awakened Crest",
["max_quantity"] = 0,
["id"] = 2809,
["quantity_earned_this_week"] = 0,
["category_header"] = "Dragonflight",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 2348,
["name"] = "Cataloged Research",
["max_quantity"] = 0,
["id"] = 1931,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 1355,
["name"] = "Cosmic Flux",
["max_quantity"] = 0,
["id"] = 2009,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 309,
["name"] = "Cyphers of the First Ones",
["max_quantity"] = 0,
["id"] = 1979,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 30,
["name"] = "Grateful Offering",
["max_quantity"] = 0,
["id"] = 1885,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 39,
["name"] = "Infused Ruby",
["max_quantity"] = 100,
["id"] = 1820,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 10703,
["name"] = "Reservoir Anima",
["max_quantity"] = 200000,
["id"] = 1813,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 1825,
["name"] = "Soul Ash",
["max_quantity"] = 0,
["id"] = 1828,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 50,
["name"] = "Soul Cinders",
["max_quantity"] = 0,
["id"] = 1906,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 371,
["name"] = "Stygia",
["max_quantity"] = 0,
["id"] = 1767,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 133,
["name"] = "Stygian Ember",
["max_quantity"] = 0,
["id"] = 1977,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 28,
["name"] = "Tower Knowledge",
["max_quantity"] = 3510,
["id"] = 1904,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 28689,
["name"] = "Coalescing Visions",
["max_quantity"] = 0,
["id"] = 1755,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Battle for Azeroth",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 5178,
["name"] = "Corrupted Mementos",
["max_quantity"] = 0,
["id"] = 1719,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Battle for Azeroth",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 1818,
["name"] = "Echoes of Ny'alotha",
["max_quantity"] = 0,
["id"] = 1803,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Battle for Azeroth",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 70,
["name"] = "Honorbound Service Medal",
["max_quantity"] = 0,
["id"] = 1716,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Battle for Azeroth",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 131,
["name"] = "Seafarer's Dubloon",
["max_quantity"] = 0,
["id"] = 1710,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Battle for Azeroth",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Seal of Wartorn Fate",
["max_quantity"] = 5,
["id"] = 1580,
["quantity_earned_this_week"] = 0,
["category_header"] = "Battle for Azeroth",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Titan Residuum",
["max_quantity"] = 0,
["id"] = 1718,
["quantity_earned_this_week"] = 0,
["category_header"] = "Battle for Azeroth",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 24,
["name"] = "War Resources",
["max_quantity"] = 0,
["id"] = 1560,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Battle for Azeroth",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 2,
["name"] = "Ancient Mana",
["max_quantity"] = 300,
["id"] = 1155,
["quantity_earned_this_week"] = 0,
["category_header"] = "Legion",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 3,
["name"] = "Curious Coin",
["max_quantity"] = 0,
["id"] = 1275,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Legion",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 395,
["name"] = "Order Resources",
["max_quantity"] = 0,
["id"] = 1220,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Legion",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 40,
["name"] = "Sightless Eye",
["max_quantity"] = 5000,
["id"] = 1149,
["quantity_earned_this_week"] = 0,
["category_header"] = "Legion",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 166,
["name"] = "Wakening Essence",
["max_quantity"] = 0,
["id"] = 1533,
["quantity_earned_this_week"] = 0,
["category_header"] = "Legion",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Artifact Fragment",
["max_quantity"] = 1000,
["id"] = 944,
["quantity_earned_this_week"] = 0,
["category_header"] = "Warlords of Draenor",
},
},
["partial"] = false,
},
},
["Player-3674-09C5872B"] = {
["currencies"] = {
["updated_at"] = 1778494534,
["partial"] = false,
["records"] = {
{
["category_header"] = "Midnight",
["max_weekly_quantity"] = 0,
["name"] = "Angler Pearls",
["max_quantity"] = 0,
["id"] = 3373,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 31,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Artisan Herbalist's Moxie",
["max_quantity"] = 0,
["id"] = 3260,
["category_header"] = "Midnight",
["quantity_earned_this_week"] = 0,
["quantity"] = 85,
},
{
["category_header"] = "Midnight",
["max_weekly_quantity"] = 0,
["name"] = "Luminous Dust",
["max_quantity"] = 0,
["id"] = 3385,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 2,
},
{
["max_weekly_quantity"] = 8,
["name"] = "Shard of Dundun",
["max_quantity"] = 8,
["id"] = 3376,
["category_header"] = "Midnight",
["quantity_earned_this_week"] = 5,
["quantity"] = 5,
},
{
["category_header"] = "Midnight",
["max_weekly_quantity"] = 0,
["name"] = "Voidlight Marl",
["max_quantity"] = 0,
["id"] = 3316,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 1102,
},
{
["max_weekly_quantity"] = 600,
["name"] = "Coffer Key Shards",
["max_quantity"] = 0,
["id"] = 3310,
["category_header"] = "Season 1",
["quantity_earned_this_week"] = 153,
["quantity"] = 153,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Dawnlight Manaflux",
["max_quantity"] = 8,
["id"] = 3378,
["category_header"] = "Season 1",
["quantity_earned_this_week"] = 0,
["quantity"] = 4,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Restored Coffer Key",
["max_quantity"] = 0,
["id"] = 3028,
["category_header"] = "Season 1",
["quantity_earned_this_week"] = 0,
["quantity"] = 1,
},
{
["category_header"] = "Season 1",
["max_weekly_quantity"] = 0,
["name"] = "Undercoin",
["max_quantity"] = 0,
["id"] = 2803,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 3000,
},
{
["category_header"] = "Dungeon and Raid",
["max_weekly_quantity"] = 0,
["name"] = "Timewarped Badge",
["max_quantity"] = 0,
["id"] = 1166,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 1175,
},
{
["category_header"] = "Miscellaneous",
["max_weekly_quantity"] = 0,
["name"] = "Community Coupons",
["max_quantity"] = 2000,
["id"] = 3363,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 78,
},
{
["category_header"] = "Miscellaneous",
["max_weekly_quantity"] = 0,
["name"] = "Darkmoon Prize Ticket",
["max_quantity"] = 0,
["id"] = 515,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 5,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Trader's Tender",
["max_quantity"] = 0,
["id"] = 2032,
["category_header"] = "Miscellaneous",
["quantity_earned_this_week"] = 0,
["quantity"] = 3015,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Bloody Tokens",
["max_quantity"] = 7200,
["id"] = 2123,
["category_header"] = "Player vs. Player",
["quantity_earned_this_week"] = 0,
["quantity"] = 0,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Conquest",
["max_quantity"] = 7200,
["id"] = 1602,
["category_header"] = "Player vs. Player",
["quantity_earned_this_week"] = 0,
["quantity"] = 0,
},
{
["category_header"] = "Player vs. Player",
["max_weekly_quantity"] = 0,
["name"] = "Honor",
["max_quantity"] = 15000,
["id"] = 1792,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 0,
},
{
["category_header"] = "War Within",
["max_weekly_quantity"] = 0,
["name"] = "Kej",
["max_quantity"] = 0,
["id"] = 3056,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 3115,
},
{
["category_header"] = "War Within",
["max_weekly_quantity"] = 0,
["name"] = "Nerub-ar Finery",
["max_quantity"] = 128,
["id"] = 3093,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 1,
},
{
["category_header"] = "War Within",
["max_weekly_quantity"] = 0,
["name"] = "Resonance Crystals",
["max_quantity"] = 0,
["id"] = 2815,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 1400,
},
{
["category_header"] = "Dragonflight",
["max_weekly_quantity"] = 0,
["name"] = "Dragon Isles Supplies",
["max_quantity"] = 0,
["id"] = 2003,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 18703,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Drake's Awakened Crest",
["max_quantity"] = 0,
["id"] = 2807,
["category_header"] = "Dragonflight",
["quantity_earned_this_week"] = 0,
["quantity"] = 0,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Dream Infusion",
["max_quantity"] = 0,
["id"] = 2777,
["category_header"] = "Dragonflight",
["quantity_earned_this_week"] = 0,
["quantity"] = 5,
},
{
["category_header"] = "Dragonflight",
["max_weekly_quantity"] = 0,
["name"] = "Elemental Overflow",
["max_quantity"] = 0,
["id"] = 2118,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 4803,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Emerald Dewdrop",
["max_quantity"] = 0,
["id"] = 2650,
["category_header"] = "Dragonflight",
["quantity_earned_this_week"] = 0,
["quantity"] = 276,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Flightstones",
["max_quantity"] = 2000,
["id"] = 2245,
["category_header"] = "Dragonflight",
["quantity_earned_this_week"] = 0,
["quantity"] = 0,
},
{
["category_header"] = "Dragonflight",
["max_weekly_quantity"] = 0,
["name"] = "Mysterious Fragment",
["max_quantity"] = 0,
["id"] = 2657,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 6174,
},
{
["category_header"] = "Dragonflight",
["max_weekly_quantity"] = 0,
["name"] = "Paracausal Flakes",
["max_quantity"] = 0,
["id"] = 2594,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 3236,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Storm Sigil",
["max_quantity"] = 0,
["id"] = 2122,
["category_header"] = "Dragonflight",
["quantity_earned_this_week"] = 0,
["quantity"] = 16,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Whelpling's Awakened Crest",
["max_quantity"] = 0,
["id"] = 2806,
["category_header"] = "Dragonflight",
["quantity_earned_this_week"] = 0,
["quantity"] = 0,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Wyrm's Awakened Crest",
["max_quantity"] = 0,
["id"] = 2809,
["category_header"] = "Dragonflight",
["quantity_earned_this_week"] = 0,
["quantity"] = 0,
},
{
["category_header"] = "Shadowlands",
["max_weekly_quantity"] = 0,
["name"] = "Cataloged Research",
["max_quantity"] = 0,
["id"] = 1931,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 1155,
},
{
["category_header"] = "Shadowlands",
["max_weekly_quantity"] = 0,
["name"] = "Cosmic Flux",
["max_quantity"] = 0,
["id"] = 2009,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 1128,
},
{
["category_header"] = "Shadowlands",
["max_weekly_quantity"] = 0,
["name"] = "Cyphers of the First Ones",
["max_quantity"] = 0,
["id"] = 1979,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 248,
},
{
["category_header"] = "Shadowlands",
["max_weekly_quantity"] = 0,
["name"] = "Grateful Offering",
["max_quantity"] = 0,
["id"] = 1885,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 39,
},
{
["category_header"] = "Shadowlands",
["max_weekly_quantity"] = 0,
["name"] = "Infused Ruby",
["max_quantity"] = 100,
["id"] = 1820,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 100,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Reservoir Anima",
["max_quantity"] = 200000,
["id"] = 1813,
["category_header"] = "Shadowlands",
["quantity_earned_this_week"] = 0,
["quantity"] = 27455,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Sinstone Fragments",
["max_quantity"] = 0,
["id"] = 1816,
["category_header"] = "Shadowlands",
["quantity_earned_this_week"] = 0,
["quantity"] = 4070,
},
{
["category_header"] = "Shadowlands",
["max_weekly_quantity"] = 0,
["name"] = "Soul Ash",
["max_quantity"] = 0,
["id"] = 1828,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 24188,
},
{
["category_header"] = "Shadowlands",
["max_weekly_quantity"] = 0,
["name"] = "Soul Cinders",
["max_quantity"] = 0,
["id"] = 1906,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 91,
},
{
["category_header"] = "Shadowlands",
["max_weekly_quantity"] = 0,
["name"] = "Stygia",
["max_quantity"] = 0,
["id"] = 1767,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 2066,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Stygian Ember",
["max_quantity"] = 0,
["id"] = 1977,
["category_header"] = "Shadowlands",
["quantity_earned_this_week"] = 0,
["quantity"] = 37,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Tower Knowledge",
["max_quantity"] = 3510,
["id"] = 1904,
["category_header"] = "Shadowlands",
["quantity_earned_this_week"] = 0,
["quantity"] = 92,
},
{
["category_header"] = "Battle for Azeroth",
["max_weekly_quantity"] = 0,
["name"] = "Coalescing Visions",
["max_quantity"] = 0,
["id"] = 1755,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 20858,
},
{
["category_header"] = "Battle for Azeroth",
["max_weekly_quantity"] = 0,
["name"] = "Corrupted Mementos",
["max_quantity"] = 0,
["id"] = 1719,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 1989,
},
{
["category_header"] = "Battle for Azeroth",
["max_weekly_quantity"] = 0,
["name"] = "Echoes of Ny'alotha",
["max_quantity"] = 0,
["id"] = 1803,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 7395,
},
{
["category_header"] = "Battle for Azeroth",
["max_weekly_quantity"] = 0,
["name"] = "Honorbound Service Medal",
["max_quantity"] = 0,
["id"] = 1716,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 65,
},
{
["category_header"] = "Battle for Azeroth",
["max_weekly_quantity"] = 0,
["name"] = "Prismatic Manapearl",
["max_quantity"] = 0,
["id"] = 1721,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 614,
},
{
["category_header"] = "Battle for Azeroth",
["max_weekly_quantity"] = 0,
["name"] = "Seafarer's Dubloon",
["max_quantity"] = 0,
["id"] = 1710,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 12,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Seal of Wartorn Fate",
["max_quantity"] = 5,
["id"] = 1580,
["category_header"] = "Battle for Azeroth",
["quantity_earned_this_week"] = 0,
["quantity"] = 0,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Titan Residuum",
["max_quantity"] = 0,
["id"] = 1718,
["category_header"] = "Battle for Azeroth",
["quantity_earned_this_week"] = 0,
["quantity"] = 0,
},
{
["category_header"] = "Battle for Azeroth",
["max_weekly_quantity"] = 0,
["name"] = "War Resources",
["max_quantity"] = 0,
["id"] = 1560,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 4829,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Ancient Mana",
["max_quantity"] = 1600,
["id"] = 1155,
["category_header"] = "Legion",
["quantity_earned_this_week"] = 0,
["quantity"] = 1359,
},
{
["category_header"] = "Legion",
["max_weekly_quantity"] = 0,
["name"] = "Curious Coin",
["max_quantity"] = 0,
["id"] = 1275,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 35,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Legionfall War Supplies",
["max_quantity"] = 1000,
["id"] = 1342,
["category_header"] = "Legion",
["quantity_earned_this_week"] = 0,
["quantity"] = 587,
},
{
["max_weekly_quantity"] = 20,
["name"] = "Lingering Soul Fragment",
["max_quantity"] = 40,
["id"] = 1314,
["category_header"] = "Legion",
["quantity_earned_this_week"] = 0,
["quantity"] = 1,
},
{
["category_header"] = "Legion",
["max_weekly_quantity"] = 0,
["name"] = "Nethershard",
["max_quantity"] = 0,
["id"] = 1226,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 4356,
},
{
["category_header"] = "Legion",
["max_weekly_quantity"] = 0,
["name"] = "Order Resources",
["max_quantity"] = 0,
["id"] = 1220,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 62,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Sightless Eye",
["max_quantity"] = 5000,
["id"] = 1149,
["category_header"] = "Legion",
["quantity_earned_this_week"] = 0,
["quantity"] = 40,
},
{
["category_header"] = "Legion",
["max_weekly_quantity"] = 0,
["name"] = "Veiled Argunite",
["max_quantity"] = 2000,
["id"] = 1508,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["quantity"] = 2000,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Wakening Essence",
["max_quantity"] = 0,
["id"] = 1533,
["category_header"] = "Legion",
["quantity_earned_this_week"] = 0,
["quantity"] = 3602,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Artifact Fragment",
["max_quantity"] = 1000,
["id"] = 944,
["category_header"] = "Warlords of Draenor",
["quantity_earned_this_week"] = 0,
["quantity"] = 0,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Garrison Resources",
["max_quantity"] = 10000,
["id"] = 824,
["category_header"] = "Warlords of Draenor",
["quantity_earned_this_week"] = 0,
["quantity"] = 3080,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Lesser Charm of Good Fortune",
["max_quantity"] = 0,
["id"] = 738,
["category_header"] = "Mists of Pandaria",
["quantity_earned_this_week"] = 0,
["quantity"] = 8,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Mote of Darkness",
["max_quantity"] = 0,
["id"] = 614,
["category_header"] = "Cataclysm",
["quantity_earned_this_week"] = 0,
["quantity"] = 2,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Spirit Shard",
["max_quantity"] = 200,
["id"] = 1704,
["category_header"] = "Burning Crusade",
["quantity_earned_this_week"] = 0,
["quantity"] = 3,
},
},
},
},
},
["schema_version"] = 5,
["addon_folder"] = "AzerothDataCollector_Currencies",
["last_saved_at"] = 1778494570,
}
