
AzerothDataCollector_ReputationsDB = {
["module_key"] = "reputations",
["by_character"] = {
["Player-3674-09D241D0"] = {
["reputations"] = {
["updated_at"] = 1778492011,
["partial"] = false,
["records"] = {
{
["name"] = "Amani Tribe",
["faction_type"] = "major",
["id"] = 2696,
["renown_rep_earned"] = 2310,
["renown_level"] = 5,
["renown_threshold"] = 2500,
},
{
["name"] = "Hara'ti",
["faction_type"] = "major",
["id"] = 2704,
["renown_rep_earned"] = 2380,
["renown_level"] = 4,
["renown_threshold"] = 2500,
},
{
["name"] = "The Singularity",
["faction_type"] = "major",
["id"] = 2699,
["renown_rep_earned"] = 1990,
["renown_level"] = 4,
["renown_threshold"] = 2500,
},
{
["name"] = "Blood Knights",
["faction_type"] = "friendship",
["id"] = 2712,
["friendship_level"] = 1,
["friendship_standing"] = 75,
["friendship_next_threshold"] = 500,
},
{
["name"] = "Farstriders",
["faction_type"] = "friendship",
["id"] = 2713,
["friendship_level"] = 1,
["friendship_standing"] = 0,
["friendship_next_threshold"] = 500,
},
{
["name"] = "Magisters",
["faction_type"] = "friendship",
["id"] = 2711,
["friendship_level"] = 1,
["friendship_standing"] = 100,
["friendship_next_threshold"] = 500,
},
{
["name"] = "Shades of the Row",
["faction_type"] = "friendship",
["id"] = 2714,
["friendship_level"] = 1,
["friendship_standing"] = 0,
["friendship_next_threshold"] = 500,
},
{
["name"] = "Valeera Sanguinar",
["faction_type"] = "friendship",
["id"] = 2744,
["friendship_level"] = 4,
["friendship_standing"] = 9616,
["friendship_next_threshold"] = 13420,
},
{
["name"] = "Council of Dornogal",
["faction_type"] = "major",
["id"] = 2590,
["renown_rep_earned"] = 567,
["renown_level"] = 18,
["renown_threshold"] = 2500,
},
{
["name"] = "Hallowfall Arathi",
["faction_type"] = "major",
["id"] = 2570,
["renown_rep_earned"] = 1007,
["renown_level"] = 17,
["renown_threshold"] = 2500,
},
{
["name"] = "The Assembly of the Deeps",
["faction_type"] = "major",
["id"] = 2594,
["renown_rep_earned"] = 1447,
["renown_level"] = 18,
["renown_threshold"] = 2500,
},
{
["name"] = "The K'aresh Trust",
["faction_type"] = "major",
["id"] = 2658,
["renown_rep_earned"] = 500,
["renown_level"] = 2,
["renown_threshold"] = 2500,
},
{
["name"] = "Gallagio Loyalty Rewards Club",
["faction_type"] = "major",
["id"] = 2685,
["renown_rep_earned"] = 250,
["renown_level"] = 1,
["renown_threshold"] = 2500,
},
{
["name"] = "The General",
["faction_type"] = "friendship",
["id"] = 2605,
["friendship_level"] = 6,
["friendship_standing"] = 12676,
["friendship_next_threshold"] = 15000,
},
{
["name"] = "The Vizier",
["faction_type"] = "friendship",
["id"] = 2607,
["friendship_level"] = 7,
["friendship_standing"] = 16486,
["friendship_next_threshold"] = 17500,
},
{
["name"] = "The Weaver",
["faction_type"] = "friendship",
["id"] = 2601,
["friendship_level"] = 7,
["friendship_standing"] = 16206,
["friendship_next_threshold"] = 17500,
},
{
["name"] = "Brann Bronzebeard",
["faction_type"] = "friendship",
["id"] = 2640,
["friendship_level"] = 42,
["friendship_standing"] = 1104286,
["friendship_next_threshold"] = 1110600,
},
{
["name"] = "Dream Wardens",
["faction_type"] = "major",
["id"] = 2574,
["renown_rep_earned"] = 0,
["renown_level"] = 20,
["renown_threshold"] = 2500,
},
{
["name"] = "Iskaara Tuskarr",
["faction_type"] = "major",
["id"] = 2511,
["renown_rep_earned"] = 343,
["renown_level"] = 24,
["renown_threshold"] = 2500,
},
{
["name"] = "Loamm Niffen",
["faction_type"] = "major",
["id"] = 2564,
["renown_rep_earned"] = 0,
["renown_level"] = 20,
["renown_threshold"] = 2500,
},
{
["name"] = "Maruuk Centaur",
["faction_type"] = "major",
["id"] = 2503,
["renown_rep_earned"] = 78,
["renown_level"] = 22,
["renown_threshold"] = 2500,
},
{
["name"] = "Azerothian Archives",
["faction_type"] = "friendship",
["id"] = 2615,
["friendship_level"] = 1,
["friendship_standing"] = 9685,
["friendship_next_threshold"] = 10500,
},
{
["name"] = "Artisan's Consortium - Dragon Isles Branch",
["faction_type"] = "friendship",
["id"] = 2544,
["friendship_level"] = 1,
["friendship_standing"] = 100,
["friendship_next_threshold"] = 500,
},
{
["name"] = "Cobalt Assembly",
["faction_type"] = "friendship",
["id"] = 2550,
["friendship_level"] = 2,
["friendship_standing"] = 325,
["friendship_next_threshold"] = 1200,
},
{
["name"] = "Sabellian",
["faction_type"] = "friendship",
["id"] = 2518,
["friendship_level"] = 1,
["friendship_standing"] = 6000,
["friendship_next_threshold"] = 8400,
},
{
["name"] = "Soridormi",
["faction_type"] = "friendship",
["id"] = 2553,
["friendship_level"] = 3,
["friendship_standing"] = 22842,
["friendship_next_threshold"] = 24000,
},
{
["name"] = "Wrathion",
["faction_type"] = "friendship",
["id"] = 2517,
["friendship_level"] = 2,
["friendship_standing"] = 10000,
["friendship_next_threshold"] = 16800,
},
{
["name"] = "Court of Harvesters",
["faction_type"] = "paragon",
["id"] = 2413,
["paragon_value"] = 262,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "Court of Night",
["faction_type"] = "friendship",
["id"] = 2464,
["friendship_level"] = 3,
["friendship_standing"] = 17000,
["friendship_next_threshold"] = 21000,
},
{
["name"] = "Death's Advance",
["faction_type"] = "paragon",
["id"] = 2470,
["paragon_value"] = 7750,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "The Archivists' Codex",
["faction_type"] = "friendship",
["id"] = 2472,
["friendship_level"] = 6,
["friendship_standing"] = 41000,
},
{
["name"] = "The Ascended",
["faction_type"] = "paragon",
["id"] = 2407,
["paragon_value"] = 1900,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "The Enlightened",
["faction_type"] = "paragon",
["id"] = 2478,
["paragon_value"] = 0,
["paragon_threshold"] = 10000,
["standing_index"] = 7,
},
{
["name"] = "The Undying Army",
["faction_type"] = "paragon",
["id"] = 2410,
["paragon_value"] = 1875,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "The Wild Hunt",
["faction_type"] = "paragon",
["id"] = 2465,
["paragon_value"] = 1425,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "Ve'nari",
["faction_type"] = "friendship",
["id"] = 2432,
["friendship_level"] = 6,
["friendship_standing"] = 42000,
},
{
["name"] = "Champions of Azeroth",
["faction_type"] = "paragon",
["id"] = 2164,
["paragon_value"] = 0,
["paragon_threshold"] = 10000,
["standing_index"] = 7,
},
{
["name"] = "Rajani",
["faction_type"] = "paragon",
["id"] = 2415,
["paragon_value"] = 0,
["paragon_threshold"] = 10000,
["standing_index"] = 7,
},
{
["name"] = "Rustbolt Resistance",
["faction_type"] = "paragon",
["id"] = 2391,
["paragon_value"] = 0,
["paragon_threshold"] = 10000,
["standing_index"] = 4,
},
{
["name"] = "Talanji's Expedition",
["faction_type"] = "paragon",
["id"] = 2156,
["paragon_value"] = 0,
["paragon_threshold"] = 10000,
["standing_index"] = 7,
},
{
["name"] = "The Honorbound",
["faction_type"] = "paragon",
["id"] = 2157,
["paragon_value"] = 3525,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "The Unshackled",
["faction_type"] = "paragon",
["id"] = 2373,
["paragon_value"] = 0,
["paragon_threshold"] = 10000,
["standing_index"] = 4,
},
{
["name"] = "Tortollan Seekers",
["faction_type"] = "paragon",
["id"] = 2163,
["paragon_value"] = 0,
["paragon_threshold"] = 10000,
["standing_index"] = 6,
},
{
["name"] = "Uldum Accord",
["faction_type"] = "paragon",
["id"] = 2417,
["paragon_value"] = 0,
["paragon_threshold"] = 10000,
["standing_index"] = 7,
},
{
["name"] = "Voldunai",
["faction_type"] = "paragon",
["id"] = 2158,
["paragon_value"] = 0,
["paragon_threshold"] = 10000,
["standing_index"] = 7,
},
{
["name"] = "Zandalari Empire",
["faction_type"] = "paragon",
["id"] = 2103,
["paragon_value"] = 0,
["paragon_threshold"] = 10000,
["standing_index"] = 6,
},
{
["name"] = "The Nightfallen",
["faction_type"] = "paragon",
["id"] = 1859,
["paragon_value"] = 0,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "Golden Lotus",
["faction_type"] = "normal",
["id"] = 1269,
["is_header"] = false,
["reputation_value"] = 0,
["standing_index"] = 4,
},
{
["name"] = "Shado-Pan",
["faction_type"] = "normal",
["id"] = 1270,
["is_header"] = false,
["reputation_value"] = 750,
["standing_index"] = 4,
},
{
["name"] = "The Black Prince",
["faction_type"] = "normal",
["id"] = 1359,
["is_header"] = false,
["reputation_value"] = 2800,
["standing_index"] = 4,
},
{
["name"] = "The Lorewalkers",
["faction_type"] = "normal",
["id"] = 1345,
["is_header"] = false,
["reputation_value"] = 0,
["standing_index"] = 4,
},
{
["name"] = "Avengers of Hyjal",
["faction_type"] = "normal",
["id"] = 1204,
["is_header"] = false,
["reputation_value"] = 5650,
["standing_index"] = 5,
},
{
["name"] = "Dragonmaw Clan",
["faction_type"] = "normal",
["id"] = 1172,
["is_header"] = false,
["reputation_value"] = 0,
["standing_index"] = 4,
},
{
["name"] = "Ramkahen",
["faction_type"] = "normal",
["id"] = 1173,
["is_header"] = false,
["reputation_value"] = 0,
["standing_index"] = 4,
},
{
["name"] = "Argent Crusade",
["faction_type"] = "normal",
["id"] = 1106,
["is_header"] = false,
["reputation_value"] = 0,
["standing_index"] = 4,
},
{
["name"] = "Kirin Tor",
["faction_type"] = "normal",
["id"] = 1090,
["is_header"] = false,
["reputation_value"] = 0,
["standing_index"] = 4,
},
{
["name"] = "Knights of the Ebon Blade",
["faction_type"] = "normal",
["id"] = 1098,
["is_header"] = false,
["reputation_value"] = 0,
["standing_index"] = 4,
},
{
["name"] = "The Ashen Verdict",
["faction_type"] = "normal",
["id"] = 1156,
["is_header"] = false,
["reputation_value"] = 14690,
["standing_index"] = 6,
},
{
["name"] = "Warsong Offensive",
["faction_type"] = "normal",
["id"] = 1085,
["is_header"] = false,
["reputation_value"] = 0,
["standing_index"] = 4,
},
{
["name"] = "Ashtongue Deathsworn",
["faction_type"] = "normal",
["id"] = 1012,
["is_header"] = false,
["reputation_value"] = 10763,
["standing_index"] = 6,
},
{
["name"] = "Keepers of Time",
["faction_type"] = "normal",
["id"] = 989,
["is_header"] = false,
["reputation_value"] = 0,
["standing_index"] = 4,
},
{
["name"] = "Thrallmar",
["faction_type"] = "normal",
["id"] = 947,
["is_header"] = false,
["reputation_value"] = 0,
["standing_index"] = 4,
},
{
["name"] = "The Sha'tar",
["faction_type"] = "normal",
["id"] = 935,
["is_header"] = false,
["reputation_value"] = 4939,
["standing_index"] = 5,
},
{
["name"] = "Darkmoon Faire",
["faction_type"] = "normal",
["id"] = 909,
["is_header"] = false,
["reputation_value"] = 3825,
["standing_index"] = 5,
},
{
["name"] = "Thorium Brotherhood",
["faction_type"] = "normal",
["id"] = 59,
["is_header"] = false,
["reputation_value"] = 0,
["standing_index"] = 4,
},
{
["name"] = "Bilgewater Cartel",
["faction_type"] = "normal",
["id"] = 1133,
["is_header"] = false,
["reputation_value"] = 3152,
["standing_index"] = 5,
},
{
["name"] = "Darkspear Trolls",
["faction_type"] = "normal",
["id"] = 530,
["is_header"] = false,
["reputation_value"] = 3152,
["standing_index"] = 5,
},
{
["name"] = "Huojin Pandaren",
["faction_type"] = "normal",
["id"] = 1352,
["is_header"] = false,
["reputation_value"] = 3152,
["standing_index"] = 5,
},
{
["name"] = "Orgrimmar",
["faction_type"] = "normal",
["id"] = 76,
["is_header"] = false,
["reputation_value"] = 3310,
["standing_index"] = 5,
},
{
["name"] = "Silvermoon City",
["faction_type"] = "normal",
["id"] = 911,
["is_header"] = false,
["reputation_value"] = 453,
["standing_index"] = 4,
},
{
["name"] = "Thunder Bluff",
["faction_type"] = "normal",
["id"] = 81,
["is_header"] = false,
["reputation_value"] = 3152,
["standing_index"] = 5,
},
{
["name"] = "Undercity",
["faction_type"] = "normal",
["id"] = 68,
["is_header"] = false,
["reputation_value"] = 553,
["standing_index"] = 4,
},
{
["name"] = "Frostwolf Clan",
["faction_type"] = "normal",
["id"] = 729,
["is_header"] = false,
["reputation_value"] = 1460,
["standing_index"] = 4,
},
{
["name"] = "Booty Bay",
["faction_type"] = "normal",
["id"] = 21,
["is_header"] = false,
["reputation_value"] = 750,
["standing_index"] = 4,
},
{
["name"] = "Everlook",
["faction_type"] = "normal",
["id"] = 577,
["is_header"] = false,
["reputation_value"] = 750,
["standing_index"] = 4,
},
{
["name"] = "Gadgetzan",
["faction_type"] = "normal",
["id"] = 369,
["is_header"] = false,
["reputation_value"] = 750,
["standing_index"] = 4,
},
{
["name"] = "Ratchet",
["faction_type"] = "normal",
["id"] = 470,
["is_header"] = false,
["reputation_value"] = 750,
["standing_index"] = 4,
},
{
["is_header"] = false,
["name"] = "Radioactive",
["faction_type"] = "normal",
["id"] = 1168,
["reputation_value"] = 25663,
["is_guild"] = true,
["standing_index"] = 7,
},
{
["name"] = "Keg Leg's Crew",
["faction_type"] = "major",
["id"] = 2593,
["renown_rep_earned"] = 12,
["renown_level"] = 1,
["renown_threshold"] = 2500,
},
{
["name"] = "The Avowed",
["faction_type"] = "normal",
["id"] = 2439,
["is_header"] = false,
["reputation_value"] = 3390,
["standing_index"] = 5,
},
},
},
},
["Player-3674-0BB3F0D1"] = {
["reputations"] = {
["updated_at"] = 1778448480,
["partial"] = false,
["records"] = {
{
["name"] = "Amani Tribe",
["faction_type"] = "major",
["id"] = 2696,
["renown_rep_earned"] = 2310,
["renown_level"] = 5,
["renown_threshold"] = 2500,
},
{
["name"] = "Hara'ti",
["faction_type"] = "major",
["id"] = 2704,
["renown_rep_earned"] = 2380,
["renown_level"] = 4,
["renown_threshold"] = 2500,
},
{
["name"] = "The Singularity",
["faction_type"] = "major",
["id"] = 2699,
["renown_rep_earned"] = 1990,
["renown_level"] = 4,
["renown_threshold"] = 2500,
},
{
["name"] = "Blood Knights",
["faction_type"] = "friendship",
["id"] = 2712,
["friendship_level"] = 1,
["friendship_standing"] = 75,
["friendship_next_threshold"] = 500,
},
{
["name"] = "Farstriders",
["faction_type"] = "friendship",
["id"] = 2713,
["friendship_level"] = 1,
["friendship_standing"] = 0,
["friendship_next_threshold"] = 500,
},
{
["name"] = "Magisters",
["faction_type"] = "friendship",
["id"] = 2711,
["friendship_level"] = 1,
["friendship_standing"] = 100,
["friendship_next_threshold"] = 500,
},
{
["name"] = "Shades of the Row",
["faction_type"] = "friendship",
["id"] = 2714,
["friendship_level"] = 1,
["friendship_standing"] = 0,
["friendship_next_threshold"] = 500,
},
{
["name"] = "Valeera Sanguinar",
["faction_type"] = "friendship",
["id"] = 2744,
["friendship_level"] = 4,
["friendship_standing"] = 9616,
["friendship_next_threshold"] = 13420,
},
{
["name"] = "Council of Dornogal",
["faction_type"] = "major",
["id"] = 2590,
["renown_rep_earned"] = 567,
["renown_level"] = 18,
["renown_threshold"] = 2500,
},
{
["name"] = "Hallowfall Arathi",
["faction_type"] = "major",
["id"] = 2570,
["renown_rep_earned"] = 1007,
["renown_level"] = 17,
["renown_threshold"] = 2500,
},
{
["name"] = "The Assembly of the Deeps",
["faction_type"] = "major",
["id"] = 2594,
["renown_rep_earned"] = 1447,
["renown_level"] = 18,
["renown_threshold"] = 2500,
},
{
["name"] = "The K'aresh Trust",
["faction_type"] = "major",
["id"] = 2658,
["renown_rep_earned"] = 500,
["renown_level"] = 2,
["renown_threshold"] = 2500,
},
{
["name"] = "Gallagio Loyalty Rewards Club",
["faction_type"] = "major",
["id"] = 2685,
["renown_rep_earned"] = 250,
["renown_level"] = 1,
["renown_threshold"] = 2500,
},
{
["name"] = "The General",
["faction_type"] = "friendship",
["id"] = 2605,
["friendship_level"] = 6,
["friendship_standing"] = 12676,
["friendship_next_threshold"] = 15000,
},
{
["name"] = "The Vizier",
["faction_type"] = "friendship",
["id"] = 2607,
["friendship_level"] = 7,
["friendship_standing"] = 16486,
["friendship_next_threshold"] = 17500,
},
{
["name"] = "The Weaver",
["faction_type"] = "friendship",
["id"] = 2601,
["friendship_level"] = 7,
["friendship_standing"] = 16206,
["friendship_next_threshold"] = 17500,
},
{
["name"] = "Brann Bronzebeard",
["faction_type"] = "friendship",
["id"] = 2640,
["friendship_level"] = 42,
["friendship_standing"] = 1104286,
["friendship_next_threshold"] = 1110600,
},
{
["name"] = "Dream Wardens",
["faction_type"] = "major",
["id"] = 2574,
["renown_rep_earned"] = 0,
["renown_level"] = 20,
["renown_threshold"] = 2500,
},
{
["name"] = "Iskaara Tuskarr",
["faction_type"] = "major",
["id"] = 2511,
["renown_rep_earned"] = 343,
["renown_level"] = 24,
["renown_threshold"] = 2500,
},
{
["name"] = "Loamm Niffen",
["faction_type"] = "major",
["id"] = 2564,
["renown_rep_earned"] = 0,
["renown_level"] = 20,
["renown_threshold"] = 2500,
},
{
["name"] = "Maruuk Centaur",
["faction_type"] = "major",
["id"] = 2503,
["renown_rep_earned"] = 78,
["renown_level"] = 22,
["renown_threshold"] = 2500,
},
{
["name"] = "Azerothian Archives",
["faction_type"] = "friendship",
["id"] = 2615,
["friendship_level"] = 1,
["friendship_standing"] = 9685,
["friendship_next_threshold"] = 10500,
},
{
["name"] = "Artisan's Consortium - Dragon Isles Branch",
["faction_type"] = "friendship",
["id"] = 2544,
["friendship_level"] = 1,
["friendship_standing"] = 100,
["friendship_next_threshold"] = 500,
},
{
["name"] = "Cobalt Assembly",
["faction_type"] = "friendship",
["id"] = 2550,
["friendship_level"] = 2,
["friendship_standing"] = 325,
["friendship_next_threshold"] = 1200,
},
{
["name"] = "Sabellian",
["faction_type"] = "friendship",
["id"] = 2518,
["friendship_level"] = 1,
["friendship_standing"] = 6000,
["friendship_next_threshold"] = 8400,
},
{
["name"] = "Soridormi",
["faction_type"] = "friendship",
["id"] = 2553,
["friendship_level"] = 3,
["friendship_standing"] = 22842,
["friendship_next_threshold"] = 24000,
},
{
["name"] = "Wrathion",
["faction_type"] = "friendship",
["id"] = 2517,
["friendship_level"] = 2,
["friendship_standing"] = 10000,
["friendship_next_threshold"] = 16800,
},
{
["name"] = "Court of Harvesters",
["faction_type"] = "paragon",
["id"] = 2413,
["paragon_value"] = 262,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "Court of Night",
["faction_type"] = "friendship",
["id"] = 2464,
["friendship_level"] = 3,
["friendship_standing"] = 17000,
["friendship_next_threshold"] = 21000,
},
{
["name"] = "Death's Advance",
["faction_type"] = "paragon",
["id"] = 2470,
["paragon_value"] = 7750,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "The Archivists' Codex",
["faction_type"] = "friendship",
["id"] = 2472,
["friendship_level"] = 6,
["friendship_standing"] = 41000,
},
{
["name"] = "The Ascended",
["faction_type"] = "paragon",
["id"] = 2407,
["paragon_value"] = 1900,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "The Enlightened",
["faction_type"] = "paragon",
["id"] = 2478,
["paragon_value"] = 0,
["paragon_threshold"] = 10000,
["standing_index"] = 7,
},
{
["name"] = "The Undying Army",
["faction_type"] = "paragon",
["id"] = 2410,
["paragon_value"] = 1875,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "The Wild Hunt",
["faction_type"] = "paragon",
["id"] = 2465,
["paragon_value"] = 1425,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "Ve'nari",
["faction_type"] = "friendship",
["id"] = 2432,
["friendship_level"] = 6,
["friendship_standing"] = 42000,
},
{
["name"] = "Bilgewater Cartel",
["faction_type"] = "normal",
["id"] = 1133,
["is_header"] = false,
["reputation_value"] = 3368,
["standing_index"] = 5,
},
{
["name"] = "Darkspear Trolls",
["faction_type"] = "normal",
["id"] = 530,
["is_header"] = false,
["reputation_value"] = 768,
["standing_index"] = 4,
},
{
["name"] = "Huojin Pandaren",
["faction_type"] = "normal",
["id"] = 1352,
["is_header"] = false,
["reputation_value"] = 3368,
["standing_index"] = 5,
},
{
["name"] = "Orgrimmar",
["faction_type"] = "normal",
["id"] = 76,
["is_header"] = false,
["reputation_value"] = 768,
["standing_index"] = 4,
},
{
["name"] = "Silvermoon City",
["faction_type"] = "normal",
["id"] = 911,
["is_header"] = false,
["reputation_value"] = 9870,
["standing_index"] = 6,
},
{
["name"] = "Thunder Bluff",
["faction_type"] = "normal",
["id"] = 81,
["is_header"] = false,
["reputation_value"] = 768,
["standing_index"] = 4,
},
{
["name"] = "Undercity",
["faction_type"] = "normal",
["id"] = 68,
["is_header"] = false,
["reputation_value"] = 3368,
["standing_index"] = 5,
},
{
["name"] = "Keg Leg's Crew",
["faction_type"] = "major",
["id"] = 2593,
["renown_rep_earned"] = 12,
["renown_level"] = 1,
["renown_threshold"] = 2500,
},
{
["name"] = "The Avowed",
["faction_type"] = "normal",
["id"] = 2439,
["is_header"] = false,
["reputation_value"] = 3390,
["standing_index"] = 5,
},
},
},
},
["Player-3674-09C5872B"] = {
["reputations"] = {
["updated_at"] = 1778492166,
["records"] = {
{
["name"] = "Amani Tribe",
["faction_type"] = "major",
["id"] = 2696,
["renown_rep_earned"] = 2310,
["renown_threshold"] = 2500,
["renown_level"] = 5,
},
{
["name"] = "Hara'ti",
["faction_type"] = "major",
["id"] = 2704,
["renown_rep_earned"] = 2380,
["renown_threshold"] = 2500,
["renown_level"] = 4,
},
{
["name"] = "The Singularity",
["faction_type"] = "major",
["id"] = 2699,
["renown_rep_earned"] = 1990,
["renown_threshold"] = 2500,
["renown_level"] = 4,
},
{
["name"] = "Blood Knights",
["faction_type"] = "friendship",
["id"] = 2712,
["friendship_level"] = 1,
["friendship_next_threshold"] = 500,
["friendship_standing"] = 75,
},
{
["name"] = "Farstriders",
["faction_type"] = "friendship",
["id"] = 2713,
["friendship_level"] = 1,
["friendship_next_threshold"] = 500,
["friendship_standing"] = 0,
},
{
["name"] = "Magisters",
["faction_type"] = "friendship",
["id"] = 2711,
["friendship_level"] = 1,
["friendship_next_threshold"] = 500,
["friendship_standing"] = 100,
},
{
["name"] = "Shades of the Row",
["faction_type"] = "friendship",
["id"] = 2714,
["friendship_level"] = 1,
["friendship_next_threshold"] = 500,
["friendship_standing"] = 0,
},
{
["name"] = "Valeera Sanguinar",
["faction_type"] = "friendship",
["id"] = 2744,
["friendship_level"] = 4,
["friendship_next_threshold"] = 13420,
["friendship_standing"] = 9616,
},
{
["name"] = "Council of Dornogal",
["faction_type"] = "major",
["id"] = 2590,
["renown_rep_earned"] = 567,
["renown_threshold"] = 2500,
["renown_level"] = 18,
},
{
["name"] = "Hallowfall Arathi",
["faction_type"] = "major",
["id"] = 2570,
["renown_rep_earned"] = 1007,
["renown_threshold"] = 2500,
["renown_level"] = 17,
},
{
["name"] = "The Assembly of the Deeps",
["faction_type"] = "major",
["id"] = 2594,
["renown_rep_earned"] = 1447,
["renown_threshold"] = 2500,
["renown_level"] = 18,
},
{
["name"] = "The K'aresh Trust",
["faction_type"] = "major",
["id"] = 2658,
["renown_rep_earned"] = 500,
["renown_threshold"] = 2500,
["renown_level"] = 2,
},
{
["name"] = "Gallagio Loyalty Rewards Club",
["faction_type"] = "major",
["id"] = 2685,
["renown_rep_earned"] = 250,
["renown_threshold"] = 2500,
["renown_level"] = 1,
},
{
["name"] = "The General",
["faction_type"] = "friendship",
["id"] = 2605,
["friendship_level"] = 6,
["friendship_next_threshold"] = 15000,
["friendship_standing"] = 12676,
},
{
["name"] = "The Vizier",
["faction_type"] = "friendship",
["id"] = 2607,
["friendship_level"] = 7,
["friendship_next_threshold"] = 17500,
["friendship_standing"] = 16486,
},
{
["name"] = "The Weaver",
["faction_type"] = "friendship",
["id"] = 2601,
["friendship_level"] = 7,
["friendship_next_threshold"] = 17500,
["friendship_standing"] = 16206,
},
{
["name"] = "Brann Bronzebeard",
["faction_type"] = "friendship",
["id"] = 2640,
["friendship_level"] = 42,
["friendship_next_threshold"] = 1110600,
["friendship_standing"] = 1104286,
},
{
["name"] = "Dream Wardens",
["faction_type"] = "major",
["id"] = 2574,
["renown_rep_earned"] = 0,
["renown_threshold"] = 2500,
["renown_level"] = 20,
},
{
["name"] = "Iskaara Tuskarr",
["faction_type"] = "major",
["id"] = 2511,
["renown_rep_earned"] = 343,
["renown_threshold"] = 2500,
["renown_level"] = 24,
},
{
["name"] = "Loamm Niffen",
["faction_type"] = "major",
["id"] = 2564,
["renown_rep_earned"] = 0,
["renown_threshold"] = 2500,
["renown_level"] = 20,
},
{
["name"] = "Maruuk Centaur",
["faction_type"] = "major",
["id"] = 2503,
["renown_rep_earned"] = 78,
["renown_threshold"] = 2500,
["renown_level"] = 22,
},
{
["name"] = "Azerothian Archives",
["faction_type"] = "friendship",
["id"] = 2615,
["friendship_level"] = 1,
["friendship_next_threshold"] = 10500,
["friendship_standing"] = 9685,
},
{
["name"] = "Artisan's Consortium - Dragon Isles Branch",
["faction_type"] = "friendship",
["id"] = 2544,
["friendship_level"] = 1,
["friendship_next_threshold"] = 500,
["friendship_standing"] = 100,
},
{
["name"] = "Cobalt Assembly",
["faction_type"] = "friendship",
["id"] = 2550,
["friendship_level"] = 2,
["friendship_next_threshold"] = 1200,
["friendship_standing"] = 325,
},
{
["name"] = "Sabellian",
["faction_type"] = "friendship",
["id"] = 2518,
["friendship_level"] = 1,
["friendship_next_threshold"] = 8400,
["friendship_standing"] = 6000,
},
{
["name"] = "Soridormi",
["faction_type"] = "friendship",
["id"] = 2553,
["friendship_level"] = 3,
["friendship_next_threshold"] = 24000,
["friendship_standing"] = 22842,
},
{
["name"] = "Wrathion",
["faction_type"] = "friendship",
["id"] = 2517,
["friendship_level"] = 2,
["friendship_next_threshold"] = 16800,
["friendship_standing"] = 10000,
},
{
["name"] = "Glimmerogg Racer",
["faction_type"] = "friendship",
["id"] = 2568,
["friendship_level"] = 1,
["friendship_next_threshold"] = 700,
["friendship_standing"] = 0,
},
{
["name"] = "Court of Harvesters",
["faction_type"] = "paragon",
["id"] = 2413,
["paragon_value"] = 262,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "Court of Night",
["faction_type"] = "friendship",
["id"] = 2464,
["friendship_level"] = 3,
["friendship_next_threshold"] = 21000,
["friendship_standing"] = 17000,
},
{
["name"] = "Death's Advance",
["faction_type"] = "paragon",
["id"] = 2470,
["paragon_value"] = 7750,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "The Archivists' Codex",
["faction_type"] = "friendship",
["id"] = 2472,
["friendship_level"] = 6,
["friendship_standing"] = 41000,
},
{
["name"] = "The Ascended",
["faction_type"] = "paragon",
["id"] = 2407,
["paragon_value"] = 1900,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "The Ember Court",
["faction_type"] = "normal",
["id"] = 2445,
["is_header"] = false,
["reputation_value"] = 800,
["standing_index"] = 4,
},
{
["name"] = "The Enlightened",
["faction_type"] = "paragon",
["id"] = 2478,
["paragon_value"] = 0,
["paragon_threshold"] = 10000,
["standing_index"] = 7,
},
{
["name"] = "The Undying Army",
["faction_type"] = "paragon",
["id"] = 2410,
["paragon_value"] = 1875,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "The Wild Hunt",
["faction_type"] = "paragon",
["id"] = 2465,
["paragon_value"] = 1425,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "Ve'nari",
["faction_type"] = "friendship",
["id"] = 2432,
["friendship_level"] = 6,
["friendship_standing"] = 42000,
},
{
["name"] = "Champions of Azeroth",
["faction_type"] = "paragon",
["id"] = 2164,
["paragon_value"] = 6487,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "Rajani",
["faction_type"] = "paragon",
["id"] = 2415,
["paragon_value"] = 150,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "Rustbolt Resistance",
["faction_type"] = "paragon",
["id"] = 2391,
["paragon_value"] = 0,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "Talanji's Expedition",
["faction_type"] = "paragon",
["id"] = 2156,
["paragon_value"] = 2512,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "The Honorbound",
["faction_type"] = "paragon",
["id"] = 2157,
["paragon_value"] = 9012,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "The Unshackled",
["faction_type"] = "paragon",
["id"] = 2373,
["paragon_value"] = 825,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "Tortollan Seekers",
["faction_type"] = "paragon",
["id"] = 2163,
["paragon_value"] = 1782,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "Uldum Accord",
["faction_type"] = "paragon",
["id"] = 2417,
["paragon_value"] = 5220,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "Voldunai",
["faction_type"] = "paragon",
["id"] = 2158,
["paragon_value"] = 6312,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "Zandalari Empire",
["faction_type"] = "paragon",
["id"] = 2103,
["paragon_value"] = 6110,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "Argussian Reach",
["faction_type"] = "paragon",
["id"] = 2170,
["paragon_value"] = 5150,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "Armies of Legionfall",
["faction_type"] = "paragon",
["id"] = 2045,
["paragon_value"] = 9225,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "Army of the Light",
["faction_type"] = "paragon",
["id"] = 2165,
["paragon_value"] = 8300,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "Chromie",
["faction_type"] = "friendship",
["id"] = 2135,
["friendship_level"] = 1,
["friendship_next_threshold"] = 1000,
["friendship_standing"] = 0,
},
{
["name"] = "Court of Farondis",
["faction_type"] = "paragon",
["id"] = 1900,
["paragon_value"] = 0,
["paragon_threshold"] = 10000,
["standing_index"] = 7,
},
{
["name"] = "Dreamweavers",
["faction_type"] = "paragon",
["id"] = 1883,
["paragon_value"] = 0,
["paragon_threshold"] = 10000,
["standing_index"] = 7,
},
{
["name"] = "Highmountain Tribe",
["faction_type"] = "paragon",
["id"] = 1828,
["paragon_value"] = 0,
["paragon_threshold"] = 10000,
["standing_index"] = 6,
},
{
["name"] = "The Nightfallen",
["faction_type"] = "paragon",
["id"] = 1859,
["paragon_value"] = 4000,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "The Wardens",
["faction_type"] = "paragon",
["id"] = 1894,
["paragon_value"] = 0,
["paragon_threshold"] = 10000,
["standing_index"] = 7,
},
{
["name"] = "Valarjar",
["faction_type"] = "paragon",
["id"] = 1948,
["paragon_value"] = 5000,
["paragon_threshold"] = 10000,
["standing_index"] = 8,
},
{
["name"] = "Order of the Awakened",
["faction_type"] = "normal",
["id"] = 1849,
["is_header"] = false,
["reputation_value"] = 0,
["standing_index"] = 4,
},
{
["name"] = "Avengers of Hyjal",
["faction_type"] = "normal",
["id"] = 1204,
["is_header"] = false,
["reputation_value"] = 21205,
["standing_index"] = 7,
},
{
["name"] = "Horde Expedition",
["faction_type"] = "normal",
["id"] = 1052,
["is_header"] = false,
["reputation_value"] = 2515,
["standing_index"] = 4,
},
{
["name"] = "The Ashen Verdict",
["faction_type"] = "normal",
["id"] = 1156,
["is_header"] = false,
["reputation_value"] = 42000,
["standing_index"] = 8,
},
{
["name"] = "Ashtongue Deathsworn",
["faction_type"] = "normal",
["id"] = 1012,
["is_header"] = false,
["reputation_value"] = 42000,
["standing_index"] = 8,
},
{
["name"] = "Sporeggar",
["faction_type"] = "normal",
["id"] = 970,
["is_header"] = false,
["reputation_value"] = 8885,
["standing_index"] = 5,
},
{
["name"] = "Argent Dawn",
["faction_type"] = "normal",
["id"] = 529,
["is_header"] = false,
["reputation_value"] = 200,
["standing_index"] = 4,
},
{
["name"] = "Dark Talons",
["faction_type"] = "normal",
["id"] = 2523,
["is_header"] = false,
["reputation_value"] = 5687,
["standing_index"] = 5,
},
{
["name"] = "Everlook",
["faction_type"] = "normal",
["id"] = 577,
["is_header"] = false,
["reputation_value"] = 750,
["standing_index"] = 4,
},
{
["name"] = "Gadgetzan",
["faction_type"] = "normal",
["id"] = 369,
["is_header"] = false,
["reputation_value"] = 750,
["standing_index"] = 4,
},
{
["name"] = "Ratchet",
["faction_type"] = "normal",
["id"] = 470,
["is_header"] = false,
["reputation_value"] = 750,
["standing_index"] = 4,
},
{
["name"] = "Guild",
["faction_type"] = "normal",
["id"] = 1168,
["is_header"] = false,
["reputation_value"] = 42000,
["standing_index"] = 8,
},
{
["name"] = "Keg Leg's Crew",
["faction_type"] = "major",
["id"] = 2593,
["renown_rep_earned"] = 12,
["renown_threshold"] = 2500,
["renown_level"] = 1,
},
{
["name"] = "Mists of Pandaria",
["faction_type"] = "normal",
["id"] = 1245,
["is_header"] = false,
["reputation_value"] = 0,
["standing_index"] = 4,
},
{
["name"] = "Argent Crusade",
["faction_type"] = "normal",
["id"] = 1106,
["is_header"] = false,
["reputation_value"] = 0,
["standing_index"] = 4,
},
{
["name"] = "Bilgewater Cartel",
["faction_type"] = "normal",
["id"] = 1133,
["is_header"] = false,
["reputation_value"] = 4375,
["standing_index"] = 5,
},
{
["name"] = "Booty Bay",
["faction_type"] = "normal",
["id"] = 21,
["is_header"] = false,
["reputation_value"] = 750,
["standing_index"] = 4,
},
{
["name"] = "Brood of Nozdormu",
["faction_type"] = "normal",
["id"] = 910,
["is_header"] = false,
["reputation_value"] = -32599,
["standing_index"] = 1,
},
{
["name"] = "Cenarion Circle",
["faction_type"] = "normal",
["id"] = 609,
["is_header"] = false,
["reputation_value"] = 2868,
["standing_index"] = 4,
},
{
["name"] = "Cenarion Expedition",
["faction_type"] = "normal",
["id"] = 942,
["is_header"] = false,
["reputation_value"] = 6772,
["standing_index"] = 5,
},
{
["name"] = "Cryptkeeper Kassir",
["faction_type"] = "friendship",
["id"] = 2455,
["friendship_level"] = 1,
["friendship_next_threshold"] = 8400,
["friendship_standing"] = 5800,
},
{
["name"] = "Darkmoon Faire",
["faction_type"] = "normal",
["id"] = 909,
["is_header"] = false,
["reputation_value"] = 10325,
["standing_index"] = 6,
},
{
["name"] = "Darkspear Trolls",
["faction_type"] = "normal",
["id"] = 530,
["is_header"] = false,
["reputation_value"] = 5600,
["standing_index"] = 5,
},
{
["name"] = "Dragonmaw Clan",
["faction_type"] = "normal",
["id"] = 1172,
["is_header"] = false,
["reputation_value"] = 0,
["standing_index"] = 4,
},
{
["name"] = "Frostwolf Clan",
["faction_type"] = "normal",
["id"] = 729,
["is_header"] = false,
["reputation_value"] = 2125,
["standing_index"] = 4,
},
{
["name"] = "Frostwolf Orcs",
["faction_type"] = "normal",
["id"] = 1445,
["is_header"] = false,
["reputation_value"] = 3460,
["standing_index"] = 5,
},
{
["name"] = "Golden Lotus",
["faction_type"] = "normal",
["id"] = 1269,
["is_header"] = false,
["reputation_value"] = 4040,
["standing_index"] = 5,
},
{
["name"] = "Guardians of Hyjal",
["faction_type"] = "normal",
["id"] = 1158,
["is_header"] = false,
["reputation_value"] = 0,
["standing_index"] = 4,
},
{
["name"] = "Huojin Pandaren",
["faction_type"] = "normal",
["id"] = 1352,
["is_header"] = false,
["reputation_value"] = 4375,
["standing_index"] = 5,
},
{
["name"] = "Hydraxian Waterlords",
["faction_type"] = "normal",
["id"] = 749,
["is_header"] = false,
["reputation_value"] = 6565,
["standing_index"] = 5,
},
{
["name"] = "Keepers of Time",
["faction_type"] = "normal",
["id"] = 989,
["is_header"] = false,
["reputation_value"] = 2611,
["standing_index"] = 4,
},
{
["name"] = "Kirin Tor",
["faction_type"] = "normal",
["id"] = 1090,
["is_header"] = false,
["reputation_value"] = 2795,
["standing_index"] = 4,
},
{
["name"] = "Kleia and Pelagos",
["faction_type"] = "friendship",
["id"] = 2458,
["friendship_level"] = 1,
["friendship_next_threshold"] = 8400,
["friendship_standing"] = 300,
},
{
["name"] = "Knights of the Ebon Blade",
["faction_type"] = "normal",
["id"] = 1098,
["is_header"] = false,
["reputation_value"] = 0,
["standing_index"] = 4,
},
{
["name"] = "Orgrimmar",
["faction_type"] = "normal",
["id"] = 76,
["is_header"] = false,
["reputation_value"] = 8999,
["standing_index"] = 5,
},
{
["name"] = "Plague Deviser Marileth",
["faction_type"] = "friendship",
["id"] = 2461,
["friendship_level"] = 1,
["friendship_next_threshold"] = 8400,
["friendship_standing"] = 0,
},
{
["name"] = "Ramkahen",
["faction_type"] = "normal",
["id"] = 1173,
["is_header"] = false,
["reputation_value"] = 1000,
["standing_index"] = 4,
},
{
["name"] = "Ravenholdt",
["faction_type"] = "normal",
["id"] = 349,
["is_header"] = false,
["reputation_value"] = 75,
["standing_index"] = 4,
},
{
["name"] = "Shado-Pan",
["faction_type"] = "normal",
["id"] = 1270,
["is_header"] = false,
["reputation_value"] = 500,
["standing_index"] = 4,
},
{
["name"] = "Shattered Sun Offensive",
["faction_type"] = "normal",
["id"] = 1077,
["is_header"] = false,
["reputation_value"] = 3483,
["standing_index"] = 5,
},
{
["name"] = "Silvermoon City",
["faction_type"] = "normal",
["id"] = 911,
["is_header"] = false,
["reputation_value"] = 5285,
["standing_index"] = 5,
},
{
["name"] = "Syndicate",
["faction_type"] = "normal",
["id"] = 70,
["is_header"] = false,
["reputation_value"] = -10400,
["standing_index"] = 1,
},
{
["name"] = "The August Celestials",
["faction_type"] = "normal",
["id"] = 1341,
["is_header"] = false,
["reputation_value"] = 0,
["standing_index"] = 4,
},
{
["name"] = "The Avowed",
["faction_type"] = "normal",
["id"] = 2439,
["is_header"] = false,
["reputation_value"] = 3390,
["standing_index"] = 5,
},
{
["name"] = "The Black Prince",
["faction_type"] = "normal",
["id"] = 1359,
["is_header"] = false,
["reputation_value"] = 2800,
["standing_index"] = 4,
},
{
["name"] = "The Consortium",
["faction_type"] = "normal",
["id"] = 933,
["is_header"] = false,
["reputation_value"] = 6750,
["standing_index"] = 5,
},
{
["name"] = "The Defilers",
["faction_type"] = "normal",
["id"] = 510,
["is_header"] = false,
["reputation_value"] = 28000,
["standing_index"] = 7,
},
{
["name"] = "The Earthen Ring",
["faction_type"] = "normal",
["id"] = 1135,
["is_header"] = false,
["reputation_value"] = 500,
["standing_index"] = 4,
},
{
["name"] = "The Hand of Vengeance",
["faction_type"] = "normal",
["id"] = 1067,
["is_header"] = false,
["reputation_value"] = 1257,
["standing_index"] = 4,
},
{
["name"] = "The Kalu'ak",
["faction_type"] = "normal",
["id"] = 1073,
["is_header"] = false,
["reputation_value"] = 0,
["standing_index"] = 4,
},
{
["name"] = "The Lorewalkers",
["faction_type"] = "normal",
["id"] = 1345,
["is_header"] = false,
["reputation_value"] = 0,
["standing_index"] = 4,
},
{
["name"] = "The Mag'har",
["faction_type"] = "normal",
["id"] = 941,
["is_header"] = false,
["reputation_value"] = 510,
["standing_index"] = 4,
},
{
["name"] = "The Scale of the Sands",
["faction_type"] = "normal",
["id"] = 990,
["is_header"] = false,
["reputation_value"] = 8412,
["standing_index"] = 5,
},
{
["name"] = "The Scryers",
["faction_type"] = "normal",
["id"] = 934,
["is_header"] = false,
["reputation_value"] = 3500,
["standing_index"] = 5,
},
{
["name"] = "The Sha'tar",
["faction_type"] = "normal",
["id"] = 935,
["is_header"] = false,
["reputation_value"] = 4737,
["standing_index"] = 5,
},
{
["name"] = "The Sunreavers",
["faction_type"] = "normal",
["id"] = 1124,
["is_header"] = false,
["reputation_value"] = 1257,
["standing_index"] = 4,
},
{
["name"] = "The Taunka",
["faction_type"] = "normal",
["id"] = 1064,
["is_header"] = false,
["reputation_value"] = 1257,
["standing_index"] = 4,
},
{
["name"] = "The Violet Eye",
["faction_type"] = "normal",
["id"] = 967,
["is_header"] = false,
["reputation_value"] = 1537,
["standing_index"] = 4,
},
{
["name"] = "The Wyrmrest Accord",
["faction_type"] = "normal",
["id"] = 1091,
["is_header"] = false,
["reputation_value"] = 0,
["standing_index"] = 4,
},
{
["name"] = "Therazane",
["faction_type"] = "normal",
["id"] = 1171,
["is_header"] = false,
["reputation_value"] = -42000,
["standing_index"] = 1,
},
{
["name"] = "Thrallmar",
["faction_type"] = "normal",
["id"] = 947,
["is_header"] = false,
["reputation_value"] = 10246,
["standing_index"] = 6,
},
{
["name"] = "Thunder Bluff",
["faction_type"] = "normal",
["id"] = 81,
["is_header"] = false,
["reputation_value"] = 1775,
["standing_index"] = 4,
},
{
["name"] = "Undercity",
["faction_type"] = "normal",
["id"] = 68,
["is_header"] = false,
["reputation_value"] = 4375,
["standing_index"] = 5,
},
{
["name"] = "Vol'jin's Spear",
["faction_type"] = "normal",
["id"] = 1681,
["is_header"] = false,
["reputation_value"] = 3025,
["standing_index"] = 5,
},
{
["name"] = "Warsong Offensive",
["faction_type"] = "normal",
["id"] = 1085,
["is_header"] = false,
["reputation_value"] = 1257,
["standing_index"] = 4,
},
{
["name"] = "Warsong Outriders",
["faction_type"] = "normal",
["id"] = 889,
["is_header"] = false,
["reputation_value"] = 3375,
["standing_index"] = 5,
},
{
["name"] = "Zandalar Tribe",
["faction_type"] = "normal",
["id"] = 270,
["is_header"] = false,
["reputation_value"] = 0,
["standing_index"] = 4,
},
},
["partial"] = false,
},
},
},
["schema_version"] = 4,
["addon_folder"] = "AzerothDataCollector_Reputations",
["last_saved_at"] = 1778492166,
}
