
AzerothDataCollector_MetaDB = {
["module_key"] = "meta",
["by_character"] = {
["Player-3674-09D241D0"] = {
["meta"] = {
["guid"] = "Player-3674-09D241D0",
["subzone"] = "",
["class"] = "WARLOCK",
["race"] = "Blood Elf",
["level"] = 80,
["class_localized"] = "Warlock",
["realm"] = "Twisting Nether",
["ilvl_overall"] = 0,
["race_id"] = 10,
["spec_index"] = 2,
["server_time"] = "2026-05-11 13:16:22",
["updated_at"] = 1778494582,
["name"] = "Feldr",
["faction"] = "Horde",
["gender_id"] = 3,
["spec_id"] = 0,
["zone"] = "Dornogal",
["ilvl_equipped"] = 0,
},
["wallet"] = {
["updated_at"] = 1778494582,
["copper"] = 0,
["partial"] = false,
},
},
["Player-3674-09C5872B"] = {
["meta"] = {
["guid"] = "Player-3674-09C5872B",
["subzone"] = "Murder Row",
["class"] = "DEMONHUNTER",
["race"] = "Blood Elf",
["level"] = 88,
["class_localized"] = "Demon Hunter",
["realm"] = "Twisting Nether",
["ilvl_overall"] = 0,
["race_id"] = 10,
["spec_index"] = 1,
["updated_at"] = 1778494538,
["name"] = "Auvendil",
["server_time"] = "2026-05-11 13:15:38",
["faction"] = "Horde",
["gender_id"] = 2,
["zone"] = "Silvermoon City",
["spec_id"] = 0,
["ilvl_equipped"] = 0,
},
["wallet"] = {
["partial"] = false,
["copper"] = 0,
["updated_at"] = 1778494538,
},
},
},
["schema_version"] = 5,
["addon_folder"] = "AzerothDataCollector_Meta",
["last_saved_at"] = 0,
}
