
AzerothDataCollector_MountsDB = {
["module_key"] = "mounts",
["by_character"] = {
["Player-3674-0BB3F0D1"] = {
["collections_mounts"] = {
["updated_at"] = 1778448408,
["partial"] = false,
["records"] = {
{
["id"] = 17,
["source_type"] = false,
["name"] = "Felsteed",
["spell_id"] = 5784,
},
{
["id"] = 18,
["source_type"] = false,
["name"] = "Chestnut Mare",
["spell_id"] = 6648,
},
{
["id"] = 19,
["source_type"] = true,
["name"] = "Dire Wolf",
["spell_id"] = 6653,
},
{
["id"] = 26,
["source_type"] = false,
["name"] = "Striped Frostsaber",
["spell_id"] = 8394,
},
{
["id"] = 41,
["source_type"] = false,
["name"] = "Warhorse",
["spell_id"] = 13819,
},
{
["id"] = 83,
["source_type"] = false,
["name"] = "Dreadsteed",
["spell_id"] = 23161,
},
{
["id"] = 84,
["source_type"] = false,
["name"] = "Charger",
["spell_id"] = 23214,
},
{
["id"] = 117,
["source_type"] = false,
["name"] = "Blue Qiraji Battle Tank",
["spell_id"] = 25953,
},
{
["id"] = 119,
["source_type"] = false,
["name"] = "Yellow Qiraji Battle Tank",
["spell_id"] = 26055,
},
{
["id"] = 120,
["source_type"] = false,
["name"] = "Green Qiraji Battle Tank",
["spell_id"] = 26056,
},
{
["id"] = 129,
["source_type"] = false,
["name"] = "Golden Gryphon",
["spell_id"] = 32235,
},
{
["id"] = 130,
["source_type"] = false,
["name"] = "Ebon Gryphon",
["spell_id"] = 32239,
},
{
["id"] = 131,
["source_type"] = false,
["name"] = "Snowy Gryphon",
["spell_id"] = 32240,
},
{
["id"] = 132,
["source_type"] = false,
["name"] = "Swift Blue Gryphon",
["spell_id"] = 32242,
},
{
["id"] = 133,
["source_type"] = true,
["name"] = "Tawny Wind Rider",
["spell_id"] = 32243,
},
{
["id"] = 134,
["source_type"] = true,
["name"] = "Blue Wind Rider",
["spell_id"] = 32244,
},
{
["id"] = 135,
["source_type"] = true,
["name"] = "Green Wind Rider",
["spell_id"] = 32245,
},
{
["id"] = 136,
["source_type"] = true,
["name"] = "Swift Red Wind Rider",
["spell_id"] = 32246,
},
{
["id"] = 137,
["source_type"] = false,
["name"] = "Swift Red Gryphon",
["spell_id"] = 32289,
},
{
["id"] = 138,
["source_type"] = false,
["name"] = "Swift Green Gryphon",
["spell_id"] = 32290,
},
{
["id"] = 139,
["source_type"] = false,
["name"] = "Swift Purple Gryphon",
["spell_id"] = 32292,
},
{
["id"] = 140,
["source_type"] = true,
["name"] = "Swift Green Wind Rider",
["spell_id"] = 32295,
},
{
["id"] = 141,
["source_type"] = true,
["name"] = "Swift Yellow Wind Rider",
["spell_id"] = 32296,
},
{
["id"] = 142,
["source_type"] = true,
["name"] = "Swift Purple Wind Rider",
["spell_id"] = 32297,
},
{
["id"] = 149,
["source_type"] = false,
["name"] = "Thalassian Charger",
["spell_id"] = 34767,
},
{
["id"] = 150,
["source_type"] = false,
["name"] = "Thalassian Warhorse",
["spell_id"] = 34769,
},
{
["id"] = 213,
["source_type"] = true,
["name"] = "Swift White Hawkstrider",
["spell_id"] = 46628,
},
{
["id"] = 221,
["source_type"] = false,
["name"] = "Acherus Deathcharger",
["spell_id"] = 48778,
},
{
["id"] = 224,
["source_type"] = true,
["name"] = "Swift Zhevra",
["spell_id"] = 49322,
},
{
["id"] = 248,
["source_type"] = true,
["name"] = "Bronze Drake",
["spell_id"] = 59569,
},
{
["id"] = 268,
["source_type"] = true,
["name"] = "Albino Drake",
["spell_id"] = 60025,
},
{
["id"] = 269,
["source_type"] = false,
["name"] = "Armored Brown Bear",
["spell_id"] = 60114,
},
{
["id"] = 270,
["source_type"] = true,
["name"] = "Armored Brown Bear",
["spell_id"] = 60116,
},
{
["id"] = 280,
["source_type"] = false,
["name"] = "Traveler's Tundra Mammoth",
["spell_id"] = 61425,
},
{
["id"] = 284,
["source_type"] = true,
["name"] = "Traveler's Tundra Mammoth",
["spell_id"] = 61447,
},
{
["id"] = 285,
["source_type"] = false,
["name"] = "Flying Carpet",
["spell_id"] = 61451,
},
{
["id"] = 291,
["source_type"] = false,
["name"] = "Blue Dragonhawk",
["spell_id"] = 61996,
},
{
["id"] = 292,
["source_type"] = true,
["name"] = "Red Dragonhawk",
["spell_id"] = 61997,
},
{
["id"] = 306,
["source_type"] = true,
["name"] = "Ironbound Proto-Drake",
["spell_id"] = 63956,
},
{
["id"] = 307,
["source_type"] = true,
["name"] = "Rusted Proto-Drake",
["spell_id"] = 63963,
},
{
["id"] = 314,
["source_type"] = true,
["name"] = "Black Skeletal Horse",
["spell_id"] = 64977,
},
{
["id"] = 364,
["source_type"] = true,
["name"] = "Icebound Frostbrood Vanquisher",
["spell_id"] = 72807,
},
{
["id"] = 367,
["source_type"] = false,
["name"] = "Exarch's Elekk",
["spell_id"] = 73629,
},
{
["id"] = 368,
["source_type"] = false,
["name"] = "Great Exarch's Elekk",
["spell_id"] = 73630,
},
{
["id"] = 376,
["source_type"] = true,
["name"] = "Celestial Steed",
["spell_id"] = 75614,
},
{
["id"] = 396,
["source_type"] = true,
["name"] = "Drake of the South Wind",
["spell_id"] = 88744,
},
{
["id"] = 403,
["source_type"] = false,
["name"] = "Golden King",
["spell_id"] = 90621,
},
{
["id"] = 407,
["source_type"] = true,
["name"] = "Sandstone Drake",
["spell_id"] = 93326,
},
{
["id"] = 409,
["source_type"] = true,
["name"] = "Kor'kron Annihilator",
["spell_id"] = 93644,
},
{
["id"] = 417,
["source_type"] = true,
["name"] = "Corrupted Fire Hawk",
["spell_id"] = 97560,
},
{
["id"] = 454,
["source_type"] = true,
["name"] = "Cindermane Charger",
["spell_id"] = 171847,
},
{
["id"] = 473,
["source_type"] = true,
["name"] = "Heavenly Onyx Cloud Serpent",
["spell_id"] = 127158,
},
{
["id"] = 478,
["source_type"] = true,
["name"] = "Astral Cloud Serpent",
["spell_id"] = 127170,
},
{
["id"] = 521,
["source_type"] = true,
["name"] = "Jade Pandaren Kite",
["spell_id"] = 133023,
},
{
["id"] = 522,
["source_type"] = true,
["name"] = "Sky Golem",
["spell_id"] = 134359,
},
{
["id"] = 547,
["source_type"] = true,
["name"] = "Hearthsteed",
["spell_id"] = 142073,
},
{
["id"] = 552,
["source_type"] = true,
["name"] = "Ironbound Wraithcharger",
["spell_id"] = 142910,
},
{
["id"] = 561,
["source_type"] = true,
["name"] = "Thundering Onyx Cloud Serpent",
["spell_id"] = 148476,
},
{
["id"] = 657,
["source_type"] = true,
["name"] = "Garn Nighthowl",
["spell_id"] = 171851,
},
{
["id"] = 678,
["source_type"] = true,
["name"] = "Chauffeured Mechano-Hog",
["spell_id"] = 179244,
},
{
["id"] = 679,
["source_type"] = false,
["name"] = "Chauffeured Mekgineer's Chopper",
["spell_id"] = 179245,
},
{
["id"] = 762,
["source_type"] = true,
["name"] = "Coalfist Gronnling",
["spell_id"] = 189364,
},
{
["id"] = 773,
["source_type"] = true,
["name"] = "Grove Defiler",
["spell_id"] = 193007,
},
{
["id"] = 780,
["source_type"] = false,
["name"] = "Felsaber",
["spell_id"] = 200175,
},
{
["id"] = 797,
["source_type"] = true,
["name"] = "Steelbound Devourer",
["spell_id"] = 213209,
},
{
["id"] = 826,
["source_type"] = true,
["name"] = "Prestigious Bronze Courser",
["spell_id"] = 222202,
},
{
["id"] = 833,
["source_type"] = true,
["name"] = "Prestigious Ivory Courser",
["spell_id"] = 222238,
},
{
["id"] = 868,
["source_type"] = false,
["name"] = "Slayer's Felbroken Shrieker",
["spell_id"] = 229417,
},
{
["id"] = 883,
["source_type"] = true,
["name"] = "Smoldering Ember Wyrm",
["spell_id"] = 231428,
},
{
["id"] = 947,
["source_type"] = true,
["name"] = "Riddler's Mind-Worm",
["spell_id"] = 243025,
},
{
["id"] = 961,
["source_type"] = true,
["name"] = "Lucid Nightmare",
["spell_id"] = 247402,
},
{
["id"] = 964,
["source_type"] = true,
["name"] = "Amethyst Ruinstrider",
["spell_id"] = 253004,
},
{
["id"] = 966,
["source_type"] = true,
["name"] = "Beryl Ruinstrider",
["spell_id"] = 253005,
},
{
["id"] = 993,
["source_type"] = true,
["name"] = "Squawks",
["spell_id"] = 254811,
},
{
["id"] = 996,
["source_type"] = false,
["name"] = "Seabraid Stallion",
["spell_id"] = 255695,
},
{
["id"] = 997,
["source_type"] = true,
["name"] = "Gilded Ravasaur",
["spell_id"] = 255696,
},
{
["id"] = 1006,
["source_type"] = false,
["name"] = "Lightforged Felcrusher",
["spell_id"] = 258022,
},
{
["id"] = 1008,
["source_type"] = true,
["name"] = "Nightborne Manasaber",
["spell_id"] = 258845,
},
{
["id"] = 1009,
["source_type"] = false,
["name"] = "Starcursed Voidstrider",
["spell_id"] = 259202,
},
{
["id"] = 1038,
["source_type"] = true,
["name"] = "Zandalari Direhorn",
["spell_id"] = 263707,
},
{
["id"] = 1044,
["source_type"] = true,
["name"] = "Mag'har Direwolf",
["spell_id"] = 267274,
},
{
["id"] = 1169,
["source_type"] = false,
["name"] = "Surf Jelly",
["spell_id"] = 278979,
},
{
["id"] = 1175,
["source_type"] = true,
["name"] = "Twilight Avenger",
["spell_id"] = 279466,
},
{
["id"] = 1176,
["source_type"] = true,
["name"] = "Craghorn Chasm-Leaper",
["spell_id"] = 279467,
},
{
["id"] = 1178,
["source_type"] = true,
["name"] = "Qinsho's Eternal Hound",
["spell_id"] = 279469,
},
{
["id"] = 1194,
["source_type"] = false,
["name"] = "Vicious White Warsaber",
["spell_id"] = 281888,
},
{
["id"] = 1195,
["source_type"] = false,
["name"] = "Vicious Black Warsaber",
["spell_id"] = 281887,
},
{
["id"] = 1196,
["source_type"] = true,
["name"] = "Vicious Black Bonesteed",
["spell_id"] = 281890,
},
{
["id"] = 1197,
["source_type"] = true,
["name"] = "Vicious White Bonesteed",
["spell_id"] = 281889,
},
{
["id"] = 1204,
["source_type"] = true,
["name"] = "Sandy Nightsaber",
["spell_id"] = 288506,
},
{
["id"] = 1209,
["source_type"] = true,
["name"] = "Stonehide Elderhorn",
["spell_id"] = 288712,
},
{
["id"] = 1211,
["source_type"] = true,
["name"] = "Bloodgorged Hunter",
["spell_id"] = 288720,
},
{
["id"] = 1212,
["source_type"] = true,
["name"] = "Island Thunderscale",
["spell_id"] = 288721,
},
{
["id"] = 1213,
["source_type"] = true,
["name"] = "Risen Mare",
["spell_id"] = 288722,
},
{
["id"] = 1218,
["source_type"] = true,
["name"] = "Dazar'alor Windreaver",
["spell_id"] = 289101,
},
{
["id"] = 1219,
["source_type"] = true,
["name"] = "Glacial Tidestorm",
["spell_id"] = 289555,
},
{
["id"] = 1224,
["source_type"] = true,
["name"] = "Wonderwing 2.0",
["spell_id"] = 290328,
},
{
["id"] = 1239,
["source_type"] = true,
["name"] = "X-995 Mechanocat",
["spell_id"] = 294143,
},
{
["id"] = 1265,
["source_type"] = true,
["name"] = "Uncorrupted Voidwing",
["spell_id"] = 302143,
},
{
["id"] = 1282,
["source_type"] = true,
["name"] = "Black Serpent of N'Zoth",
["spell_id"] = 305182,
},
{
["id"] = 1286,
["source_type"] = true,
["name"] = "Caravan Hyena",
["spell_id"] = 306423,
},
{
["id"] = 1289,
["source_type"] = true,
["name"] = "Ensorcelled Everwyrm",
["spell_id"] = 307932,
},
{
["id"] = 1299,
["source_type"] = true,
["name"] = "Battle Gargon Vrednic",
["spell_id"] = 312754,
},
{
["id"] = 1302,
["source_type"] = true,
["name"] = "Dreamlight Runestag",
["spell_id"] = 312759,
},
{
["id"] = 1303,
["source_type"] = true,
["name"] = "Enchanted Dreamlight Runestag",
["spell_id"] = 312761,
},
{
["id"] = 1305,
["source_type"] = true,
["name"] = "Darkwarren Hardshell",
["spell_id"] = 312763,
},
{
["id"] = 1309,
["source_type"] = true,
["name"] = "Chittering Animite",
["spell_id"] = 312776,
},
{
["id"] = 1310,
["source_type"] = true,
["name"] = "Horrid Dredwing",
["spell_id"] = 332882,
},
{
["id"] = 1311,
["source_type"] = true,
["name"] = "Ivory Cloud Serpent",
["spell_id"] = 315014,
},
{
["id"] = 1313,
["source_type"] = true,
["name"] = "Rajani Warserpent",
["spell_id"] = 315427,
},
{
["id"] = 1326,
["source_type"] = true,
["name"] = "Awakened Mindborer",
["spell_id"] = 316637,
},
{
["id"] = 1357,
["source_type"] = true,
["name"] = "Enchanted Shadeleaf Runestag",
["spell_id"] = 332246,
},
{
["id"] = 1364,
["source_type"] = false,
["name"] = "War-Bred Tauralus",
["spell_id"] = 332455,
},
{
["id"] = 1369,
["source_type"] = false,
["name"] = "Armored Plaguerot Tauralus",
["spell_id"] = 332464,
},
{
["id"] = 1384,
["source_type"] = true,
["name"] = "Sinfall Gargon",
["spell_id"] = 332927,
},
{
["id"] = 1385,
["source_type"] = true,
["name"] = "Crypt Gargon",
["spell_id"] = 332932,
},
{
["id"] = 1388,
["source_type"] = true,
["name"] = "Gravestone Battle Gargon",
["spell_id"] = 333021,
},
{
["id"] = 1399,
["source_type"] = false,
["name"] = "Eternal Phalynx of Purity",
["spell_id"] = 334403,
},
{
["id"] = 1414,
["source_type"] = true,
["name"] = "Sinrunner Blanchy",
["spell_id"] = 339588,
},
{
["id"] = 1419,
["source_type"] = true,
["name"] = "Sintouched Deathwalker",
["spell_id"] = 340068,
},
{
["id"] = 1421,
["source_type"] = true,
["name"] = "Court Sinrunner",
["spell_id"] = 341639,
},
{
["id"] = 1422,
["source_type"] = true,
["name"] = "Warstitched Darkhound",
["spell_id"] = 341766,
},
{
["id"] = 1423,
["source_type"] = true,
["name"] = "Highwind Darkmane",
["spell_id"] = 341776,
},
{
["id"] = 1428,
["source_type"] = true,
["name"] = "Amber Ardenmoth",
["spell_id"] = 342666,
},
{
["id"] = 1434,
["source_type"] = true,
["name"] = "Deepstar Aurelid",
["spell_id"] = 342680,
},
{
["id"] = 1439,
["source_type"] = true,
["name"] = "Infested Necroray",
["spell_id"] = 344576,
},
{
["id"] = 1458,
["source_type"] = true,
["name"] = "Wandering Ancient",
["spell_id"] = 348162,
},
{
["id"] = 1459,
["source_type"] = true,
["name"] = "Vicious War Gorm",
["spell_id"] = 348769,
},
{
["id"] = 1460,
["source_type"] = false,
["name"] = "Vicious War Gorm",
["spell_id"] = 348770,
},
{
["id"] = 1476,
["source_type"] = true,
["name"] = "Wild Hunt Legsplitter",
["spell_id"] = 352441,
},
{
["id"] = 1477,
["source_type"] = true,
["name"] = "Undying Darkhound",
["spell_id"] = 352742,
},
{
["id"] = 1484,
["source_type"] = true,
["name"] = "Ardenweald Wilderling",
["spell_id"] = 353856,
},
{
["id"] = 1487,
["source_type"] = true,
["name"] = "Summer Wilderling",
["spell_id"] = 353859,
},
{
["id"] = 1489,
["source_type"] = true,
["name"] = "Obsidian Gravewing",
["spell_id"] = 353866,
},
{
["id"] = 1490,
["source_type"] = true,
["name"] = "Sinfall Gravewing",
["spell_id"] = 353872,
},
{
["id"] = 1495,
["source_type"] = false,
["name"] = "Maldraxxian Corpsefly",
["spell_id"] = 353883,
},
{
["id"] = 1508,
["source_type"] = true,
["name"] = "Fierce Razorwing",
["spell_id"] = 354359,
},
{
["id"] = 1509,
["source_type"] = true,
["name"] = "Garnet Razorwing",
["spell_id"] = 354360,
},
{
["id"] = 1511,
["source_type"] = true,
["name"] = "Maelie, the Wanderer",
["spell_id"] = 354362,
},
{
["id"] = 1514,
["source_type"] = true,
["name"] = "Rampaging Mauler",
["spell_id"] = 356501,
},
{
["id"] = 1526,
["source_type"] = true,
["name"] = "Deathrunner",
["spell_id"] = 359278,
},
{
["id"] = 1529,
["source_type"] = true,
["name"] = "Anointed Protostag",
["spell_id"] = 359276,
},
{
["id"] = 1544,
["source_type"] = true,
["name"] = "Wastewarped Deathwalker",
["spell_id"] = 359407,
},
{
["id"] = 1550,
["source_type"] = true,
["name"] = "Depthstalker",
["spell_id"] = 359380,
},
{
["id"] = 1556,
["source_type"] = true,
["name"] = "Tangled Dreamweaver",
["spell_id"] = 359843,
},
{
["id"] = 1563,
["source_type"] = true,
["name"] = "Highland Drake",
["spell_id"] = 360954,
},
{
["id"] = 1568,
["source_type"] = false,
["name"] = "Lightforged Ruinstrider",
["spell_id"] = 363613,
},
{
["id"] = 1569,
["source_type"] = true,
["name"] = "Patient Bufonid",
["spell_id"] = 363701,
},
{
["id"] = 1576,
["source_type"] = true,
["name"] = "Jigglesworth Sr.",
["spell_id"] = 366791,
},
{
["id"] = 1577,
["source_type"] = true,
["name"] = "Ash'adar, Harbinger of Dawn",
["spell_id"] = 366962,
},
{
["id"] = 1580,
["source_type"] = true,
["name"] = "Heartbond Lupine",
["spell_id"] = 367673,
},
{
["id"] = 1585,
["source_type"] = true,
["name"] = "Colossal Wraithbound Mawrat",
["spell_id"] = 368128,
},
{
["id"] = 1588,
["source_type"] = true,
["name"] = "Winding Slitherdrake",
["spell_id"] = 368893,
},
{
["id"] = 1589,
["source_type"] = true,
["name"] = "Renewed Proto-Drake",
["spell_id"] = 368896,
},
{
["id"] = 1590,
["source_type"] = true,
["name"] = "Windborne Velocidrake",
["spell_id"] = 368899,
},
{
["id"] = 1591,
["source_type"] = true,
["name"] = "Cliffside Wylderdrake",
["spell_id"] = 368901,
},
{
["id"] = 1596,
["source_type"] = true,
["name"] = "Amalgam of Rage",
["spell_id"] = 369476,
},
{
["id"] = 1603,
["source_type"] = true,
["name"] = "Subterranean Magmammoth",
["spell_id"] = 371176,
},
{
["id"] = 1664,
["source_type"] = true,
["name"] = "Guardian Vorquin",
["spell_id"] = 384963,
},
{
["id"] = 1665,
["source_type"] = true,
["name"] = "Swift Armored Vorquin",
["spell_id"] = 385134,
},
{
["id"] = 1667,
["source_type"] = true,
["name"] = "Armored Vorquin Leystrider",
["spell_id"] = 385131,
},
{
["id"] = 1668,
["source_type"] = true,
["name"] = "Majestic Armored Vorquin",
["spell_id"] = 385115,
},
{
["id"] = 1671,
["source_type"] = true,
["name"] = "Duskwing Ohuna",
["spell_id"] = 385262,
},
{
["id"] = 1683,
["source_type"] = true,
["name"] = "Crimson Vorquin",
["spell_id"] = 394216,
},
{
["id"] = 1684,
["source_type"] = true,
["name"] = "Sapphire Vorquin",
["spell_id"] = 394218,
},
{
["id"] = 1685,
["source_type"] = true,
["name"] = "Bronze Vorquin",
["spell_id"] = 394219,
},
{
["id"] = 1686,
["source_type"] = true,
["name"] = "Obsidian Vorquin",
["spell_id"] = 394220,
},
{
["id"] = 1735,
["source_type"] = true,
["name"] = "Cataloged Shalewing",
["spell_id"] = 408651,
},
{
["id"] = 1772,
["source_type"] = true,
["name"] = "Scarlet Pterrordax",
["spell_id"] = 413825,
},
{
["id"] = 1779,
["source_type"] = true,
["name"] = "Felstorm Dragon",
["spell_id"] = 414326,
},
{
["id"] = 1792,
["source_type"] = true,
["name"] = "Algarian Stormrider",
["spell_id"] = 417888,
},
{
["id"] = 1798,
["source_type"] = true,
["name"] = "Azure Worldchiller",
["spell_id"] = 420097,
},
{
["id"] = 1808,
["source_type"] = true,
["name"] = "Blossoming Dreamstag",
["spell_id"] = 423871,
},
{
["id"] = 1809,
["source_type"] = true,
["name"] = "Suntouched Dreamstag",
["spell_id"] = 423873,
},
{
["id"] = 1810,
["source_type"] = true,
["name"] = "Rekindled Dreamstag",
["spell_id"] = 423877,
},
{
["id"] = 1812,
["source_type"] = true,
["name"] = "Runebound Firelord",
["spell_id"] = 424009,
},
{
["id"] = 1815,
["source_type"] = true,
["name"] = "Winter Night Dreamsaber",
["spell_id"] = 424476,
},
{
["id"] = 1816,
["source_type"] = true,
["name"] = "Evening Sun Dreamsaber",
["spell_id"] = 424479,
},
{
["id"] = 1817,
["source_type"] = true,
["name"] = "Morning Flourish Dreamsaber",
["spell_id"] = 424482,
},
{
["id"] = 1824,
["source_type"] = true,
["name"] = "Brown-Furred Spiky Bakar",
["spell_id"] = 424601,
},
{
["id"] = 1830,
["source_type"] = true,
["name"] = "Flourishing Whimsydrake",
["spell_id"] = 425338,
},
{
["id"] = 1839,
["source_type"] = true,
["name"] = "Stargrazer",
["spell_id"] = 427226,
},
{
["id"] = 1938,
["source_type"] = true,
["name"] = "Mammyth",
["spell_id"] = 427546,
},
{
["id"] = 2038,
["source_type"] = true,
["name"] = "Clayscale Hornstrider",
["spell_id"] = 432610,
},
{
["id"] = 2055,
["source_type"] = true,
["name"] = "Infinite Armoredon",
["spell_id"] = 434462,
},
{
["id"] = 2064,
["source_type"] = true,
["name"] = "Sky Surfer",
["spell_id"] = 435084,
},
{
["id"] = 2091,
["source_type"] = true,
["name"] = "Voyaging Wilderling",
["spell_id"] = 439138,
},
{
["id"] = 2142,
["source_type"] = true,
["name"] = "August Phoenix",
["spell_id"] = 446017,
},
{
["id"] = 2144,
["source_type"] = true,
["name"] = "Delver's Dirigible",
["spell_id"] = 446052,
},
{
["id"] = 2152,
["source_type"] = true,
["name"] = "Pearlescent Goblin Wave Shredder",
["spell_id"] = 447413,
},
{
["id"] = 2192,
["source_type"] = true,
["name"] = "Beledar's Spawn",
["spell_id"] = 448941,
},
{
["id"] = 2194,
["source_type"] = true,
["name"] = "Dauntless Imperial Lynx",
["spell_id"] = 448979,
},
{
["id"] = 2201,
["source_type"] = true,
["name"] = "Sentinel War Wolf",
["spell_id"] = 449140,
},
{
["id"] = 2214,
["source_type"] = true,
["name"] = "Slatestone Ramolith",
["spell_id"] = 449415,
},
{
["id"] = 2219,
["source_type"] = true,
["name"] = "Sureki Skyrazor",
["spell_id"] = 451486,
},
{
["id"] = 2237,
["source_type"] = true,
["name"] = "Grizzly Hills Packmaster",
["spell_id"] = 457485,
},
{
["id"] = 2238,
["source_type"] = true,
["name"] = "Plunderlord's Golden Crocolisk",
["spell_id"] = 457650,
},
{
["id"] = 2244,
["source_type"] = true,
["name"] = "Diamond Mechsuit",
["spell_id"] = 458335,
},
{
["id"] = 2616,
["source_type"] = true,
["name"] = "Ivory Grimlynx",
["spell_id"] = 1243598,
},
{
["id"] = 2785,
["source_type"] = true,
["name"] = "Relinquished Scarlet Charger",
["spell_id"] = 1261391,
},
},
},
},
["Player-3674-09C5872B"] = {
["collections_mounts"] = {
["updated_at"] = 1778449753,
["records"] = {
{
["id"] = 17,
["source_type"] = false,
["name"] = "Felsteed",
["spell_id"] = 5784,
},
{
["id"] = 18,
["source_type"] = false,
["name"] = "Chestnut Mare",
["spell_id"] = 6648,
},
{
["id"] = 19,
["source_type"] = true,
["name"] = "Dire Wolf",
["spell_id"] = 6653,
},
{
["id"] = 26,
["source_type"] = false,
["name"] = "Striped Frostsaber",
["spell_id"] = 8394,
},
{
["id"] = 41,
["source_type"] = false,
["name"] = "Warhorse",
["spell_id"] = 13819,
},
{
["id"] = 83,
["source_type"] = false,
["name"] = "Dreadsteed",
["spell_id"] = 23161,
},
{
["id"] = 84,
["source_type"] = false,
["name"] = "Charger",
["spell_id"] = 23214,
},
{
["id"] = 117,
["source_type"] = false,
["name"] = "Blue Qiraji Battle Tank",
["spell_id"] = 25953,
},
{
["id"] = 119,
["source_type"] = false,
["name"] = "Yellow Qiraji Battle Tank",
["spell_id"] = 26055,
},
{
["id"] = 120,
["source_type"] = false,
["name"] = "Green Qiraji Battle Tank",
["spell_id"] = 26056,
},
{
["id"] = 129,
["source_type"] = false,
["name"] = "Golden Gryphon",
["spell_id"] = 32235,
},
{
["id"] = 130,
["source_type"] = false,
["name"] = "Ebon Gryphon",
["spell_id"] = 32239,
},
{
["id"] = 131,
["source_type"] = false,
["name"] = "Snowy Gryphon",
["spell_id"] = 32240,
},
{
["id"] = 132,
["source_type"] = false,
["name"] = "Swift Blue Gryphon",
["spell_id"] = 32242,
},
{
["id"] = 133,
["source_type"] = true,
["name"] = "Tawny Wind Rider",
["spell_id"] = 32243,
},
{
["id"] = 134,
["source_type"] = true,
["name"] = "Blue Wind Rider",
["spell_id"] = 32244,
},
{
["id"] = 135,
["source_type"] = true,
["name"] = "Green Wind Rider",
["spell_id"] = 32245,
},
{
["id"] = 136,
["source_type"] = true,
["name"] = "Swift Red Wind Rider",
["spell_id"] = 32246,
},
{
["id"] = 137,
["source_type"] = false,
["name"] = "Swift Red Gryphon",
["spell_id"] = 32289,
},
{
["id"] = 138,
["source_type"] = false,
["name"] = "Swift Green Gryphon",
["spell_id"] = 32290,
},
{
["id"] = 139,
["source_type"] = false,
["name"] = "Swift Purple Gryphon",
["spell_id"] = 32292,
},
{
["id"] = 140,
["source_type"] = true,
["name"] = "Swift Green Wind Rider",
["spell_id"] = 32295,
},
{
["id"] = 141,
["source_type"] = true,
["name"] = "Swift Yellow Wind Rider",
["spell_id"] = 32296,
},
{
["id"] = 142,
["source_type"] = true,
["name"] = "Swift Purple Wind Rider",
["spell_id"] = 32297,
},
{
["id"] = 149,
["source_type"] = false,
["name"] = "Thalassian Charger",
["spell_id"] = 34767,
},
{
["id"] = 150,
["source_type"] = false,
["name"] = "Thalassian Warhorse",
["spell_id"] = 34769,
},
{
["id"] = 213,
["source_type"] = true,
["name"] = "Swift White Hawkstrider",
["spell_id"] = 46628,
},
{
["id"] = 221,
["source_type"] = false,
["name"] = "Acherus Deathcharger",
["spell_id"] = 48778,
},
{
["id"] = 224,
["source_type"] = true,
["name"] = "Swift Zhevra",
["spell_id"] = 49322,
},
{
["id"] = 248,
["source_type"] = true,
["name"] = "Bronze Drake",
["spell_id"] = 59569,
},
{
["id"] = 268,
["source_type"] = true,
["name"] = "Albino Drake",
["spell_id"] = 60025,
},
{
["id"] = 269,
["source_type"] = false,
["name"] = "Armored Brown Bear",
["spell_id"] = 60114,
},
{
["id"] = 270,
["source_type"] = true,
["name"] = "Armored Brown Bear",
["spell_id"] = 60116,
},
{
["id"] = 280,
["source_type"] = false,
["name"] = "Traveler's Tundra Mammoth",
["spell_id"] = 61425,
},
{
["id"] = 284,
["source_type"] = true,
["name"] = "Traveler's Tundra Mammoth",
["spell_id"] = 61447,
},
{
["id"] = 285,
["source_type"] = false,
["name"] = "Flying Carpet",
["spell_id"] = 61451,
},
{
["id"] = 291,
["source_type"] = false,
["name"] = "Blue Dragonhawk",
["spell_id"] = 61996,
},
{
["id"] = 292,
["source_type"] = true,
["name"] = "Red Dragonhawk",
["spell_id"] = 61997,
},
{
["id"] = 306,
["source_type"] = true,
["name"] = "Ironbound Proto-Drake",
["spell_id"] = 63956,
},
{
["id"] = 307,
["source_type"] = true,
["name"] = "Rusted Proto-Drake",
["spell_id"] = 63963,
},
{
["id"] = 314,
["source_type"] = true,
["name"] = "Black Skeletal Horse",
["spell_id"] = 64977,
},
{
["id"] = 364,
["source_type"] = true,
["name"] = "Icebound Frostbrood Vanquisher",
["spell_id"] = 72807,
},
{
["id"] = 367,
["source_type"] = false,
["name"] = "Exarch's Elekk",
["spell_id"] = 73629,
},
{
["id"] = 368,
["source_type"] = false,
["name"] = "Great Exarch's Elekk",
["spell_id"] = 73630,
},
{
["id"] = 376,
["source_type"] = true,
["name"] = "Celestial Steed",
["spell_id"] = 75614,
},
{
["id"] = 396,
["source_type"] = true,
["name"] = "Drake of the South Wind",
["spell_id"] = 88744,
},
{
["id"] = 403,
["source_type"] = false,
["name"] = "Golden King",
["spell_id"] = 90621,
},
{
["id"] = 407,
["source_type"] = true,
["name"] = "Sandstone Drake",
["spell_id"] = 93326,
},
{
["id"] = 409,
["source_type"] = true,
["name"] = "Kor'kron Annihilator",
["spell_id"] = 93644,
},
{
["id"] = 417,
["source_type"] = true,
["name"] = "Corrupted Fire Hawk",
["spell_id"] = 97560,
},
{
["id"] = 454,
["source_type"] = true,
["name"] = "Cindermane Charger",
["spell_id"] = 171847,
},
{
["id"] = 473,
["source_type"] = true,
["name"] = "Heavenly Onyx Cloud Serpent",
["spell_id"] = 127158,
},
{
["id"] = 478,
["source_type"] = true,
["name"] = "Astral Cloud Serpent",
["spell_id"] = 127170,
},
{
["id"] = 521,
["source_type"] = true,
["name"] = "Jade Pandaren Kite",
["spell_id"] = 133023,
},
{
["id"] = 522,
["source_type"] = true,
["name"] = "Sky Golem",
["spell_id"] = 134359,
},
{
["id"] = 547,
["source_type"] = true,
["name"] = "Hearthsteed",
["spell_id"] = 142073,
},
{
["id"] = 552,
["source_type"] = true,
["name"] = "Ironbound Wraithcharger",
["spell_id"] = 142910,
},
{
["id"] = 561,
["source_type"] = true,
["name"] = "Thundering Onyx Cloud Serpent",
["spell_id"] = 148476,
},
{
["id"] = 657,
["source_type"] = true,
["name"] = "Garn Nighthowl",
["spell_id"] = 171851,
},
{
["id"] = 678,
["source_type"] = true,
["name"] = "Chauffeured Mechano-Hog",
["spell_id"] = 179244,
},
{
["id"] = 679,
["source_type"] = false,
["name"] = "Chauffeured Mekgineer's Chopper",
["spell_id"] = 179245,
},
{
["id"] = 762,
["source_type"] = true,
["name"] = "Coalfist Gronnling",
["spell_id"] = 189364,
},
{
["id"] = 773,
["source_type"] = true,
["name"] = "Grove Defiler",
["spell_id"] = 193007,
},
{
["id"] = 780,
["source_type"] = true,
["name"] = "Felsaber",
["spell_id"] = 200175,
},
{
["id"] = 797,
["source_type"] = true,
["name"] = "Steelbound Devourer",
["spell_id"] = 213209,
},
{
["id"] = 826,
["source_type"] = true,
["name"] = "Prestigious Bronze Courser",
["spell_id"] = 222202,
},
{
["id"] = 833,
["source_type"] = true,
["name"] = "Prestigious Ivory Courser",
["spell_id"] = 222238,
},
{
["id"] = 868,
["source_type"] = true,
["name"] = "Slayer's Felbroken Shrieker",
["spell_id"] = 229417,
},
{
["id"] = 883,
["source_type"] = true,
["name"] = "Smoldering Ember Wyrm",
["spell_id"] = 231428,
},
{
["id"] = 947,
["source_type"] = true,
["name"] = "Riddler's Mind-Worm",
["spell_id"] = 243025,
},
{
["id"] = 961,
["source_type"] = true,
["name"] = "Lucid Nightmare",
["spell_id"] = 247402,
},
{
["id"] = 964,
["source_type"] = true,
["name"] = "Amethyst Ruinstrider",
["spell_id"] = 253004,
},
{
["id"] = 966,
["source_type"] = true,
["name"] = "Beryl Ruinstrider",
["spell_id"] = 253005,
},
{
["id"] = 993,
["source_type"] = true,
["name"] = "Squawks",
["spell_id"] = 254811,
},
{
["id"] = 996,
["source_type"] = false,
["name"] = "Seabraid Stallion",
["spell_id"] = 255695,
},
{
["id"] = 997,
["source_type"] = true,
["name"] = "Gilded Ravasaur",
["spell_id"] = 255696,
},
{
["id"] = 1006,
["source_type"] = false,
["name"] = "Lightforged Felcrusher",
["spell_id"] = 258022,
},
{
["id"] = 1008,
["source_type"] = true,
["name"] = "Nightborne Manasaber",
["spell_id"] = 258845,
},
{
["id"] = 1009,
["source_type"] = false,
["name"] = "Starcursed Voidstrider",
["spell_id"] = 259202,
},
{
["id"] = 1038,
["source_type"] = true,
["name"] = "Zandalari Direhorn",
["spell_id"] = 263707,
},
{
["id"] = 1044,
["source_type"] = true,
["name"] = "Mag'har Direwolf",
["spell_id"] = 267274,
},
{
["id"] = 1169,
["source_type"] = false,
["name"] = "Surf Jelly",
["spell_id"] = 278979,
},
{
["id"] = 1175,
["source_type"] = true,
["name"] = "Twilight Avenger",
["spell_id"] = 279466,
},
{
["id"] = 1176,
["source_type"] = true,
["name"] = "Craghorn Chasm-Leaper",
["spell_id"] = 279467,
},
{
["id"] = 1178,
["source_type"] = true,
["name"] = "Qinsho's Eternal Hound",
["spell_id"] = 279469,
},
{
["id"] = 1194,
["source_type"] = false,
["name"] = "Vicious White Warsaber",
["spell_id"] = 281888,
},
{
["id"] = 1195,
["source_type"] = false,
["name"] = "Vicious Black Warsaber",
["spell_id"] = 281887,
},
{
["id"] = 1196,
["source_type"] = true,
["name"] = "Vicious Black Bonesteed",
["spell_id"] = 281890,
},
{
["id"] = 1197,
["source_type"] = true,
["name"] = "Vicious White Bonesteed",
["spell_id"] = 281889,
},
{
["id"] = 1204,
["source_type"] = true,
["name"] = "Sandy Nightsaber",
["spell_id"] = 288506,
},
{
["id"] = 1209,
["source_type"] = true,
["name"] = "Stonehide Elderhorn",
["spell_id"] = 288712,
},
{
["id"] = 1211,
["source_type"] = true,
["name"] = "Bloodgorged Hunter",
["spell_id"] = 288720,
},
{
["id"] = 1212,
["source_type"] = true,
["name"] = "Island Thunderscale",
["spell_id"] = 288721,
},
{
["id"] = 1213,
["source_type"] = true,
["name"] = "Risen Mare",
["spell_id"] = 288722,
},
{
["id"] = 1218,
["source_type"] = true,
["name"] = "Dazar'alor Windreaver",
["spell_id"] = 289101,
},
{
["id"] = 1219,
["source_type"] = true,
["name"] = "Glacial Tidestorm",
["spell_id"] = 289555,
},
{
["id"] = 1224,
["source_type"] = true,
["name"] = "Wonderwing 2.0",
["spell_id"] = 290328,
},
{
["id"] = 1239,
["source_type"] = true,
["name"] = "X-995 Mechanocat",
["spell_id"] = 294143,
},
{
["id"] = 1265,
["source_type"] = true,
["name"] = "Uncorrupted Voidwing",
["spell_id"] = 302143,
},
{
["id"] = 1282,
["source_type"] = true,
["name"] = "Black Serpent of N'Zoth",
["spell_id"] = 305182,
},
{
["id"] = 1286,
["source_type"] = true,
["name"] = "Caravan Hyena",
["spell_id"] = 306423,
},
{
["id"] = 1289,
["source_type"] = true,
["name"] = "Ensorcelled Everwyrm",
["spell_id"] = 307932,
},
{
["id"] = 1299,
["source_type"] = true,
["name"] = "Battle Gargon Vrednic",
["spell_id"] = 312754,
},
{
["id"] = 1302,
["source_type"] = true,
["name"] = "Dreamlight Runestag",
["spell_id"] = 312759,
},
{
["id"] = 1303,
["source_type"] = true,
["name"] = "Enchanted Dreamlight Runestag",
["spell_id"] = 312761,
},
{
["id"] = 1305,
["source_type"] = true,
["name"] = "Darkwarren Hardshell",
["spell_id"] = 312763,
},
{
["id"] = 1309,
["source_type"] = true,
["name"] = "Chittering Animite",
["spell_id"] = 312776,
},
{
["id"] = 1310,
["source_type"] = true,
["name"] = "Horrid Dredwing",
["spell_id"] = 332882,
},
{
["id"] = 1311,
["source_type"] = true,
["name"] = "Ivory Cloud Serpent",
["spell_id"] = 315014,
},
{
["id"] = 1313,
["source_type"] = true,
["name"] = "Rajani Warserpent",
["spell_id"] = 315427,
},
{
["id"] = 1326,
["source_type"] = true,
["name"] = "Awakened Mindborer",
["spell_id"] = 316637,
},
{
["id"] = 1357,
["source_type"] = true,
["name"] = "Enchanted Shadeleaf Runestag",
["spell_id"] = 332246,
},
{
["id"] = 1364,
["source_type"] = false,
["name"] = "War-Bred Tauralus",
["spell_id"] = 332455,
},
{
["id"] = 1369,
["source_type"] = false,
["name"] = "Armored Plaguerot Tauralus",
["spell_id"] = 332464,
},
{
["id"] = 1384,
["source_type"] = true,
["name"] = "Sinfall Gargon",
["spell_id"] = 332927,
},
{
["id"] = 1385,
["source_type"] = true,
["name"] = "Crypt Gargon",
["spell_id"] = 332932,
},
{
["id"] = 1388,
["source_type"] = true,
["name"] = "Gravestone Battle Gargon",
["spell_id"] = 333021,
},
{
["id"] = 1399,
["source_type"] = false,
["name"] = "Eternal Phalynx of Purity",
["spell_id"] = 334403,
},
{
["id"] = 1414,
["source_type"] = true,
["name"] = "Sinrunner Blanchy",
["spell_id"] = 339588,
},
{
["id"] = 1419,
["source_type"] = true,
["name"] = "Sintouched Deathwalker",
["spell_id"] = 340068,
},
{
["id"] = 1421,
["source_type"] = true,
["name"] = "Court Sinrunner",
["spell_id"] = 341639,
},
{
["id"] = 1422,
["source_type"] = true,
["name"] = "Warstitched Darkhound",
["spell_id"] = 341766,
},
{
["id"] = 1423,
["source_type"] = true,
["name"] = "Highwind Darkmane",
["spell_id"] = 341776,
},
{
["id"] = 1428,
["source_type"] = true,
["name"] = "Amber Ardenmoth",
["spell_id"] = 342666,
},
{
["id"] = 1434,
["source_type"] = true,
["name"] = "Deepstar Aurelid",
["spell_id"] = 342680,
},
{
["id"] = 1439,
["source_type"] = true,
["name"] = "Infested Necroray",
["spell_id"] = 344576,
},
{
["id"] = 1458,
["source_type"] = true,
["name"] = "Wandering Ancient",
["spell_id"] = 348162,
},
{
["id"] = 1459,
["source_type"] = true,
["name"] = "Vicious War Gorm",
["spell_id"] = 348769,
},
{
["id"] = 1460,
["source_type"] = false,
["name"] = "Vicious War Gorm",
["spell_id"] = 348770,
},
{
["id"] = 1476,
["source_type"] = true,
["name"] = "Wild Hunt Legsplitter",
["spell_id"] = 352441,
},
{
["id"] = 1477,
["source_type"] = true,
["name"] = "Undying Darkhound",
["spell_id"] = 352742,
},
{
["id"] = 1484,
["source_type"] = true,
["name"] = "Ardenweald Wilderling",
["spell_id"] = 353856,
},
{
["id"] = 1487,
["source_type"] = true,
["name"] = "Summer Wilderling",
["spell_id"] = 353859,
},
{
["id"] = 1489,
["source_type"] = true,
["name"] = "Obsidian Gravewing",
["spell_id"] = 353866,
},
{
["id"] = 1490,
["source_type"] = true,
["name"] = "Sinfall Gravewing",
["spell_id"] = 353872,
},
{
["id"] = 1495,
["source_type"] = false,
["name"] = "Maldraxxian Corpsefly",
["spell_id"] = 353883,
},
{
["id"] = 1508,
["source_type"] = true,
["name"] = "Fierce Razorwing",
["spell_id"] = 354359,
},
{
["id"] = 1509,
["source_type"] = true,
["name"] = "Garnet Razorwing",
["spell_id"] = 354360,
},
{
["id"] = 1511,
["source_type"] = true,
["name"] = "Maelie, the Wanderer",
["spell_id"] = 354362,
},
{
["id"] = 1514,
["source_type"] = true,
["name"] = "Rampaging Mauler",
["spell_id"] = 356501,
},
{
["id"] = 1526,
["source_type"] = true,
["name"] = "Deathrunner",
["spell_id"] = 359278,
},
{
["id"] = 1529,
["source_type"] = true,
["name"] = "Anointed Protostag",
["spell_id"] = 359276,
},
{
["id"] = 1544,
["source_type"] = true,
["name"] = "Wastewarped Deathwalker",
["spell_id"] = 359407,
},
{
["id"] = 1550,
["source_type"] = true,
["name"] = "Depthstalker",
["spell_id"] = 359380,
},
{
["id"] = 1556,
["source_type"] = true,
["name"] = "Tangled Dreamweaver",
["spell_id"] = 359843,
},
{
["id"] = 1563,
["source_type"] = true,
["name"] = "Highland Drake",
["spell_id"] = 360954,
},
{
["id"] = 1568,
["source_type"] = false,
["name"] = "Lightforged Ruinstrider",
["spell_id"] = 363613,
},
{
["id"] = 1569,
["source_type"] = true,
["name"] = "Patient Bufonid",
["spell_id"] = 363701,
},
{
["id"] = 1576,
["source_type"] = true,
["name"] = "Jigglesworth Sr.",
["spell_id"] = 366791,
},
{
["id"] = 1577,
["source_type"] = true,
["name"] = "Ash'adar, Harbinger of Dawn",
["spell_id"] = 366962,
},
{
["id"] = 1580,
["source_type"] = true,
["name"] = "Heartbond Lupine",
["spell_id"] = 367673,
},
{
["id"] = 1585,
["source_type"] = true,
["name"] = "Colossal Wraithbound Mawrat",
["spell_id"] = 368128,
},
{
["id"] = 1588,
["source_type"] = true,
["name"] = "Winding Slitherdrake",
["spell_id"] = 368893,
},
{
["id"] = 1589,
["source_type"] = true,
["name"] = "Renewed Proto-Drake",
["spell_id"] = 368896,
},
{
["id"] = 1590,
["source_type"] = true,
["name"] = "Windborne Velocidrake",
["spell_id"] = 368899,
},
{
["id"] = 1591,
["source_type"] = true,
["name"] = "Cliffside Wylderdrake",
["spell_id"] = 368901,
},
{
["id"] = 1596,
["source_type"] = true,
["name"] = "Amalgam of Rage",
["spell_id"] = 369476,
},
{
["id"] = 1603,
["source_type"] = true,
["name"] = "Subterranean Magmammoth",
["spell_id"] = 371176,
},
{
["id"] = 1664,
["source_type"] = true,
["name"] = "Guardian Vorquin",
["spell_id"] = 384963,
},
{
["id"] = 1665,
["source_type"] = true,
["name"] = "Swift Armored Vorquin",
["spell_id"] = 385134,
},
{
["id"] = 1667,
["source_type"] = true,
["name"] = "Armored Vorquin Leystrider",
["spell_id"] = 385131,
},
{
["id"] = 1668,
["source_type"] = true,
["name"] = "Majestic Armored Vorquin",
["spell_id"] = 385115,
},
{
["id"] = 1671,
["source_type"] = true,
["name"] = "Duskwing Ohuna",
["spell_id"] = 385262,
},
{
["id"] = 1683,
["source_type"] = true,
["name"] = "Crimson Vorquin",
["spell_id"] = 394216,
},
{
["id"] = 1684,
["source_type"] = true,
["name"] = "Sapphire Vorquin",
["spell_id"] = 394218,
},
{
["id"] = 1685,
["source_type"] = true,
["name"] = "Bronze Vorquin",
["spell_id"] = 394219,
},
{
["id"] = 1686,
["source_type"] = true,
["name"] = "Obsidian Vorquin",
["spell_id"] = 394220,
},
{
["id"] = 1735,
["source_type"] = true,
["name"] = "Cataloged Shalewing",
["spell_id"] = 408651,
},
{
["id"] = 1772,
["source_type"] = true,
["name"] = "Scarlet Pterrordax",
["spell_id"] = 413825,
},
{
["id"] = 1779,
["source_type"] = true,
["name"] = "Felstorm Dragon",
["spell_id"] = 414326,
},
{
["id"] = 1792,
["source_type"] = true,
["name"] = "Algarian Stormrider",
["spell_id"] = 417888,
},
{
["id"] = 1798,
["source_type"] = true,
["name"] = "Azure Worldchiller",
["spell_id"] = 420097,
},
{
["id"] = 1808,
["source_type"] = true,
["name"] = "Blossoming Dreamstag",
["spell_id"] = 423871,
},
{
["id"] = 1809,
["source_type"] = true,
["name"] = "Suntouched Dreamstag",
["spell_id"] = 423873,
},
{
["id"] = 1810,
["source_type"] = true,
["name"] = "Rekindled Dreamstag",
["spell_id"] = 423877,
},
{
["id"] = 1812,
["source_type"] = true,
["name"] = "Runebound Firelord",
["spell_id"] = 424009,
},
{
["id"] = 1815,
["source_type"] = true,
["name"] = "Winter Night Dreamsaber",
["spell_id"] = 424476,
},
{
["id"] = 1816,
["source_type"] = true,
["name"] = "Evening Sun Dreamsaber",
["spell_id"] = 424479,
},
{
["id"] = 1817,
["source_type"] = true,
["name"] = "Morning Flourish Dreamsaber",
["spell_id"] = 424482,
},
{
["id"] = 1824,
["source_type"] = true,
["name"] = "Brown-Furred Spiky Bakar",
["spell_id"] = 424601,
},
{
["id"] = 1830,
["source_type"] = true,
["name"] = "Flourishing Whimsydrake",
["spell_id"] = 425338,
},
{
["id"] = 1839,
["source_type"] = true,
["name"] = "Stargrazer",
["spell_id"] = 427226,
},
{
["id"] = 1938,
["source_type"] = true,
["name"] = "Mammyth",
["spell_id"] = 427546,
},
{
["id"] = 2038,
["source_type"] = true,
["name"] = "Clayscale Hornstrider",
["spell_id"] = 432610,
},
{
["id"] = 2055,
["source_type"] = true,
["name"] = "Infinite Armoredon",
["spell_id"] = 434462,
},
{
["id"] = 2064,
["source_type"] = true,
["name"] = "Sky Surfer",
["spell_id"] = 435084,
},
{
["id"] = 2091,
["source_type"] = true,
["name"] = "Voyaging Wilderling",
["spell_id"] = 439138,
},
{
["id"] = 2142,
["source_type"] = true,
["name"] = "August Phoenix",
["spell_id"] = 446017,
},
{
["id"] = 2144,
["source_type"] = true,
["name"] = "Delver's Dirigible",
["spell_id"] = 446052,
},
{
["id"] = 2152,
["source_type"] = true,
["name"] = "Pearlescent Goblin Wave Shredder",
["spell_id"] = 447413,
},
{
["id"] = 2192,
["source_type"] = true,
["name"] = "Beledar's Spawn",
["spell_id"] = 448941,
},
{
["id"] = 2194,
["source_type"] = true,
["name"] = "Dauntless Imperial Lynx",
["spell_id"] = 448979,
},
{
["id"] = 2201,
["source_type"] = true,
["name"] = "Sentinel War Wolf",
["spell_id"] = 449140,
},
{
["id"] = 2214,
["source_type"] = true,
["name"] = "Slatestone Ramolith",
["spell_id"] = 449415,
},
{
["id"] = 2219,
["source_type"] = true,
["name"] = "Sureki Skyrazor",
["spell_id"] = 451486,
},
{
["id"] = 2237,
["source_type"] = true,
["name"] = "Grizzly Hills Packmaster",
["spell_id"] = 457485,
},
{
["id"] = 2238,
["source_type"] = true,
["name"] = "Plunderlord's Golden Crocolisk",
["spell_id"] = 457650,
},
{
["id"] = 2244,
["source_type"] = true,
["name"] = "Diamond Mechsuit",
["spell_id"] = 458335,
},
{
["id"] = 2616,
["source_type"] = true,
["name"] = "Ivory Grimlynx",
["spell_id"] = 1243598,
},
{
["id"] = 2785,
["source_type"] = true,
["name"] = "Relinquished Scarlet Charger",
["spell_id"] = 1261391,
},
},
["partial"] = false,
},
},
},
["schema_version"] = 4,
["addon_folder"] = "AzerothDataCollector_Mounts",
["last_saved_at"] = 1778449753,
}
