
AzerothDataCollector_ContainersDB = {
["module_key"] = "containers",
["by_character"] = {
["Player-3674-09D241D0"] = {
["containers"] = {
["updated_at"] = 1778492006,
["partial"] = false,
["records"] = {
{
["id"] = -2,
["name"] = "_container_scan_meta",
["bank_ui_opened_at_least_once"] = false,
},
{
["container_kind"] = "character_bag",
["id"] = 6948,
["bag_id"] = 0,
["name"] = "Hearthstone",
["slot"] = 1,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:6948::::::::80:266::17:::::::|h[Hearthstone]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 71634,
["bag_id"] = 0,
["name"] = "Darkmoon Adventurer's Guide",
["slot"] = 2,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:71634::::::::80:266:::::::::|h[Darkmoon Adventurer's Guide]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 187421,
["bag_id"] = 0,
["name"] = "Ashen Liniment",
["slot"] = 3,
["item_level"] = 1,
["item_link"] = "|cnIQ3:|Hitem:187421::::::::80:266:::::::::|h[Ashen Liniment]|h|r",
["count"] = 20,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 208485,
["bag_id"] = 0,
["name"] = "The Scarlet Key",
["slot"] = 4,
["item_level"] = 1,
["item_link"] = "|cnIQ2:|Hitem:208485::::::::80:266:::::::::|h[The Scarlet Key]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 18229,
["bag_id"] = 0,
["name"] = "Nat Pagle's Guide to Extreme Anglin'",
["slot"] = 5,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:18229::::::::80:266:::::::::|h[Nat Pagle's Guide to Extreme Anglin']|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 223756,
["bag_id"] = 0,
["name"] = "Illusory Adornment: Shadow",
["slot"] = 6,
["item_level"] = 89,
["item_link"] = "|cnIQ3:|Hitem:223756::::::::80:266:::::::::|h[Illusory Adornment: Shadow |A:Professions-ChatIcon-Quality-Tier3:17:15::1|a]|h|r",
["count"] = 3,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 244513,
["bag_id"] = 1,
["name"] = "Worn Shadowguard Kris",
["slot"] = 1,
["item_level"] = 100,
["item_link"] = "|cnIQ3:|Hitem:244513::::::::80:266::136:5:12267:6652:10844:3178:10254:1:28:3008:::::|h[Worn Shadowguard Kris]|h|r",
["count"] = 1,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 15152,
["bag_id"] = 1,
["name"] = "Nocturnal Shoes of the Fireflash",
["slot"] = 2,
["item_level"] = 74,
["item_link"] = "|cnIQ2:|Hitem:15152::::::::80:266::22:2:6654:1691:2:9:80:28:2872:::::|h[Nocturnal Shoes of the Fireflash]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 217117,
["bag_id"] = 1,
["name"] = "Algari Competitor's Cloth Leggings",
["slot"] = 3,
["item_level"] = 88,
["item_link"] = "|cnIQ2:|Hitem:217117::::::::80:266::13:3:11318:9626:10840:6:28:2734:29:36:30:40:38:7:40:1288:43:210221::::Player-3674-09D241D0:|h[Algari Competitor's Cloth Leggings |A:Professions-ChatIcon-Quality-Tier4:17:15::1|a]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 217122,
["bag_id"] = 1,
["name"] = "Algari Competitor's Cloth Gloves",
["slot"] = 4,
["item_level"] = 88,
["item_link"] = "|cnIQ2:|Hitem:217122::::::::80:266::13:3:11318:9626:10840:6:28:2734:29:49:30:40:38:7:40:1293:43:210221::::Player-3674-09D241D0:|h[Algari Competitor's Cloth Gloves |A:Professions-ChatIcon-Quality-Tier4:17:15::1|a]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 85663,
["bag_id"] = 2,
["name"] = "Herbalist's Spade",
["slot"] = 1,
["item_level"] = 2,
["item_link"] = "|cnIQ1:|Hitem:85663::::::::80:266::14::1:28:783:::::|h[Herbalist's Spade]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 39505,
["bag_id"] = 2,
["name"] = "Virtuoso Inking Set",
["slot"] = 2,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:39505::::::::80:266::::1:28:783:::::|h[Virtuoso Inking Set]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 9295,
["bag_id"] = 2,
["name"] = "Recipe: Invisibility Potion",
["slot"] = 3,
["item_level"] = 1,
["item_link"] = "|cnIQ2:|Hitem:9295::::::::80:266::22::1:28:2872:::::|h[Recipe: Invisibility Potion]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 22309,
["bag_id"] = 2,
["name"] = "Pattern: Big Bag of Enchantment",
["slot"] = 4,
["item_level"] = 1,
["item_link"] = "|cnIQ2:|Hitem:22309::::::::80:266::22::1:28:2872:::::|h[Pattern: Big Bag of Enchantment]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 17706,
["bag_id"] = 2,
["name"] = "Plans: Edge of Winter",
["slot"] = 5,
["item_level"] = 1,
["item_link"] = "|cnIQ2:|Hitem:17706::::::::80:266::11::1:28:420:::::|h[Plans: Edge of Winter]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 226131,
["bag_id"] = 4,
["name"] = "Deployable Wind-Wrangling Spire",
["slot"] = 1,
["item_level"] = 86,
["item_link"] = "|cnIQ3:|Hitem:226131::::::::80:266:::::::::|h[Deployable Wind-Wrangling Spire]|h|r",
["count"] = 2,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 86143,
["bag_id"] = 4,
["name"] = "Battle Pet Bandage",
["slot"] = 2,
["item_level"] = 10,
["item_link"] = "|cnIQ2:|Hitem:86143::::::::80:266:::::::::|h[Battle Pet Bandage]|h|r",
["count"] = 87,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 222752,
["bag_id"] = 4,
["name"] = "Hearty Unseasoned Field Steak",
["slot"] = 3,
["item_level"] = 23,
["item_link"] = "|cnIQ3:|Hitem:222752::::::::80:266:::::::::|h[Hearty Unseasoned Field Steak]|h|r",
["count"] = 2,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 21215,
["bag_id"] = 4,
["name"] = "Graccu's Mince Meat Fruitcake",
["slot"] = 4,
["item_level"] = 11,
["item_link"] = "|cnIQ1:|Hitem:21215::::::::80:266:::::::::|h[Graccu's Mince Meat Fruitcake]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 21254,
["bag_id"] = 4,
["name"] = "Winter Veil Cookie",
["slot"] = 5,
["item_level"] = 12,
["item_link"] = "|cnIQ1:|Hitem:21254::::::::80:266:::::::::|h[Winter Veil Cookie]|h|r",
["count"] = 5,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 187418,
["bag_id"] = 4,
["name"] = "Evolving Mawshroom",
["slot"] = 6,
["item_level"] = 12,
["item_link"] = "|cnIQ1:|Hitem:187418::::::::80:266:::::::::|h[Evolving Mawshroom]|h|r",
["count"] = 20,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 187418,
["bag_id"] = 4,
["name"] = "Evolving Mawshroom",
["slot"] = 7,
["item_level"] = 12,
["item_link"] = "|cnIQ1:|Hitem:187418::::::::80:266:::::::::|h[Evolving Mawshroom]|h|r",
["count"] = 14,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 220756,
["bag_id"] = 4,
["name"] = "Flickering Torch",
["slot"] = 8,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:220756::::::::80:266:::::::::|h[Flickering Torch]|h|r",
["count"] = 6,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 187508,
["bag_id"] = 4,
["name"] = "Trained Gromit Carrier",
["slot"] = 9,
["item_level"] = 1,
["item_link"] = "|cnIQ2:|Hitem:187508::::::::80:266:::::::::|h[Trained Gromit Carrier]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 225767,
["bag_id"] = 4,
["name"] = "Spare Toolbox",
["slot"] = 10,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:225767::::::::80:266::::1:28:2838:::::|h[Spare Toolbox]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 223287,
["bag_id"] = 4,
["name"] = "Atomized Salien Slime",
["slot"] = 11,
["item_level"] = 86,
["item_link"] = "|cnIQ2:|Hitem:223287::::::::80:266:::::::::|h[Atomized Salien Slime]|h|r",
["count"] = 2,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 128768,
["bag_id"] = 4,
["name"] = "Candy Cane",
["slot"] = 12,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:128768::::::::80:266:::::::::|h[Candy Cane]|h|r",
["count"] = 5,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 224320,
["bag_id"] = 4,
["name"] = "Gleeful Glamour - Void Elf",
["slot"] = 13,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:224320::::::::80:266:::::::::|h[Gleeful Glamour - Void Elf |A:Professions-ChatIcon-Quality-Tier1:17:15::1|a]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 225673,
["bag_id"] = 5,
["name"] = "Artisan's Consortium Seal of Approval",
["slot"] = 1,
["item_level"] = 21,
["item_link"] = "|cnIQ4:|Hitem:225673::::::::80:266:::::::::|h[Artisan's Consortium Seal of Approval]|h|r",
["count"] = 1,
["quality"] = 4,
},
{
["container_kind"] = "character_bag",
["id"] = 228339,
["bag_id"] = 5,
["name"] = "Soul Sigil II",
["slot"] = 2,
["item_level"] = 21,
["item_link"] = "|cnIQ3:|Hitem:228339::::::::80:266:::::::::|h[Soul Sigil II]|h|r",
["count"] = 2,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 228338,
["bag_id"] = 5,
["name"] = "Soul Sigil I",
["slot"] = 3,
["item_level"] = 21,
["item_link"] = "|cnIQ3:|Hitem:228338::::::::80:266:::::::::|h[Soul Sigil I]|h|r",
["count"] = 6,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 194124,
["bag_id"] = 5,
["name"] = "Vibrant Shard",
["slot"] = 4,
["item_level"] = 19,
["item_link"] = "|cnIQ3:|Hitem:194124::::::::80:266:::::::::|h[Vibrant Shard]|h|r",
["count"] = 1,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 210815,
["bag_id"] = 5,
["name"] = "Coreway Catalyst",
["slot"] = 5,
["item_level"] = 21,
["item_link"] = "|cnIQ3:|Hitem:210815::::::::80:266:::::::::|h[Coreway Catalyst]|h|r",
["count"] = 10,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 211296,
["bag_id"] = 5,
["name"] = "Spark of Omens",
["slot"] = 6,
["item_level"] = 21,
["item_link"] = "|cnIQ4:|Hitem:211296::::::::80:266:::::::::|h[Spark of Omens]|h|r",
["count"] = 1,
["quality"] = 4,
},
{
["container_kind"] = "character_bag",
["id"] = 210814,
["bag_id"] = 5,
["name"] = "Artisan's Acuity",
["slot"] = 7,
["item_level"] = 21,
["item_link"] = "|cnIQ3:|Hitem:210814::::::::80:266:::::::::|h[Artisan's Acuity]|h|r",
["count"] = 1010,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 173060,
["bag_id"] = 5,
["name"] = "Aerated Water",
["slot"] = 8,
["item_level"] = 17,
["item_link"] = "|cnIQ1:|Hitem:173060::::::::80:266:::::::::|h[Aerated Water]|h|r",
["count"] = 124,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 211297,
["bag_id"] = 5,
["name"] = "Fractured Spark of Omens",
["slot"] = 9,
["item_level"] = 21,
["item_link"] = "|cnIQ4:|Hitem:211297::::::::80:266:::::::::|h[Fractured Spark of Omens]|h|r",
["count"] = 1,
["quality"] = 4,
},
{
["container_kind"] = "character_bag",
["id"] = 165703,
["bag_id"] = 5,
["name"] = "Breath of Bwonsamdi",
["slot"] = 10,
["item_level"] = 16,
["item_link"] = "|cnIQ4:|Hitem:165703::::::::80:266:::::::::|h[Breath of Bwonsamdi]|h|r",
["count"] = 9,
["quality"] = 4,
},
{
["container_kind"] = "character_bag",
["id"] = 165948,
["bag_id"] = 5,
["name"] = "Tidalcore",
["slot"] = 11,
["item_level"] = 16,
["item_link"] = "|cnIQ3:|Hitem:165948::::::::80:266:::::::::|h[Tidalcore]|h|r",
["count"] = 22,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 152668,
["bag_id"] = 5,
["name"] = "Expulsom",
["slot"] = 12,
["item_level"] = 16,
["item_link"] = "|cnIQ3:|Hitem:152668::::::::80:266:::::::::|h[Expulsom]|h|r",
["count"] = 33,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 173204,
["bag_id"] = 5,
["name"] = "Lightless Silk",
["slot"] = 13,
["item_level"] = 17,
["item_link"] = "|cnIQ2:|Hitem:173204::::::::80:266:::::::::|h[Lightless Silk]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 173202,
["bag_id"] = 5,
["name"] = "Shrouded Cloth",
["slot"] = 14,
["item_level"] = 17,
["item_link"] = "|cnIQ1:|Hitem:173202::::::::80:266:::::::::|h[Shrouded Cloth]|h|r",
["count"] = 2,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 219948,
["bag_id"] = 5,
["name"] = "Storm Dust",
["slot"] = 15,
["item_level"] = 21,
["item_link"] = "|cnIQ1:|Hitem:219948::::::::80:266:::::::::|h[Storm Dust |A:Professions-ChatIcon-Quality-Tier3:17:15::1|a]|h|r",
["count"] = 105,
["quality"] = 1,
},
},
},
},
["Player-3674-0BB3F0D1"] = {
["containers"] = {
["updated_at"] = 1778448408,
["partial"] = false,
["records"] = {
{
["id"] = -2,
["name"] = "_container_scan_meta",
["bank_ui_opened_at_least_once"] = false,
},
{
["container_kind"] = "character_bag",
["id"] = 6948,
["bag_id"] = 0,
["name"] = "Hearthstone",
["slot"] = 1,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:6948::::::::15:253::75:::::::|h[Hearthstone]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 6889,
["bag_id"] = 0,
["name"] = "Small Egg",
["slot"] = 2,
["item_level"] = 10,
["item_link"] = "|cnIQ1:|Hitem:6889::::::::15:253:::::::::|h[Small Egg]|h|r",
["count"] = 3,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 805,
["bag_id"] = 0,
["name"] = "Small Red Pouch",
["slot"] = 3,
["item_level"] = 2,
["item_link"] = "|cnIQ1:|Hitem:805::::::::15:253:::::::::|h[Small Red Pouch]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 20837,
["bag_id"] = 0,
["name"] = "Sunstrider Axe",
["slot"] = 4,
["item_level"] = 5,
["item_link"] = "|cnIQ1:|Hitem:20837::::::::15:253::11:1:13617:2:9:5:28:1485:::::|h[Sunstrider Axe]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 187693,
["bag_id"] = 0,
["name"] = "Hunter's Belt",
["slot"] = 5,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:187693::::::::15:253::75:::::::|h[Hunter's Belt]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 128541,
["bag_id"] = 0,
["name"] = "Enchant Ring - Binding of Critical Strike",
["slot"] = 6,
["item_level"] = 16,
["item_link"] = "|cnIQ3:|Hitem:128541::::::::15:253:::::::::|h[Enchant Ring - Binding of Critical Strike]|h|r",
["count"] = 1,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 192626,
["bag_id"] = 0,
["name"] = "Mound of Dust",
["slot"] = 7,
["item_level"] = 21,
["item_link"] = "|cnIQ0:|Hitem:192626::::::::15:253:::::::::|h[Mound of Dust]|h|r",
["count"] = 2,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 83007,
["bag_id"] = 0,
["name"] = "Greater Tiger Claw Inscription",
["slot"] = 8,
["item_level"] = 15,
["item_link"] = "|cnIQ4:|Hitem:83007::::::::15:253:::::::::|h[Greater Tiger Claw Inscription]|h|r",
["count"] = 1,
["quality"] = 4,
},
{
["container_kind"] = "character_bag",
["id"] = 192644,
["bag_id"] = 0,
["name"] = "Aeriform Speck",
["slot"] = 9,
["item_level"] = 21,
["item_link"] = "|cnIQ0:|Hitem:192644::::::::15:253:::::::::|h[Aeriform Speck]|h|r",
["count"] = 1,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 192628,
["bag_id"] = 0,
["name"] = "Phoenix Ash",
["slot"] = 10,
["item_level"] = 21,
["item_link"] = "|cnIQ0:|Hitem:192628::::::::15:253:::::::::|h[Phoenix Ash]|h|r",
["count"] = 2,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 4663,
["bag_id"] = 0,
["name"] = "Journeyman's Belt",
["slot"] = 11,
["item_level"] = 4,
["item_link"] = "|cnIQ1:|Hitem:4663::::::::15:253::::1:28:77:::::|h[Journeyman's Belt]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 23334,
["bag_id"] = 0,
["name"] = "Cracked Power Core",
["slot"] = 12,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:23334::::::::15:253:::::::::|h[Cracked Power Core]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 131237,
["bag_id"] = 0,
["name"] = "Padded Chainmail",
["slot"] = 13,
["item_level"] = 7,
["item_link"] = "|cnIQ1:|Hitem:131237::::::::15:253::11:1:13617:2:9:7:28:77:::::|h[Padded Chainmail]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 23354,
["bag_id"] = 0,
["name"] = "Crystalized Mana Residue",
["slot"] = 14,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:23354::::::::15:253:::::::::|h[Crystalized Mana Residue]|h|r",
["count"] = 3,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 7096,
["bag_id"] = 0,
["name"] = "Plucked Feather",
["slot"] = 15,
["item_level"] = 1,
["item_link"] = "|cnIQ0:|Hitem:7096::::::::15:253:::::::::|h[Plucked Feather]|h|r",
["count"] = 1,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 23353,
["bag_id"] = 0,
["name"] = "Mana Residue",
["slot"] = 16,
["item_level"] = 1,
["item_link"] = "|cnIQ0:|Hitem:23353::::::::15:253:::::::::|h[Mana Residue]|h|r",
["count"] = 8,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 779,
["bag_id"] = 0,
["name"] = "Shiny Seashell",
["slot"] = 17,
["item_level"] = 1,
["item_link"] = "|cnIQ0:|Hitem:779::::::::15:253:::::::::|h[Shiny Seashell]|h|r",
["count"] = 6,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 6510,
["bag_id"] = 0,
["name"] = "Infantry Gauntlets",
["slot"] = 18,
["item_level"] = 5,
["item_link"] = "|cnIQ1:|Hitem:6510::::::::15:253::::1:28:77:::::|h[Infantry Gauntlets]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 2589,
["bag_id"] = 0,
["name"] = "Linen Cloth",
["slot"] = 19,
["item_level"] = 10,
["item_link"] = "|cnIQ1:|Hitem:2589::::::::15:253:::::::::|h[Linen Cloth]|h|r",
["count"] = 9,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 23370,
["bag_id"] = 0,
["name"] = "Ley-Keeper's Blade",
["slot"] = 20,
["item_level"] = 7,
["item_link"] = "|cnIQ1:|Hitem:23370::::::::15:253::11:1:13617:2:9:7:28:77:::::|h[Ley-Keeper's Blade]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 2643,
["bag_id"] = 1,
["name"] = "Loose Chain Bracers",
["slot"] = 1,
["item_level"] = 1,
["item_link"] = "|cnIQ0:|Hitem:2643::::::::15:253:::1:6656:2:9:9:28:77:::::|h[Loose Chain Bracers]|h|r",
["count"] = 1,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 774,
["bag_id"] = 1,
["name"] = "Malachite",
["slot"] = 2,
["item_level"] = 10,
["item_link"] = "|cnIQ2:|Hitem:774::::::::15:253:::::::::|h[Malachite]|h|r",
["count"] = 2,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 23398,
["bag_id"] = 1,
["name"] = "Worn Ranger's Bow",
["slot"] = 3,
["item_level"] = 9,
["item_link"] = "|cnIQ1:|Hitem:23398::::::::15:253::11:1:13617:2:9:9:28:77:::::|h[Worn Ranger's Bow]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 1429,
["bag_id"] = 1,
["name"] = "Patchwork Cloak",
["slot"] = 4,
["item_level"] = 1,
["item_link"] = "|cnIQ0:|Hitem:1429::::::::15:253:::1:6656:2:9:9:28:77:::::|h[Patchwork Cloak]|h|r",
["count"] = 1,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 22957,
["bag_id"] = 1,
["name"] = "Rusty Sin'dorei Sword",
["slot"] = 5,
["item_level"] = 9,
["item_link"] = "|cnIQ1:|Hitem:22957::::::::15:253::11:1:13617:2:9:9:28:77:::::|h[Rusty Sin'dorei Sword]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 1431,
["bag_id"] = 1,
["name"] = "Patchwork Pants",
["slot"] = 6,
["item_level"] = 1,
["item_link"] = "|cnIQ0:|Hitem:1431::::::::15:253:::1:6656:2:9:10:28:77:::::|h[Patchwork Pants]|h|r",
["count"] = 1,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 131240,
["bag_id"] = 1,
["name"] = "Longshoreman's Bracers",
["slot"] = 7,
["item_level"] = 10,
["item_link"] = "|cnIQ1:|Hitem:131240::::::::15:253::11:1:13617:2:9:10:28:77:::::|h[Longshoreman's Bracers]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 23373,
["bag_id"] = 1,
["name"] = "Long Knife",
["slot"] = 8,
["item_level"] = 10,
["item_link"] = "|cnIQ1:|Hitem:23373::::::::15:253::11:1:13617:2:9:10:28:77:::::|h[Long Knife]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 180055,
["bag_id"] = 1,
["name"] = "Relic of the Past I",
["slot"] = 9,
["item_level"] = 17,
["item_link"] = "|cnIQ1:|Hitem:180055::::::::15:253:::::::::|h[Relic of the Past I]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 192631,
["bag_id"] = 1,
["name"] = "Scale-Piercing Fang",
["slot"] = 10,
["item_level"] = 21,
["item_link"] = "|cnIQ0:|Hitem:192631::::::::15:253:::::::::|h[Scale-Piercing Fang]|h|r",
["count"] = 26,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 192624,
["bag_id"] = 1,
["name"] = "Cracked Scales",
["slot"] = 11,
["item_level"] = 21,
["item_link"] = "|cnIQ0:|Hitem:192624::::::::15:253:::::::::|h[Cracked Scales]|h|r",
["count"] = 4,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 200285,
["bag_id"] = 1,
["name"] = "Dragonscale Expedition Insignia",
["slot"] = 12,
["item_level"] = 17,
["item_link"] = "|cnIQ2:|Hitem:200285::::::::15:253:::::::::|h[Dragonscale Expedition Insignia]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 197744,
["bag_id"] = 1,
["name"] = "Hornswog Hunk",
["slot"] = 13,
["item_level"] = 19,
["item_link"] = "|cnIQ1:|Hitem:197744::::::::15:253:::::::::|h[Hornswog Hunk]|h|r",
["count"] = 2,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 200093,
["bag_id"] = 1,
["name"] = "Centaur Hunting Trophy",
["slot"] = 14,
["item_level"] = 1,
["item_link"] = "|cnIQ2:|Hitem:200093::::::::15:253:::::::::|h[Centaur Hunting Trophy]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 200165,
["bag_id"] = 1,
["name"] = "Aegis of Scales",
["slot"] = 15,
["item_level"] = 11,
["item_link"] = "|cnIQ3:|Hitem:200165::::::::15:253::17:2:13642:6652:2:9:11:28:2437:::::|h[Aegis of Scales]|h|r",
["count"] = 1,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 192672,
["bag_id"] = 1,
["name"] = "Tattered Proto-Wing",
["slot"] = 16,
["item_level"] = 21,
["item_link"] = "|cnIQ0:|Hitem:192672::::::::15:253:::::::::|h[Tattered Proto-Wing]|h|r",
["count"] = 1,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 192614,
["bag_id"] = 1,
["name"] = "Elemental Ooze",
["slot"] = 17,
["item_level"] = 21,
["item_link"] = "|cnIQ0:|Hitem:192614::::::::15:253:::::::::|h[Elemental Ooze]|h|r",
["count"] = 11,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 188213,
["bag_id"] = 1,
["name"] = "Large Green Bag",
["slot"] = 18,
["item_level"] = 12,
["item_link"] = "|cnIQ1:|Hitem:188213::::::::15:253:::::::::|h[Large Green Bag]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 192635,
["bag_id"] = 1,
["name"] = "Warped Metal",
["slot"] = 19,
["item_level"] = 21,
["item_link"] = "|cnIQ0:|Hitem:192635::::::::15:253:::::::::|h[Warped Metal]|h|r",
["count"] = 10,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 190320,
["bag_id"] = 1,
["name"] = "Rousing Fire",
["slot"] = 20,
["item_level"] = 19,
["item_link"] = "|cnIQ3:|Hitem:190320::::::::15:253:::::::::|h[Rousing Fire]|h|r",
["count"] = 2,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 201470,
["bag_id"] = 1,
["name"] = "Story of a Memorable Victory",
["slot"] = 21,
["item_level"] = 1,
["item_link"] = "|cnIQ2:|Hitem:201470::::::::15:253:::::::::|h[Story of a Memorable Victory]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 192625,
["bag_id"] = 1,
["name"] = "Motionless Stone",
["slot"] = 22,
["item_level"] = 21,
["item_link"] = "|cnIQ0:|Hitem:192625::::::::15:253:::::::::|h[Motionless Stone]|h|r",
["count"] = 6,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 192662,
["bag_id"] = 1,
["name"] = "Pyretic Speck",
["slot"] = 23,
["item_level"] = 21,
["item_link"] = "|cnIQ0:|Hitem:192662::::::::15:253:::::::::|h[Pyretic Speck]|h|r",
["count"] = 2,
["quality"] = 0,
},
{
["container_kind"] = "character_bag",
["id"] = 193050,
["bag_id"] = 1,
["name"] = "Tattered Wildercloth",
["slot"] = 24,
["item_level"] = 19,
["item_link"] = "|cnIQ1:|Hitem:193050::::::::15:253:::::::::|h[Tattered Wildercloth]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 194402,
["bag_id"] = 1,
["name"] = "Expedition Mercenary's Hauberk",
["slot"] = 25,
["item_level"] = 13,
["item_link"] = "|cnIQ2:|Hitem:194402::::::::15:253::26:1:13642:2:9:13:28:2523:::::|h[Expedition Mercenary's Hauberk]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 190315,
["bag_id"] = 1,
["name"] = "Rousing Earth",
["slot"] = 26,
["item_level"] = 19,
["item_link"] = "|cnIQ3:|Hitem:190315::::::::15:253:::::::::|h[Rousing Earth]|h|r",
["count"] = 3,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 197741,
["bag_id"] = 1,
["name"] = "Maybe Meat",
["slot"] = 27,
["item_level"] = 19,
["item_link"] = "|cnIQ1:|Hitem:197741::::::::15:253:::::::::|h[Maybe Meat]|h|r",
["count"] = 3,
["quality"] = 1,
},
},
},
},
["Player-3674-09C5872B"] = {
["containers"] = {
["updated_at"] = 1778492151,
["records"] = {
{
["id"] = -2,
["name"] = "_container_scan_meta",
["bank_ui_opened_at_least_once"] = false,
},
{
["container_kind"] = "character_bag",
["id"] = 6948,
["bag_id"] = 0,
["name"] = "Hearthstone",
["slot"] = 1,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:6948::::::::88:577:::::::::|h[Hearthstone]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 265820,
["bag_id"] = 0,
["name"] = "Ruia's Musings, Part 3",
["slot"] = 2,
["item_level"] = 80,
["item_link"] = "|cnIQ1:|Hitem:265820::::::::88:577:::::::::|h[Ruia's Musings, Part 3]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 265819,
["bag_id"] = 0,
["name"] = "Ruia's Musings, Part 2",
["slot"] = 3,
["item_level"] = 80,
["item_link"] = "|cnIQ1:|Hitem:265819::::::::88:577:::::::::|h[Ruia's Musings, Part 2]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 265818,
["bag_id"] = 0,
["name"] = "Ruia's Musings, Part 1",
["slot"] = 4,
["item_level"] = 80,
["item_link"] = "|cnIQ1:|Hitem:265818::::::::88:577:::::::::|h[Ruia's Musings, Part 1]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 163604,
["bag_id"] = 0,
["name"] = "Net-o-Matic 5000",
["slot"] = 5,
["item_level"] = 15,
["item_link"] = "|cnIQ2:|Hitem:163604::::::::88:577::11:::::::|h[Net-o-Matic 5000]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 267051,
["bag_id"] = 0,
["name"] = "Dark Particle",
["slot"] = 6,
["item_level"] = 1,
["item_link"] = "|cnIQ2:|Hitem:267051::::::::88:577:::::::::|h[Dark Particle]|h|r",
["count"] = 89,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 253580,
["bag_id"] = 0,
["name"] = "Harvesting Hatchet",
["slot"] = 7,
["item_level"] = 1,
["item_link"] = "|cnIQ3:|Hitem:253580::::::::88:577::14::1:28:4285:::::|h[Harvesting Hatchet]|h|r",
["count"] = 1,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 259126,
["bag_id"] = 0,
["name"] = "Void Violet Dye",
["slot"] = 9,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:259126::::::::88:577:::::::::|h[Void Violet Dye]|h|r",
["count"] = 3,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 259115,
["bag_id"] = 0,
["name"] = "Alliance Blue Dye",
["slot"] = 10,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:259115::::::::88:577:::::::::|h[Alliance Blue Dye]|h|r",
["count"] = 3,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 259114,
["bag_id"] = 0,
["name"] = "Lush Green Dye",
["slot"] = 11,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:259114::::::::88:577:::::::::|h[Lush Green Dye]|h|r",
["count"] = 4,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 259113,
["bag_id"] = 0,
["name"] = "Horde Red Dye",
["slot"] = 12,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:259113::::::::88:577:::::::::|h[Horde Red Dye]|h|r",
["count"] = 3,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 238500,
["bag_id"] = 0,
["name"] = "Maella's Report",
["slot"] = 20,
["item_level"] = 21,
["item_link"] = "|cnIQ1:|Hitem:238500::::::::88:577:::::::::|h[Maella's Report]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 86143,
["bag_id"] = 1,
["name"] = "Battle Pet Bandage",
["slot"] = 2,
["item_level"] = 10,
["item_link"] = "|cnIQ2:|Hitem:86143::::::::88:577:::::::::|h[Battle Pet Bandage]|h|r",
["count"] = 4,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 200886,
["bag_id"] = 1,
["name"] = "Lemon Silverleaf Tea",
["slot"] = 3,
["item_level"] = 21,
["item_link"] = "|cnIQ1:|Hitem:200886::::::::88:577:::::::::|h[Lemon Silverleaf Tea]|h|r",
["count"] = 6,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 258138,
["bag_id"] = 1,
["name"] = "Potent Healing Potion",
["slot"] = 5,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:258138::::::::88:577:::::::::|h[Potent Healing Potion]|h|r",
["count"] = 34,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 1205,
["bag_id"] = 1,
["name"] = "Melon Juice",
["slot"] = 6,
["item_level"] = 7,
["item_link"] = "|cnIQ1:|Hitem:1205::::::::88:577:::::::::|h[Melon Juice]|h|r",
["count"] = 2,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 1708,
["bag_id"] = 1,
["name"] = "Sweet Nectar",
["slot"] = 7,
["item_level"] = 10,
["item_link"] = "|cnIQ1:|Hitem:1708::::::::88:577:::::::::|h[Sweet Nectar]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 4599,
["bag_id"] = 1,
["name"] = "Cured Ham Steak",
["slot"] = 8,
["item_level"] = 11,
["item_link"] = "|cnIQ1:|Hitem:4599::::::::88:577:::::::::|h[Cured Ham Steak]|h|r",
["count"] = 2,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 1645,
["bag_id"] = 1,
["name"] = "Moonberry Juice",
["slot"] = 9,
["item_level"] = 11,
["item_link"] = "|cnIQ1:|Hitem:1645::::::::88:577:::::::::|h[Moonberry Juice]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 8952,
["bag_id"] = 1,
["name"] = "Roasted Quail",
["slot"] = 10,
["item_level"] = 12,
["item_link"] = "|cnIQ1:|Hitem:8952::::::::88:577:::::::::|h[Roasted Quail]|h|r",
["count"] = 3,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 2455,
["bag_id"] = 1,
["name"] = "Minor Mana Potion",
["slot"] = 11,
["item_level"] = 7,
["item_link"] = "|cnIQ1:|Hitem:2455::::::::88:577:::::::::|h[Minor Mana Potion]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 117,
["bag_id"] = 1,
["name"] = "Tough Jerky",
["slot"] = 12,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:117::::::::88:577:::::::::|h[Tough Jerky]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 13446,
["bag_id"] = 1,
["name"] = "Major Healing Potion",
["slot"] = 13,
["item_level"] = 12,
["item_link"] = "|cnIQ1:|Hitem:13446::::::::88:577:::::::::|h[Major Healing Potion]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 262786,
["bag_id"] = 1,
["name"] = "Suntouched Special Reserve",
["slot"] = 14,
["item_level"] = 1,
["item_link"] = "|cnIQ1:|Hitem:262786::::::::88:577:::::::::|h[Suntouched Special Reserve]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 112384,
["bag_id"] = 1,
["name"] = "Reflecting Prism",
["slot"] = 15,
["item_level"] = 1,
["item_link"] = "|cnIQ2:|Hitem:112384::::::::88:577::::1:28:5914:::::|h[Reflecting Prism]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 112384,
["bag_id"] = 1,
["name"] = "Reflecting Prism",
["slot"] = 16,
["item_level"] = 1,
["item_link"] = "|cnIQ2:|Hitem:112384::::::::88:577::::1:28:5914:::::|h[Reflecting Prism]|h|r",
["count"] = 1,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 238987,
["bag_id"] = 1,
["name"] = "Saltheril's Favor",
["slot"] = 21,
["item_level"] = 1,
["item_link"] = "|cnIQ3:|Hitem:238987::::::::88:577:::::::::|h[Saltheril's Favor]|h|r",
["count"] = 1,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 270934,
["bag_id"] = 1,
["name"] = "Recruit's Field Pouch",
["slot"] = 22,
["item_level"] = 1,
["item_link"] = "|cnIQ3:|Hitem:270934::::::::88:577::11::2:9:87:28:3322:::::|h[Recruit's Field Pouch]|h|r",
["count"] = 1,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 272125,
["bag_id"] = 1,
["name"] = "Recruit's Cache",
["slot"] = 23,
["item_level"] = 1,
["item_link"] = "|cnIQ3:|Hitem:272125::::::::88:577::11::2:9:87:28:3321:::::|h[Recruit's Cache]|h|r",
["count"] = 1,
["quality"] = 3,
},
{
["container_kind"] = "character_bag",
["id"] = 38682,
["bag_id"] = 3,
["name"] = "Enchanting Vellum",
["slot"] = 1,
["item_level"] = 44,
["item_link"] = "|cnIQ1:|Hitem:38682::::::::88:577:::::::::|h[Enchanting Vellum]|h|r",
["count"] = 44,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 227208,
["bag_id"] = 3,
["name"] = "Bismuth Rod",
["slot"] = 2,
["item_level"] = 77,
["item_link"] = "|cnIQ1:|Hitem:227208::::::::88:577::14::1:28:2797:::::|h[Bismuth Rod]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 256963,
["bag_id"] = 5,
["name"] = "Thalassian Lumber",
["slot"] = 5,
["item_level"] = 10,
["item_link"] = "|cnIQ2:|Hitem:256963::::::::88:577:::::::::|h[Thalassian Lumber]|h|r",
["count"] = 2,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 251923,
["bag_id"] = 5,
["name"] = "Thalassian Essence of the Faire",
["slot"] = 11,
["item_level"] = 24,
["item_link"] = "|cnIQ2:|Hitem:251923::::::::88:577:::::::::|h[Thalassian Essence of the Faire]|h|r",
["count"] = 2,
["quality"] = 2,
},
{
["container_kind"] = "character_bag",
["id"] = 4338,
["bag_id"] = 5,
["name"] = "Mageweave Cloth",
["slot"] = 14,
["item_level"] = 10,
["item_link"] = "|cnIQ1:|Hitem:4338::::::::88:577:::::::::|h[Mageweave Cloth]|h|r",
["count"] = 3,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 1179,
["bag_id"] = 5,
["name"] = "Ice Cold Milk",
["slot"] = 15,
["item_level"] = 3,
["item_link"] = "|cnIQ1:|Hitem:1179::::::::88:577:::::::::|h[Ice Cold Milk]|h|r",
["count"] = 1,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 40195,
["bag_id"] = 5,
["name"] = "Pygmy Oil",
["slot"] = 16,
["item_level"] = 12,
["item_link"] = "|cnIQ1:|Hitem:40195::::::::88:577:::::::::|h[Pygmy Oil]|h|r",
["count"] = 2,
["quality"] = 1,
},
{
["container_kind"] = "character_bag",
["id"] = 265801,
["bag_id"] = 5,
["name"] = "Savory Anomaly",
["slot"] = 17,
["item_level"] = 78,
["item_link"] = "|cnIQ2:|Hitem:265801::::::::88:577:::::::::|h[Savory Anomaly]|h|r",
["count"] = 1,
["quality"] = 2,
},
},
["partial"] = false,
},
},
},
["schema_version"] = 4,
["addon_folder"] = "AzerothDataCollector_Containers",
["last_saved_at"] = 1778492151,
}
