
AzerothDataCollector_MetaDB = {
["module_key"] = "meta",
["by_character"] = {
["Player-3674-0BB3F0D1"] = {
["meta"] = {
["guid"] = "Player-3674-0BB3F0D1",
["subzone"] = "",
["class"] = "HUNTER",
["race"] = "Blood Elf",
["level"] = 15,
["class_localized"] = "Hunter",
["realm"] = "Twisting Nether",
["ilvl_overall"] = 0,
["race_id"] = 10,
["spec_index"] = 1,
["updated_at"] = 1778448483,
["name"] = "Maevil",
["server_time"] = "2026-05-11 00:28:03",
["faction"] = "Horde",
["gender_id"] = 3,
["zone"] = "The Waking Shores",
["spec_id"] = 0,
["ilvl_equipped"] = 0,
},
["wallet"] = {
["partial"] = false,
["copper"] = 0,
["updated_at"] = 1778448483,
},
},
["Player-3674-09C5872B"] = {
["meta"] = {
["guid"] = "Player-3674-09C5872B",
["subzone"] = "Murder Row",
["class"] = "DEMONHUNTER",
["race"] = "Blood Elf",
["level"] = 88,
["class_localized"] = "Demon Hunter",
["realm"] = "Twisting Nether",
["ilvl_overall"] = 0,
["race_id"] = 10,
["spec_index"] = 1,
["server_time"] = "2026-05-11 01:03:22",
["updated_at"] = 1778450602,
["name"] = "Auvendil",
["faction"] = "Horde",
["gender_id"] = 2,
["spec_id"] = 0,
["zone"] = "Silvermoon City",
["ilvl_equipped"] = 0,
},
["wallet"] = {
["partial"] = false,
["copper"] = 0,
["updated_at"] = 1778450602,
},
},
},
["schema_version"] = 4,
["addon_folder"] = "AzerothDataCollector_Meta",
["last_saved_at"] = 0,
}
