
AzerothDataCollector_CurrenciesDB = {
["module_key"] = "currencies",
["by_character"] = {
["Player-3674-0BB3F0D1"] = {
["currencies"] = {
["updated_at"] = 1778448408,
["partial"] = false,
["records"] = {
{
["max_weekly_quantity"] = 0,
["name"] = "Dawnlight Manaflux",
["max_quantity"] = 8,
["id"] = 3378,
["category_header"] = "Season 1",
["quantity_earned_this_week"] = 0,
["quantity"] = 4,
},
{
["max_weekly_quantity"] = 0,
["name"] = "Trader's Tender",
["max_quantity"] = 0,
["id"] = 2032,
["category_header"] = "Miscellaneous",
["quantity_earned_this_week"] = 0,
["quantity"] = 3015,
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 20,
["name"] = "Dragon Isles Supplies",
["max_quantity"] = 0,
["id"] = 2003,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Dragonflight",
},
},
},
},
["Player-3674-09C5872B"] = {
["currencies"] = {
["updated_at"] = 1778449755,
["records"] = {
{
["max_weekly_quantity"] = 0,
["quantity"] = 31,
["name"] = "Angler Pearls",
["max_quantity"] = 0,
["id"] = 3373,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Midnight",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 70,
["name"] = "Artisan Herbalist's Moxie",
["max_quantity"] = 0,
["id"] = 3260,
["quantity_earned_this_week"] = 0,
["category_header"] = "Midnight",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 2,
["name"] = "Luminous Dust",
["max_quantity"] = 0,
["id"] = 3385,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Midnight",
},
{
["max_weekly_quantity"] = 8,
["quantity"] = 5,
["name"] = "Shard of Dundun",
["max_quantity"] = 8,
["id"] = 3376,
["quantity_earned_this_week"] = 5,
["category_header"] = "Midnight",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 1102,
["name"] = "Voidlight Marl",
["max_quantity"] = 0,
["id"] = 3316,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Midnight",
},
{
["max_weekly_quantity"] = 600,
["quantity"] = 153,
["name"] = "Coffer Key Shards",
["max_quantity"] = 0,
["id"] = 3310,
["quantity_earned_this_week"] = 153,
["category_header"] = "Season 1",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 4,
["name"] = "Dawnlight Manaflux",
["max_quantity"] = 8,
["id"] = 3378,
["quantity_earned_this_week"] = 0,
["category_header"] = "Season 1",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 1,
["name"] = "Restored Coffer Key",
["max_quantity"] = 0,
["id"] = 3028,
["quantity_earned_this_week"] = 0,
["category_header"] = "Season 1",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 3000,
["name"] = "Undercoin",
["max_quantity"] = 0,
["id"] = 2803,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Season 1",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 1175,
["name"] = "Timewarped Badge",
["max_quantity"] = 0,
["id"] = 1166,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Dungeon and Raid",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 78,
["name"] = "Community Coupons",
["max_quantity"] = 2000,
["id"] = 3363,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Miscellaneous",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 5,
["name"] = "Darkmoon Prize Ticket",
["max_quantity"] = 0,
["id"] = 515,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Miscellaneous",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 3015,
["name"] = "Trader's Tender",
["max_quantity"] = 0,
["id"] = 2032,
["quantity_earned_this_week"] = 0,
["category_header"] = "Miscellaneous",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Bloody Tokens",
["max_quantity"] = 7200,
["id"] = 2123,
["quantity_earned_this_week"] = 0,
["category_header"] = "Player vs. Player",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Conquest",
["max_quantity"] = 7200,
["id"] = 1602,
["quantity_earned_this_week"] = 0,
["category_header"] = "Player vs. Player",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Honor",
["max_quantity"] = 15000,
["id"] = 1792,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Player vs. Player",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 3115,
["name"] = "Kej",
["max_quantity"] = 0,
["id"] = 3056,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "War Within",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 1,
["name"] = "Nerub-ar Finery",
["max_quantity"] = 128,
["id"] = 3093,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "War Within",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 1400,
["name"] = "Resonance Crystals",
["max_quantity"] = 0,
["id"] = 2815,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "War Within",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 18703,
["name"] = "Dragon Isles Supplies",
["max_quantity"] = 0,
["id"] = 2003,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Dragonflight",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Drake's Awakened Crest",
["max_quantity"] = 0,
["id"] = 2807,
["quantity_earned_this_week"] = 0,
["category_header"] = "Dragonflight",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 5,
["name"] = "Dream Infusion",
["max_quantity"] = 0,
["id"] = 2777,
["quantity_earned_this_week"] = 0,
["category_header"] = "Dragonflight",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 4803,
["name"] = "Elemental Overflow",
["max_quantity"] = 0,
["id"] = 2118,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Dragonflight",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 276,
["name"] = "Emerald Dewdrop",
["max_quantity"] = 0,
["id"] = 2650,
["quantity_earned_this_week"] = 0,
["category_header"] = "Dragonflight",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Flightstones",
["max_quantity"] = 2000,
["id"] = 2245,
["quantity_earned_this_week"] = 0,
["category_header"] = "Dragonflight",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 6174,
["name"] = "Mysterious Fragment",
["max_quantity"] = 0,
["id"] = 2657,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Dragonflight",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 3236,
["name"] = "Paracausal Flakes",
["max_quantity"] = 0,
["id"] = 2594,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Dragonflight",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 16,
["name"] = "Storm Sigil",
["max_quantity"] = 0,
["id"] = 2122,
["quantity_earned_this_week"] = 0,
["category_header"] = "Dragonflight",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Whelpling's Awakened Crest",
["max_quantity"] = 0,
["id"] = 2806,
["quantity_earned_this_week"] = 0,
["category_header"] = "Dragonflight",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Wyrm's Awakened Crest",
["max_quantity"] = 0,
["id"] = 2809,
["quantity_earned_this_week"] = 0,
["category_header"] = "Dragonflight",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 1155,
["name"] = "Cataloged Research",
["max_quantity"] = 0,
["id"] = 1931,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 1128,
["name"] = "Cosmic Flux",
["max_quantity"] = 0,
["id"] = 2009,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 248,
["name"] = "Cyphers of the First Ones",
["max_quantity"] = 0,
["id"] = 1979,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 39,
["name"] = "Grateful Offering",
["max_quantity"] = 0,
["id"] = 1885,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 100,
["name"] = "Infused Ruby",
["max_quantity"] = 100,
["id"] = 1820,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 27455,
["name"] = "Reservoir Anima",
["max_quantity"] = 200000,
["id"] = 1813,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 4070,
["name"] = "Sinstone Fragments",
["max_quantity"] = 0,
["id"] = 1816,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 24188,
["name"] = "Soul Ash",
["max_quantity"] = 0,
["id"] = 1828,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 91,
["name"] = "Soul Cinders",
["max_quantity"] = 0,
["id"] = 1906,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 2066,
["name"] = "Stygia",
["max_quantity"] = 0,
["id"] = 1767,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 37,
["name"] = "Stygian Ember",
["max_quantity"] = 0,
["id"] = 1977,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 92,
["name"] = "Tower Knowledge",
["max_quantity"] = 3510,
["id"] = 1904,
["quantity_earned_this_week"] = 0,
["category_header"] = "Shadowlands",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 20858,
["name"] = "Coalescing Visions",
["max_quantity"] = 0,
["id"] = 1755,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Battle for Azeroth",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 1989,
["name"] = "Corrupted Mementos",
["max_quantity"] = 0,
["id"] = 1719,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Battle for Azeroth",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 7395,
["name"] = "Echoes of Ny'alotha",
["max_quantity"] = 0,
["id"] = 1803,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Battle for Azeroth",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 65,
["name"] = "Honorbound Service Medal",
["max_quantity"] = 0,
["id"] = 1716,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Battle for Azeroth",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 614,
["name"] = "Prismatic Manapearl",
["max_quantity"] = 0,
["id"] = 1721,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Battle for Azeroth",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 12,
["name"] = "Seafarer's Dubloon",
["max_quantity"] = 0,
["id"] = 1710,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Battle for Azeroth",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Seal of Wartorn Fate",
["max_quantity"] = 5,
["id"] = 1580,
["quantity_earned_this_week"] = 0,
["category_header"] = "Battle for Azeroth",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Titan Residuum",
["max_quantity"] = 0,
["id"] = 1718,
["quantity_earned_this_week"] = 0,
["category_header"] = "Battle for Azeroth",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 4829,
["name"] = "War Resources",
["max_quantity"] = 0,
["id"] = 1560,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Battle for Azeroth",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 1359,
["name"] = "Ancient Mana",
["max_quantity"] = 1600,
["id"] = 1155,
["quantity_earned_this_week"] = 0,
["category_header"] = "Legion",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 35,
["name"] = "Curious Coin",
["max_quantity"] = 0,
["id"] = 1275,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Legion",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 587,
["name"] = "Legionfall War Supplies",
["max_quantity"] = 1000,
["id"] = 1342,
["quantity_earned_this_week"] = 0,
["category_header"] = "Legion",
},
{
["max_weekly_quantity"] = 20,
["quantity"] = 1,
["name"] = "Lingering Soul Fragment",
["max_quantity"] = 40,
["id"] = 1314,
["quantity_earned_this_week"] = 0,
["category_header"] = "Legion",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 4356,
["name"] = "Nethershard",
["max_quantity"] = 0,
["id"] = 1226,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Legion",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 62,
["name"] = "Order Resources",
["max_quantity"] = 0,
["id"] = 1220,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Legion",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 40,
["name"] = "Sightless Eye",
["max_quantity"] = 5000,
["id"] = 1149,
["quantity_earned_this_week"] = 0,
["category_header"] = "Legion",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 2000,
["name"] = "Veiled Argunite",
["max_quantity"] = 2000,
["id"] = 1508,
["is_account_wide"] = true,
["quantity_earned_this_week"] = 0,
["category_header"] = "Legion",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 3602,
["name"] = "Wakening Essence",
["max_quantity"] = 0,
["id"] = 1533,
["quantity_earned_this_week"] = 0,
["category_header"] = "Legion",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 0,
["name"] = "Artifact Fragment",
["max_quantity"] = 1000,
["id"] = 944,
["quantity_earned_this_week"] = 0,
["category_header"] = "Warlords of Draenor",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 3080,
["name"] = "Garrison Resources",
["max_quantity"] = 10000,
["id"] = 824,
["quantity_earned_this_week"] = 0,
["category_header"] = "Warlords of Draenor",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 8,
["name"] = "Lesser Charm of Good Fortune",
["max_quantity"] = 0,
["id"] = 738,
["quantity_earned_this_week"] = 0,
["category_header"] = "Mists of Pandaria",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 2,
["name"] = "Mote of Darkness",
["max_quantity"] = 0,
["id"] = 614,
["quantity_earned_this_week"] = 0,
["category_header"] = "Cataclysm",
},
{
["max_weekly_quantity"] = 0,
["quantity"] = 3,
["name"] = "Spirit Shard",
["max_quantity"] = 200,
["id"] = 1704,
["quantity_earned_this_week"] = 0,
["category_header"] = "Burning Crusade",
},
},
["partial"] = false,
},
},
},
["schema_version"] = 4,
["addon_folder"] = "AzerothDataCollector_Currencies",
["last_saved_at"] = 1778449755,
}
