
AzerothDataCollector_SpellsDB = {
["module_key"] = "spells",
["by_character"] = {
["Player-3674-0BB3F0D1"] = {
["spells"] = {
["updated_at"] = 1778448408,
["partial"] = false,
["records"] = {
{
["tab"] = "General",
["name"] = "Anomaly Detection Mark I",
["item_type"] = "1",
["id"] = 382499,
["spell_book_index"] = 1,
},
{
["tab"] = "General",
["name"] = "Arcane Torrent",
["item_type"] = "1",
["id"] = 80483,
["spell_book_index"] = 2,
},
{
["tab"] = "General",
["name"] = "Auto Attack",
["item_type"] = "1",
["id"] = 6603,
["spell_book_index"] = 3,
},
{
["tab"] = "General",
["name"] = "Auto Shot",
["item_type"] = "1",
["id"] = 75,
["spell_book_index"] = 4,
},
{
["tab"] = "General",
["name"] = "Mechanism Bypass",
["item_type"] = "1",
["id"] = 382501,
["spell_book_index"] = 5,
},
{
["tab"] = "General",
["name"] = "Recuperate",
["item_type"] = "1",
["id"] = 1231411,
["spell_book_index"] = 6,
},
{
["tab"] = "General",
["name"] = "Revive Battle Pets",
["item_type"] = "1",
["id"] = 125439,
["spell_book_index"] = 7,
},
{
["tab"] = "General",
["name"] = "Arcane Acuity",
["item_type"] = "1",
["id"] = 154742,
["spell_book_index"] = 10,
},
{
["tab"] = "General",
["name"] = "Arcane Affinity",
["item_type"] = "1",
["id"] = 28877,
["spell_book_index"] = 11,
},
{
["tab"] = "General",
["name"] = "Arcane Resistance",
["item_type"] = "1",
["id"] = 822,
["spell_book_index"] = 12,
},
{
["tab"] = "General",
["name"] = "Armor Skills",
["item_type"] = "1",
["id"] = 76250,
["spell_book_index"] = 13,
},
{
["tab"] = "General",
["name"] = "Battle for Azeroth Pathfinder",
["item_type"] = "1",
["id"] = 278833,
["spell_book_index"] = 14,
},
{
["tab"] = "General",
["name"] = "Journeyman Riding",
["item_type"] = "1",
["id"] = 33391,
["spell_book_index"] = 15,
},
{
["tab"] = "General",
["name"] = "Languages",
["item_type"] = "1",
["id"] = 79748,
["spell_book_index"] = 16,
},
{
["tab"] = "General",
["name"] = "Weapon Skills",
["item_type"] = "1",
["id"] = 76249,
["spell_book_index"] = 17,
},
{
["tab"] = "General",
["name"] = "Expert Riding",
["item_type"] = "2",
["id"] = 34090,
["spell_book_index"] = 18,
},
{
["tab"] = "General",
["name"] = "Master Riding",
["item_type"] = "2",
["id"] = 90265,
["spell_book_index"] = 19,
},
{
["tab"] = "Hunter",
["name"] = "Arcane Shot",
["item_type"] = "1",
["id"] = 185358,
["spell_book_index"] = 64,
},
{
["tab"] = "Hunter",
["name"] = "Aspect of the Cheetah",
["item_type"] = "1",
["id"] = 186257,
["spell_book_index"] = 65,
},
{
["tab"] = "Hunter",
["name"] = "Aspect of the Turtle",
["item_type"] = "1",
["id"] = 186265,
["spell_book_index"] = 66,
},
{
["tab"] = "Hunter",
["name"] = "Disengage",
["item_type"] = "1",
["id"] = 781,
["spell_book_index"] = 68,
},
{
["tab"] = "Hunter",
["name"] = "Exhilaration",
["item_type"] = "1",
["id"] = 109304,
["spell_book_index"] = 69,
},
{
["tab"] = "Hunter",
["name"] = "Feign Death",
["item_type"] = "1",
["id"] = 5384,
["spell_book_index"] = 70,
},
{
["tab"] = "Hunter",
["name"] = "Freezing Trap",
["item_type"] = "1",
["id"] = 187650,
["spell_book_index"] = 71,
},
{
["tab"] = "Hunter",
["name"] = "Hunter's Mark",
["item_type"] = "1",
["id"] = 257284,
["spell_book_index"] = 72,
},
{
["tab"] = "Hunter",
["name"] = "Kill Command",
["item_type"] = "1",
["id"] = 34026,
["spell_book_index"] = 73,
},
{
["tab"] = "Hunter",
["name"] = "Survival of the Fittest",
["item_type"] = "1",
["id"] = 264735,
["spell_book_index"] = 75,
},
{
["tab"] = "Hunter",
["name"] = "Wing Clip",
["item_type"] = "1",
["id"] = 195645,
["spell_book_index"] = 76,
},
{
["tab"] = "Hunter",
["name"] = "Call Pet 3",
["item_type"] = "2",
["id"] = 83243,
["spell_book_index"] = 77,
},
{
["tab"] = "Hunter",
["name"] = "Flare",
["item_type"] = "2",
["id"] = 1543,
["spell_book_index"] = 78,
},
{
["tab"] = "Hunter",
["name"] = "Command Pet",
["item_type"] = "2",
["id"] = 272651,
["spell_book_index"] = 79,
},
{
["tab"] = "Hunter",
["name"] = "Call Pet 4",
["item_type"] = "2",
["id"] = 83244,
["spell_book_index"] = 80,
},
{
["tab"] = "Hunter",
["name"] = "Call Pet 5",
["item_type"] = "2",
["id"] = 83245,
["spell_book_index"] = 81,
},
{
["tab"] = "Beast Mastery",
["name"] = "Barbed Shot",
["item_type"] = "1",
["id"] = 217200,
["spell_book_index"] = 91,
},
{
["tab"] = "Beast Mastery",
["name"] = "Exotic Beasts",
["item_type"] = "1",
["id"] = 53270,
["spell_book_index"] = 92,
},
{
["tab"] = "Beast Mastery",
["name"] = "Mastery: Master of Beasts",
["item_type"] = "1",
["id"] = 76657,
["spell_book_index"] = 93,
},
{
["tab"] = "Beast Mastery",
["name"] = "Eyes of the Beast",
["item_type"] = "2",
["id"] = 321297,
["spell_book_index"] = 94,
},
{
["tab"] = "Marksmanship",
["name"] = "Aimed Shot",
["item_type"] = "1",
["id"] = 19434,
["spell_book_index"] = 96,
},
{
["tab"] = "Marksmanship",
["name"] = "Explosive Shot",
["item_type"] = "1",
["id"] = 212431,
["spell_book_index"] = 97,
},
{
["tab"] = "Marksmanship",
["name"] = "Fetch: Eagle",
["item_type"] = "1",
["id"] = 1232995,
["spell_book_index"] = 98,
},
{
["tab"] = "Marksmanship",
["name"] = "Multi-Shot",
["item_type"] = "1",
["id"] = 257620,
["spell_book_index"] = 99,
},
{
["tab"] = "Marksmanship",
["name"] = "Rapid Fire",
["item_type"] = "1",
["id"] = 257044,
["spell_book_index"] = 100,
},
{
["tab"] = "Marksmanship",
["name"] = "Steady Shot",
["item_type"] = "1",
["id"] = 56641,
["spell_book_index"] = 101,
},
{
["tab"] = "Marksmanship",
["name"] = "Trueshot",
["item_type"] = "1",
["id"] = 288613,
["spell_book_index"] = 102,
},
{
["tab"] = "Marksmanship",
["name"] = "Volley",
["item_type"] = "1",
["id"] = 260243,
["spell_book_index"] = 103,
},
{
["tab"] = "Marksmanship",
["name"] = "Bleak Arrows",
["item_type"] = "1",
["id"] = 467749,
["spell_book_index"] = 104,
},
{
["tab"] = "Marksmanship",
["name"] = "Manhunter",
["item_type"] = "1",
["id"] = 1217788,
["spell_book_index"] = 105,
},
{
["tab"] = "Marksmanship",
["name"] = "Mastery: Sniper Training",
["item_type"] = "1",
["id"] = 193468,
["spell_book_index"] = 106,
},
{
["tab"] = "Marksmanship",
["name"] = "Spotter's Mark",
["item_type"] = "1",
["id"] = 1219616,
["spell_book_index"] = 107,
},
{
["tab"] = "Marksmanship",
["name"] = "Intimidation",
["item_type"] = "1",
["id"] = 474421,
["spell_book_index"] = 108,
},
{
["tab"] = "Marksmanship",
["name"] = "Air Superiority",
["item_type"] = "1",
["id"] = 470937,
["spell_book_index"] = 109,
},
{
["tab"] = "Marksmanship",
["name"] = "Eagle Eye",
["item_type"] = "1",
["id"] = 6197,
["spell_book_index"] = 110,
},
{
["tab"] = "Marksmanship",
["name"] = "Harrier's Cry",
["item_type"] = "1",
["id"] = 466904,
["spell_book_index"] = 111,
},
{
["tab"] = "Survival",
["name"] = "Boomstick",
["item_type"] = "1",
["id"] = 1261193,
["spell_book_index"] = 112,
},
{
["tab"] = "Survival",
["name"] = "Flamefang Pitch",
["item_type"] = "1",
["id"] = 1251592,
["spell_book_index"] = 113,
},
{
["tab"] = "Survival",
["name"] = "Harpoon",
["item_type"] = "1",
["id"] = 190925,
["spell_book_index"] = 114,
},
{
["tab"] = "Survival",
["name"] = "Hatchet Toss",
["item_type"] = "1",
["id"] = 193265,
["spell_book_index"] = 115,
},
{
["tab"] = "Survival",
["name"] = "Raptor Strike",
["item_type"] = "1",
["id"] = 186270,
["spell_book_index"] = 116,
},
{
["tab"] = "Survival",
["name"] = "Steady Shot",
["item_type"] = "1",
["id"] = 56641,
["spell_book_index"] = 117,
},
{
["tab"] = "Survival",
["name"] = "Takedown",
["item_type"] = "1",
["id"] = 1250646,
["spell_book_index"] = 118,
},
{
["tab"] = "Survival",
["name"] = "Mastery: Spirit Bond",
["item_type"] = "1",
["id"] = 263135,
["spell_book_index"] = 119,
},
{
["tab"] = "Survival",
["name"] = "Wildfire Bomb",
["item_type"] = "1",
["id"] = 259495,
["spell_book_index"] = 120,
},
{
["tab"] = "Survival",
["name"] = "Aspect of the Eagle",
["item_type"] = "1",
["id"] = 186289,
["spell_book_index"] = 121,
},
{
["tab"] = "Survival",
["name"] = "Eyes of the Beast",
["item_type"] = "1",
["id"] = 321297,
["spell_book_index"] = 122,
},
},
},
},
["Player-3674-09C5872B"] = {
["spells"] = {
["updated_at"] = 1778449754,
["records"] = {
{
["tab"] = "General",
["name"] = "Anomaly Detection Mark I",
["item_type"] = "1",
["id"] = 382499,
["spell_book_index"] = 1,
},
{
["tab"] = "General",
["name"] = "Arcane Torrent",
["item_type"] = "1",
["id"] = 202719,
["spell_book_index"] = 2,
},
{
["tab"] = "General",
["name"] = "Auto Attack",
["item_type"] = "1",
["id"] = 6603,
["spell_book_index"] = 3,
},
{
["tab"] = "General",
["name"] = "Mechanism Bypass",
["item_type"] = "1",
["id"] = 382501,
["spell_book_index"] = 6,
},
{
["tab"] = "General",
["name"] = "Recuperate",
["item_type"] = "1",
["id"] = 1231411,
["spell_book_index"] = 8,
},
{
["tab"] = "General",
["name"] = "Revive Battle Pets",
["item_type"] = "1",
["id"] = 125439,
["spell_book_index"] = 9,
},
{
["tab"] = "General",
["name"] = "Vindicaar Matrix Crystal",
["item_type"] = "1",
["id"] = 251463,
["spell_book_index"] = 12,
},
{
["tab"] = "General",
["name"] = "Arcane Acuity",
["item_type"] = "1",
["id"] = 154742,
["spell_book_index"] = 14,
},
{
["tab"] = "General",
["name"] = "Arcane Affinity",
["item_type"] = "1",
["id"] = 28877,
["spell_book_index"] = 15,
},
{
["tab"] = "General",
["name"] = "Arcane Resistance",
["item_type"] = "1",
["id"] = 822,
["spell_book_index"] = 16,
},
{
["tab"] = "General",
["name"] = "Armor Skills",
["item_type"] = "1",
["id"] = 202782,
["spell_book_index"] = 17,
},
{
["tab"] = "General",
["name"] = "Battle for Azeroth Pathfinder",
["item_type"] = "1",
["id"] = 278833,
["spell_book_index"] = 18,
},
{
["tab"] = "General",
["name"] = "Grove Invigoration",
["item_type"] = "1",
["id"] = 322721,
["spell_book_index"] = 19,
},
{
["tab"] = "General",
["name"] = "Languages",
["item_type"] = "1",
["id"] = 79748,
["spell_book_index"] = 20,
},
{
["tab"] = "General",
["name"] = "Master Riding",
["item_type"] = "1",
["id"] = 90265,
["spell_book_index"] = 21,
},
{
["tab"] = "General",
["name"] = "Weapon Skills",
["item_type"] = "1",
["id"] = 202783,
["spell_book_index"] = 22,
},
{
["tab"] = "Demon Hunter",
["name"] = "Consume Magic",
["item_type"] = "1",
["id"] = 278326,
["spell_book_index"] = 75,
},
{
["tab"] = "Demon Hunter",
["name"] = "Darkness",
["item_type"] = "1",
["id"] = 196718,
["spell_book_index"] = 76,
},
{
["tab"] = "Demon Hunter",
["name"] = "Disrupt",
["item_type"] = "1",
["id"] = 183752,
["spell_book_index"] = 77,
},
{
["tab"] = "Demon Hunter",
["name"] = "Glide",
["item_type"] = "1",
["id"] = 131347,
["spell_book_index"] = 78,
},
{
["tab"] = "Demon Hunter",
["name"] = "Immolation Aura",
["item_type"] = "1",
["id"] = 258920,
["spell_book_index"] = 79,
},
{
["tab"] = "Demon Hunter",
["name"] = "Imprison",
["item_type"] = "1",
["id"] = 217832,
["spell_book_index"] = 80,
},
{
["tab"] = "Demon Hunter",
["name"] = "Metamorphosis",
["item_type"] = "1",
["id"] = 191427,
["spell_book_index"] = 81,
},
{
["tab"] = "Demon Hunter",
["name"] = "Sigil of Misery",
["item_type"] = "1",
["id"] = 207684,
["spell_book_index"] = 82,
},
{
["tab"] = "Demon Hunter",
["name"] = "Spectral Sight",
["item_type"] = "1",
["id"] = 188501,
["spell_book_index"] = 83,
},
{
["tab"] = "Demon Hunter",
["name"] = "Throw Glaive",
["item_type"] = "1",
["id"] = 185123,
["spell_book_index"] = 84,
},
{
["tab"] = "Demon Hunter",
["name"] = "Torment",
["item_type"] = "1",
["id"] = 185245,
["spell_book_index"] = 85,
},
{
["tab"] = "Demon Hunter",
["name"] = "Vengeful Retreat",
["item_type"] = "1",
["id"] = 198793,
["spell_book_index"] = 86,
},
{
["tab"] = "Demon Hunter",
["name"] = "Chaos Brand",
["item_type"] = "1",
["id"] = 255260,
["spell_book_index"] = 87,
},
{
["tab"] = "Demon Hunter",
["name"] = "Double Jump",
["item_type"] = "1",
["id"] = 196055,
["spell_book_index"] = 88,
},
{
["tab"] = "Havoc",
["name"] = "Blade Dance",
["item_type"] = "1",
["id"] = 188499,
["spell_book_index"] = 91,
},
{
["tab"] = "Havoc",
["name"] = "Blur",
["item_type"] = "1",
["id"] = 198589,
["spell_book_index"] = 92,
},
{
["tab"] = "Havoc",
["name"] = "Chaos Nova",
["item_type"] = "1",
["id"] = 179057,
["spell_book_index"] = 93,
},
{
["tab"] = "Havoc",
["name"] = "Chaos Strike",
["item_type"] = "1",
["id"] = 162794,
["spell_book_index"] = 94,
},
{
["tab"] = "Havoc",
["name"] = "Eye Beam",
["item_type"] = "1",
["id"] = 198013,
["spell_book_index"] = 95,
},
{
["tab"] = "Havoc",
["name"] = "Fel Rush",
["item_type"] = "1",
["id"] = 195072,
["spell_book_index"] = 96,
},
{
["tab"] = "Havoc",
["name"] = "Felblade",
["item_type"] = "1",
["id"] = 232893,
["spell_book_index"] = 97,
},
{
["tab"] = "Havoc",
["name"] = "The Hunt",
["item_type"] = "1",
["id"] = 370965,
["spell_book_index"] = 98,
},
{
["tab"] = "Havoc",
["name"] = "Demon Blades",
["item_type"] = "1",
["id"] = 203555,
["spell_book_index"] = 99,
},
{
["tab"] = "Havoc",
["name"] = "Demonic Appetite",
["item_type"] = "1",
["id"] = 206478,
["spell_book_index"] = 100,
},
{
["tab"] = "Havoc",
["name"] = "Demonic Wards",
["item_type"] = "1",
["id"] = 278386,
["spell_book_index"] = 101,
},
{
["tab"] = "Havoc",
["name"] = "Mastery: Demonic Presence",
["item_type"] = "1",
["id"] = 185164,
["spell_book_index"] = 102,
},
{
["tab"] = "Havoc",
["name"] = "Shattered Souls",
["item_type"] = "1",
["id"] = 178940,
["spell_book_index"] = 103,
},
{
["tab"] = "Vengeance",
["name"] = "Demon Spikes",
["item_type"] = "1",
["id"] = 321028,
["spell_book_index"] = 105,
},
{
["tab"] = "Vengeance",
["name"] = "Demon Spikes",
["item_type"] = "1",
["id"] = 203720,
["spell_book_index"] = 106,
},
{
["tab"] = "Vengeance",
["name"] = "Fel Devastation",
["item_type"] = "1",
["id"] = 212084,
["spell_book_index"] = 107,
},
{
["tab"] = "Vengeance",
["name"] = "Fiery Brand",
["item_type"] = "1",
["id"] = 204021,
["spell_book_index"] = 108,
},
{
["tab"] = "Vengeance",
["name"] = "Demonic Wards",
["item_type"] = "1",
["id"] = 203513,
["spell_book_index"] = 109,
},
{
["tab"] = "Vengeance",
["name"] = "Fiery Brand",
["item_type"] = "1",
["id"] = 320962,
["spell_book_index"] = 110,
},
{
["tab"] = "Vengeance",
["name"] = "Fracture",
["item_type"] = "1",
["id"] = 263642,
["spell_book_index"] = 111,
},
{
["tab"] = "Vengeance",
["name"] = "Immolation Aura",
["item_type"] = "1",
["id"] = 320378,
["spell_book_index"] = 112,
},
{
["tab"] = "Vengeance",
["name"] = "Infernal Strike",
["item_type"] = "1",
["id"] = 189110,
["spell_book_index"] = 113,
},
{
["tab"] = "Vengeance",
["name"] = "Mastery: Fel Blood",
["item_type"] = "1",
["id"] = 321299,
["spell_book_index"] = 114,
},
{
["tab"] = "Vengeance",
["name"] = "Metamorphosis",
["item_type"] = "1",
["id"] = 187827,
["spell_book_index"] = 115,
},
{
["tab"] = "Vengeance",
["name"] = "Sigil of Chains",
["item_type"] = "1",
["id"] = 202138,
["spell_book_index"] = 116,
},
{
["tab"] = "Vengeance",
["name"] = "Sigil of Flame",
["item_type"] = "1",
["id"] = 204596,
["spell_book_index"] = 117,
},
{
["tab"] = "Vengeance",
["name"] = "Sigil of Silence",
["item_type"] = "1",
["id"] = 202137,
["spell_book_index"] = 118,
},
{
["tab"] = "Vengeance",
["name"] = "Sigil of Spite",
["item_type"] = "1",
["id"] = 390163,
["spell_book_index"] = 119,
},
{
["tab"] = "Vengeance",
["name"] = "Soul Carver",
["item_type"] = "1",
["id"] = 207407,
["spell_book_index"] = 120,
},
{
["tab"] = "Vengeance",
["name"] = "Soul Cleave",
["item_type"] = "1",
["id"] = 228477,
["spell_book_index"] = 121,
},
{
["tab"] = "Vengeance",
["name"] = "Spirit Bomb",
["item_type"] = "1",
["id"] = 247454,
["spell_book_index"] = 122,
},
{
["tab"] = "Vengeance",
["name"] = "Throw Glaive",
["item_type"] = "1",
["id"] = 204157,
["spell_book_index"] = 123,
},
{
["tab"] = "Vengeance",
["name"] = "Mastery: Fel Blood",
["item_type"] = "1",
["id"] = 203747,
["spell_book_index"] = 124,
},
{
["tab"] = "Vengeance",
["name"] = "Riposte",
["item_type"] = "1",
["id"] = 207197,
["spell_book_index"] = 125,
},
{
["tab"] = "Vengeance",
["name"] = "Shattered Souls",
["item_type"] = "1",
["id"] = 204254,
["spell_book_index"] = 126,
},
{
["tab"] = "Vengeance",
["name"] = "Thick Skin",
["item_type"] = "1",
["id"] = 320380,
["spell_book_index"] = 127,
},
{
["tab"] = "Devourer",
["name"] = "Blur",
["item_type"] = "1",
["id"] = 198589,
["spell_book_index"] = 128,
},
{
["tab"] = "Devourer",
["name"] = "Consume",
["item_type"] = "1",
["id"] = 473662,
["spell_book_index"] = 129,
},
{
["tab"] = "Devourer",
["name"] = "Reap",
["item_type"] = "1",
["id"] = 1226019,
["spell_book_index"] = 130,
},
{
["tab"] = "Devourer",
["name"] = "Shift",
["item_type"] = "1",
["id"] = 1234796,
["spell_book_index"] = 131,
},
{
["tab"] = "Devourer",
["name"] = "Soul Immolation",
["item_type"] = "1",
["id"] = 1241937,
["spell_book_index"] = 132,
},
{
["tab"] = "Devourer",
["name"] = "Spectral Sight",
["item_type"] = "1",
["id"] = 1251417,
["spell_book_index"] = 133,
},
{
["tab"] = "Devourer",
["name"] = "The Hunt",
["item_type"] = "1",
["id"] = 1246167,
["spell_book_index"] = 134,
},
{
["tab"] = "Devourer",
["name"] = "Void Metamorphosis",
["item_type"] = "1",
["id"] = 1217605,
["spell_book_index"] = 135,
},
{
["tab"] = "Devourer",
["name"] = "Void Nova",
["item_type"] = "1",
["id"] = 1234195,
["spell_book_index"] = 136,
},
{
["tab"] = "Devourer",
["name"] = "Void Ray",
["item_type"] = "1",
["id"] = 473728,
["spell_book_index"] = 137,
},
{
["tab"] = "Devourer",
["name"] = "Voidblade",
["item_type"] = "1",
["id"] = 1245412,
["spell_book_index"] = 138,
},
{
["tab"] = "Devourer",
["name"] = "Demonic Wards",
["item_type"] = "1",
["id"] = 1277736,
["spell_book_index"] = 139,
},
{
["tab"] = "Devourer",
["name"] = "Grim Focus",
["item_type"] = "1",
["id"] = 1260008,
["spell_book_index"] = 140,
},
{
["tab"] = "Devourer",
["name"] = "Mastery: Monster Within",
["item_type"] = "1",
["id"] = 1238855,
["spell_book_index"] = 141,
},
{
["tab"] = "Devourer",
["name"] = "Shattered Souls",
["item_type"] = "1",
["id"] = 1227619,
["spell_book_index"] = 142,
},
},
["partial"] = false,
},
},
},
["schema_version"] = 4,
["addon_folder"] = "AzerothDataCollector_Spells",
["last_saved_at"] = 1778449754,
}
